### ISSUE TITLE
 Receiving data of other tenant in the Multi Tenant installation customer - Lomond Capital(LOC)

### ISSUE THREAD

**Issue by rajeshwl** [reapit/foundations#10065]
**Describe the bug**
We are importing the transactions using the updated date, but seems we are receiving data of other tenant as well. Can you please check this and fix it out, it will help us to avoid billing and unnecessary data.

**Customer Code: LOC-GMOC**
End Point: `/transactions/`

**Expected behaviour**
We expect the endpoint to get filtered with office grouping or an option to pass the office id in the request params. As property id or tenancy id can't be passed, because we have large number of properties. But Office ID's will be few. 

Can you please prioritize this issue.

**Comment by AshDeeming** [comment]
Hi @rajeshwl 
Please can you provide more details, including the app name & any example references.

**Comment by rajeshwl** [comment]
@rajeshwl ,
App Name: Starberry DataXchange AWS

Transaction ID:
SWN23022412(This transaction belongs to property(TGD220148)

**Comment by plittlewood-rpt** [comment]
Hi @rajeshwl this will be happening because the transaction API data has to be filtered based on the client accounts the offices have access to. The reason you are getting these transactions is because they are assigned to a client account that offices in LOC-GMOC have access to. As such this is behaving as expected based on the customer's AgencyCloud configuration.

**Comment by plittlewood-rpt** [comment]
Hi @rajesh - the above should be sufficient to answer this, but if you still need assistance please reach back out to us.
