### ISSUE TITLE
Patch for `externalArea.max` field wouldn't saved (properties service)

### ISSUE THREAD

**Issue by ss-dimasm** [reapit/foundations#10109]
**Describe the bug**
Cannot save information on field `externalArea.max`, when do the patch action on properties service

**To Reproduce**
Steps to reproduce the behaviour eg:
1. Hit patch on properties service with the attached payload
2. Get the latest update for the property that has been updated
3. See unexpected result

**Expected behaviour**
We have sent the proper payload according to the documentation, so it should be saved

```json
{
  "externalArea": {
    "type": "acres",
    "min": 1,
    "max": 2
  }
}
```

**Additional context**
SBOX data

**Specification**
- Project: Reapit.Services.Properties
- Rather than removing the max field which would make the model look slightly odd, we should update the commentary on the Swagger documentation to make it clear that there is no corresponding field in AgencyCloud

**Comment by plittlewood-rpt** [comment]
Hi @ss-dimasm the external area model was designed with a range in mind in case AgencyCloud was ever updated to include an upper limit on the external area size. This hasn't happened however and there are no plans to do this so it's likely we will remove externalArea.max from the POST and PATCH models. We'll leave it in the GET model for now so that this isn't a breaking change, but we may remove it in a future version.

**Comment by ss-dimasm** [comment]
Thanks for the confirmation @plittlewood-rpt, does it would only happened on the `externalArea.max` field only? or is there any more fields that would be removed esp. on properties service? thanks

**Comment by plittlewood-rpt** [comment]
Hi @ss-dimasm just this one. I think we will just update commentary for now instead of remove it as it's a bit weird to have a min field with no max. In the future there is still a possibility of it coming into use.
