### ISSUE TITLE
As a client logging into the marketplace without admin permissions, I should not be able to perform certain actions

### ISSUE THREAD

**Issue by willmcvay** [reapit/foundations#1012]
**Summary:** As a client logging into the marketplace, without admin permissions (not part of CustomerAdministrators group), I should only be able to browse apps but not install them from the browse apps page

**Relates to ticket:** https://github.com/reapit/foundations/issues/1011

**Location:** https://dev.marketplace.reapit.cloud/client/apps

**Task:** 
- Use the access & ID token to see the group information
- You should extend the LoginIdentity object parsed in Cognito Auth package from the id token to set a new value "isAdmin"
- The hide the 'install' button when opening apps from the 'Browse Apps' page 
- Further actions to be permissioned TBC

**Comment by HollyJoyPhillips** [comment]
Hi @ant066, please can you hide the 'Install App' button rather than disabling it?

![image](https://user-images.githubusercontent.com/52408607/82218202-6ff55980-9913-11ea-8ccf-bd0cdf8c046f.png)

Also, when viewing the app in standalone mode, the button is not disabled, can you hide it in standalone mode also when the user is not an admin. 
![image](https://user-images.githubusercontent.com/52408607/82218222-78e62b00-9913-11ea-88c2-64acffc2c22d.png)
