### ISSUE TITLE
Failure to patch appointments

### ISSUE THREAD

**Issue by au63** [reapit/foundations#10217]
I am patching an appointment's follow up responseId and seeing this response

{"errors":[{"field":"PropertyId","message":"One or more of the related entities with the ids specified does not exist"}],"statusCode":422,"dateTime":"2023-11-23T09:11:15.9465339Z","description":"One or more validation failures have occurred. Please refer to Errors list for details"}

As this is a specific to a client, please let me know if is it okay to share details like client id and appointment id.

**Triage notes**
- This is happening becuase the property referenced in the appointment is archived
- As part of appointment create/update routines, we validate that the associated entities are valid to make sure third parties can't create appointments for invalid properties and contacts.
- The property check is not taking into account archived properties, which is why the validation failure is being thrown
- We should probably only run validation rules when the referenced entities are being changed anyway, so there's an opportunity to refactor here
- To replicate the problem, create an appointment for a live property, archived the property and then attempt to patch the appointment. You'll get a 422

**Specification**
- Project: Reapit.Services.Appointments
- Look at the best way of handling this problem. The developer who raised this ticket was _only_ patching the followUp.responseId property, and the payload did not contain any other fields. As a result, it's fair to expect that we wouldn't re-run the associated resource validation rules anyway as they weren't being changed. We should aim to update the API to only run this logic (`AppointmentRepository.ValidateReferencedKeysPropertiesAsync`) if the values actually change which will mean adjusting the order of operations slightly
- If the above isn't possible, we should add an archived property check to this function

**Comment by au63** [comment]
Email sent to sinfo@reapitfoundations.zendesk.com.

**Comment by plittlewood-rpt** [comment]
HI @au63 I have had a look at this today. You are unable to patch the appointment because the property that it is associated with has been archived. There is a hole in the validation logic which we need to fix that only checks the live property data when validating the referenced ids on the appointment (in this case property id NEW220416). I will add a specification to this ticket to fix the bug. In the meantime, I can set the follow up information on this appointment manually for you if you like. Please let me know. It's unusual for someone to be trying to patch appointments related to archived property resources, which is likely why this has never surfaced before now.
