### ISSUE TITLE
PropertyHive to Reapit connection issue...

### ISSUE THREAD

**Issue by Richjaw** [reapit/foundations#10220]
I'm being asked for 3 credentials to connect Reapit to our Propertyhive account,
URL:
User:
Pass:
I don't know where to find our URL, our ID is JOH though.
Am I to assume I use my reapit login for username and pass?

Thanks!

**Comment by AshDeeming** [comment]
Hi @Richjaw 
In order for a 3rd party to access a clients data, their app will need to be installed via the AppMarket - Credentials should not be sent to 3rd parties.

**Comment by Richjaw** [comment]
@AshDeeming I have the app installed from marketplace but clicking on it just brings me to the propertyhive website.

Within wordpress I'm only given these options to import...

![image](https://github.com/reapit/foundations/assets/151842161/220da80d-ad3c-45ed-9bd4-fbede3e2cada)

Any idea how to get this to work?

I'm more after advice with the propertyhive @propertyhive wordpress plugin.

**Comment by propertyhive** [comment]
@Richjaw You'll need to select 'Reapit Foundations API' from the dropdown instead of 'Reapit / JET'. 'Reapit / Jet' is their old SOAP API that's no longer supported.

**Comment by Richjaw** [comment]
@propertyhive I'm on the latest version of PH plugin but I don't have the reapit foundations on dropdown on the import section.

![image](https://github.com/reapit/foundations/assets/151842161/525d89dd-39f2-4eb8-8704-236c51dbe9fe)

Any ideas?

**Comment by propertyhive** [comment]
Good morning, We released Foundations support about 2 and half years ago so you must be using an old version from before then.

When you bought the import add on you bought that version at the time which didn't have Foundations support. In this time we've since developed this feature, and also changed our pricing and you can't buy add ons individually now. 

As a result, you would need to be on a pro subscription to get the latest version and also receive updates going forward:

https://wp-property-hive.com/pricing/?plan=import

As this is not a issue specific to Reapit please feel free to email me at info@wp-property-hive.com should there be any further questions.

Steve

**Comment by Richjaw** [comment]
@propertyhive Thank you!

Much appreciated.
