### ISSUE TITLE
Create proposal for work for Elements v2.0

### ISSUE THREAD

**Issue by willmcvay** [reapit/foundations#1029]
**Background context or User story:**

_We have an outstanding milestone for the Reapit Elements package v2.0. As Developers, we use the package internally and we know the package is not perfect, although it has done a good job for us. 

We have dev time available this year to do some refactoring and improvements. This task is to gather suggestions for work so we can schedule for development_

**Considerations:**

- The components **must** look and work the same for v2 even if they are different under the hood 
- The package is a mess of CSS modules and global styles - structure can be improved for maintainability and readability
- The purging of unused CSS in the build is messy and awkward
- Initially we thought we could re-factor in Styled Components but because we have so many non-react users, we **must** support an external stylesheet. 
- Open to suggestions on alternative frameworks but **must** be well supported, reasonably lightweight and export friendly classes
- Do we stick with Bulma? If we change it, we must remember point 1 to keep things looking and feeling the same
- Are there any third party libs we can bin, or change, or should upgrade?
- Are there any new components we can add to make life easier?

**Suggested solution:**

- Outcome is a "request for comments" from the team so we can agree as a group the best way forward and we can create issues from this. The document should be circulated to the team so everyone can have their say. The best solutions will be selected for dev_

**Comment by tanphamhaiduong** [comment]
@willmcvay @HollyJoyPhillips for version 2. I suggest we use this library to avoid re-innovate the wheel. So I think this library is also enough which we need to use and we'll create a wrapper to restyle as Reapit styles by styled-components.
https://react-component.github.io/badgeboard/
And we'll add Formik and re-export it from elements v2 for user easy to use it

**Comment by tanphamhaiduong** [comment]
# Request for Comments: Elements V2

## Stakeholders
- Cloud team
- Client using elements V1

## Problem
- For the elements V1 we wrapped by Formik as HOC and it's very hard for user who want use component only
- The styles messy and we need to clean up
- New code maintain easier than before because we remove formik inside component
![image](https://user-images.githubusercontent.com/22660833/81675568-376c0080-9479-11ea-8ff1-660bc24c15ab.png)
As example above it's very hard to maintain because there's lot of logic inside the component including formik logic

## Solution
- We'll use rc-componenents for the complex component like date picker, select dropdown, tables ...
- We'll style for component like elements V1 before by using linaria lib prefer to write like this to export css class for human reading
- We still use bulma.css for re export some style which which can be use by the users of elementv1
- Remove formik for elements
- Export formik from elements V2 to avoid conflict between dependencies of the app and dependencies of elements

## Verifying Solution
- We can write 1 or 2 components only apply to the apps and check it before do the whole one

## Risks
- It take bandwidth for create new elements V2
- It'll take time if we want to migrate the current app to elements V2

## Estimated Costs
- To avoid re-inovate the wheel we'll use rc-component and wrap it by our styles for complex components

## Implementation
- Use linaria and write style like the code below to make sure our style will export for human reading
```
import { css } from 'linaria';

// Create a class name
const title = css`
  font-size: 24px;
  font-weight: bold;
`;

function Heading() {
  // Pass it to a component
  return <h1 className={title}>This is a title</h1>;
}
```
## Rollback
- We'll still using the current ElementV1 and export ElementsV2 by v2 folder inside elementV1.
- We can write 1 or 2 components only apply to one small app. If there's error we only revert that components
