### ISSUE TITLE
Not all Property Images appearing when being searched by modified date

### ISSUE THREAD

**Issue by BYMIntegrationsDev1** [reapit/foundations#10351]
**Describe the bug**
Not all Property Images appearing when being searched by modified date

**To Reproduce**
Steps to reproduce the behaviour eg:
1. Go to https://platform.reapit.cloud/propertyImages/ for customer WNK
2. Search for Images by Property Id in this case 6 objects are returned (https://platform.reapit.cloud/propertyImages/?propertyId=EAL150076)
3. Now do a search by modified date that encompasses the modified dates returned in the query above. (https://platform.reapit.cloud/propertyImages/?pageSize=50&pageNumber=4&modifiedFrom=2021-07-16T01:00:51Z&modifiedTo=2021-07-17T01:00:51Z) - 4 pages returned
4. See error - The Images returned in step 2 are not in the images returned by the query in step 3

**Expected behaviour**
All property images that match a query should be returned.

**Specification**
- Project: Reapit.Services.PropertyImages
- Using the example provided, tunnel through to the WNK production environment to evaluate what's going on here.

**Comment by plittlewood-rpt** [comment]
Hi @BYMIntegrationsDev1 the behaviour you are seeing here is actually by design. The images that are not being returned are archived and do not get returned unless you explicitly provide the propertyId parameter. Historically we didn't return archived images at all, however item #4656 introduced the capability to return them when specifying one or more `propertyId` values in the query string to deal with an issue where images would not get embedded in calls to GET /properties?embed=images.

The property you mention above is also archived, so before deciding if there are any remedial actions to take, I'd query why you need these images at all. Can you shed any light on this please?

In terms of what could be done to resolve this, as you know there's no way currently to serve live and archived data in the same request, so it's likely we'd need to add a `fromArchive` query string parameter and associate property to the models so you could query both data sets. The behaviour of this API would then match that of other endpoints.

Thanks

**Comment by plittlewood-rpt** [comment]
Hi @BYMIntegrationsDev1 we have made the decision to introduce support for archived property images. The caveat here, as you'll note from the Swagger documentation, is that the physical asset for these resources might not always be available depending on the age of the record. This is just going out to production and will resolve your issue reported above, assuming you use the new `fromArchive` parameter in your query. As with other endpoints it is not currently possible to retrieve live and archived resources in the same call.
