### ISSUE TITLE
AG140181 - Fixflo sync not reflected in Reapit

### ISSUE THREAD

**Issue by TMoffat** [reapit/foundations#10668]
Alright you beautiful creatures.

Our shared client Edward Rose Property Group are having a wee issue with their sync. 

Despite being assigned correctly in Fixflo and the webhooks appearing successful, my dear friend Maureen is not being attached to the works order within the RPS.

Images redacted - see AD

Hopefully this is something you can help me with.

**Comment by plittlewood-rpt** [comment]
HI @TMoffat firstly apologies for the delay in getting back to you. I've had a look at the example provided and can see it was submitted to us with a negotiatorId of SXQ, which doesn't actually exist in this agent's system so I'd ask if you could ask your developers to figure out where that is coming from. I've gone a bit further and found lots more examples where you are passing a negotiatorId of SXQ in your request to POST /worksOrders, the most recent being at 15:22 today for the new works order attached to your system code IS14035804 (our request id for tracking purposes ee4355fb-e6af-4501-a295-c322af331ed0 / T9LbxFFJLPEERHw=). It looks therefore there's a wider issue here. There's some older examples where a negotiatorId of RRRD has also been provided which is invalid. I have logged a separate item to address the missing validation however I'll give you chance to address any issues at your end first otherwise it will cause problems with your integration. 

Can you come back to me on the above once you've had chance to speak to your developers?

**Comment by plittlewood-rpt** [comment]
Some further info which has just come to light. The user in question (Maureen, with a code of SXQ) actually exists in a different system which is under the LSL umbrella. This system also has the Edward Rose franchise in it so it looks like you might have some odd mapping going on in your own systems. SXQ exists in the RER dataset, and not the YOM dataset which is the one you've sent this particular example through to. Hope this sheds some light on the problem. Thanks

**Comment by TMoffat** [comment]
Hi Pete,

That's really useful, thank you for your assistance.

Excuse my ignorance but is this something the client can easily sort or
likely something that LSL will need to action for them?

Kind regards,
Tom

**Comment by plittlewood-rpt** [comment]
HI @TMoffat I don't think the customer will need to sort anything here. It's perfectly fine for them to have the two systems up the way they have, it feels like an issue with the mapping at Fixflo's end, but I can't comment on how that works.

**Comment by TMoffat** [comment]
Hi Pete,

With most of the other LSL franchises the majority have two Fixflo systems
looking at the different data sets. Edward Rose are slightly different in
that they only have one - YOM-GRYN. I'll need to get them to move Maureen
across to the correct data set but am just a bit unsure of how to advise
them on how to do this.

Kind regards,
Tom

**Comment by plittlewood-rpt** [comment]
Closing as per email thread.
