### ISSUE TITLE
Incorrect Offer status in Analytics Schema

### ISSUE THREAD

**Issue by ktanalyst** [reapit/foundations#10665]
**Describe the bug**
Bit of a strange one this - it's quite difficult to articulate the problem.

We had an offer on a property (code MTS180648) which was accepted on 15/01/2024, and was subsequently rejected on 31/01/2024. In the OFFERS view, this offer should have a status of 'Fallthrough' because it transitioned from Accepted to Rejected, but instead has  a Withdrawn status.

This is important because in order to identify which offer relates to an approved sale, we have to limit the results to offers which are either accepted, or have previously been accepted - this would include fallthrough, completed and exchanged. In an ideal world we would simply exclude offers which don't have an Accepted Date, however there is another related bug where all offers from the same applicant carry the same accepted date regardless of whether they were accepted or not (see below ticket):

https://github.com/reapit/foundations/issues/10107

It is also strange that when the code for this specific offer is ran using Data Warehouse, the Include in Pipeline field is showing as 'Yes', however this is unticked and greyed out on the platform (as below):

![image](https://github.com/reapit/foundations/assets/143076147/e0cde1c8-e05e-4bd5-8ebc-86ef8e446e08)

Why has this offer not been recognized as a Fallthrough? I don't know how many other records this is affecting as I've only picked it up while investigating something else. If I have misunderstood something about the way in which this process should work, please let me know the details.

**To Reproduce**
This code will isolate the offer which should be a fallthrough:
`SELECT *
FROM REAPIT.ANALYTICS_KLR.OFFERS
WHERE ID = '5fa8c74a6977c6b115548c183a78beeb'`

**Expected behaviour**
This offer should have a status of Fallthrough because it has transitioned from Accepted to Rejected, and should not be set to be included in pipeline. It should also have a fallthrough date logged.

**Screenshots**
Relevant offer detail changes between accepted and withdrawn:
![image](https://github.com/reapit/foundations/assets/143076147/bd3dda25-1a91-47b0-8776-b3584cf6c029)

**Device (please complete the following information for web issues):**
PC

**Comment by plittlewood-rpt** [comment]
Hi @ktanalyst 

The linked issue should be resolved in the next hour or so when the data next refreshes. I'll get the INCLUDE_IN_PIPELINE flag issue resolved as part of this item, it's because the UI in AgencyCloud just displays the box as unchecked if the offer status is withdrawn/rejected, regardless of what is set in the database (this offer does have the pipeline flag still checked, which looks to be a bug somewhere in AgencyCloud that I'll log with the appropriate team).

In terms of what I think is going on with the main issue here:

It looks to stem from the fact that there is no direct relationship between offer records and journal entries in the database. The status change dates are inferred from the journal entries written into the system rather than being stored against the offer directly. The analytics schema will attempt to attach offers to the correct journal entries when generating this data based on the applicant id, property id, and offer amount. What I _think_ has happened here is as follows:

- An offer of 170,500 was accepted on 15th Jan
- The accepted offer had it's amount changed from 170,500 to 155,500 on 31st Jan. 
- The accepted offer is then rejected on 31st Jan. This would normally be the action that triggers the offer status in the analytics schema to be shown as a Fallthrough, however...
- On 1st feb, this offer of 155,500 had it's status changed from rejected to withdrawn AND had it's amount changed back to 170,500. From my testing it looks like there is an issue with AgencyCloud in that it doesn't explicitly journalise the change in offer amount if the status changes in the same action. 

As the mechanism that joins to the journal entries to calculate status change dates users the offer amount in it's logic, the offer amount in the journal entry for going from accepted -> rejected is actually different to the offer amount and so it doesn't get picked up as a fallthrough (because it doesn't detected that it was ever accepted). We've actually got an internal engineering item that our AgencyCloud team will be looking at to look at ways we can include the offer id in journal entries as it will simplify this whole mechanism. I can't provide an ETA on this though unfortunately as it's quite intrusive to the inner mechanics of sales progression.

We do store a fallthrough date against the property, however to attribute it back to the correct offer we have to consider the offer amount and therefore with the data as it is, there isn't a great deal I can do about this particular example. If the offer amount was changed incorrectly, I can see if we can amend the journal data, however we typically have a strong stance on making any changes to this data as it's the chronological record of what happened during a property transaction and should therefore not be altered in any way. I'm going to raise the issue with our product team as I want to try and understand more about why we don't store the status change dates against the offers themselves. 

I'll let you know once I've resolved the issue with the Include in Pipeline flag, hopefully in the next day or so

Thanks

**Comment by plittlewood-rpt** [comment]
Internal ticket ACT-893 logged to deal with the bug in AC that doesn't clear the pipeline flag properly when an offer falls through.

**Comment by ktanalyst** [comment]
Thanks Pete, that's a very helpful explanation. I'm hoping this is just an isolated case, but I spoke to the person who updated this offer to understand their process. It seems to marry up with your theory that the offer status and amount were updated in the same action, which was a result of a buyer who already had an offer accepted changing their offer amount which was rejected by the vendor.

I'll await your final thoughts on this before reporting back on this issue.

Thanks

**Comment by plittlewood-rpt** [comment]
Hi @ktanalyst I've just merged the fix to ensure the pipeline flag value only gets set in the analytics schema for accepted offers. It's good to know that we seem to align on what's actually gone on here
