### ISSUE TITLE
Add Exchange Due field into OFFERS view

### ISSUE THREAD

**Issue by ktanalyst** [reapit/foundations#10755]
**Background context**
In the offer window there is a field called 'Exchange Due', which is a string field where the Sales Progressors can predict which month the property is likely to exchange. This is really useful for forecasting income and it would be extremely useful if this field could be added to the OFFERS view in the Analytics Schema so it can be pulled into our BI platform.

![image](https://github.com/reapit/foundations/assets/143076147/ac6bbd52-1e0d-4474-bf69-228ff761a94a)

**Specification**
- Project: Analytics Schema
- Add new `EXCHANGE_DUE` field to `OFFERS` property that exposes offers.extra.fExchange. This is a text field due to the nature of the data that can be stored and should be documented accordingly to make it clear that consumers are responsible for any data transformations
- Ensure documentation is updated

**Comment by plittlewood-rpt** [comment]
HI @ktanalyst we'll take a look at this in our next refinement session (Thursday). The reason it's not gone in to date is because it's a text field which means agents use it differently. Some agents enter specific dates, some enter a month as text, like you are doing above. This makes it lose some of the value as you can't really filter that data unless all the Exchange Due data is in the same format in your own dataset. It's likely this will be able to be added, but with a caveat that it will be down to each agent/consumer of that data to manage any transformations as we'll only be able to expose it as text.

**Comment by ktanalyst** [comment]
Thanks @plittlewood-rpt , where can I find the new field?

**Comment by plittlewood-rpt** [comment]
Hi @ktanalyst as always you'll need to refresh the data share in the data warehouse app. You can see the initial comment on this issue for the spec (new EXCHANGE_DUE field in the OFFERS view model). Cheers

**Comment by ktanalyst** [comment]
No problem. It wasn't in the documentation when I checked earlier but is now. Cheers
