### ISSUE TITLE
Is "type": "Land Type" a common custom field used by more than one agency?

### ISSUE THREAD

**Issue by Simon-Homeflow** [reapit/foundations#10758]
We are asking this on behalf of White & Sons Reapit ID WAS

Question: 

1. Is the "type": "Land Type" field used by multiple agents or specific to White and Sons?
2. Is  "type": "Style", field used by multiple agents or specific to White and Sons?

Postman response example:
"unmappedAttributes": [
                {
                    "type": "Land Type",
                    "value": "Pasture"
                },
                {
                    "type": "Style",
                    "value": "Stables"

The answer to this question will determine whether we map attributes or if we ask agent to use a different method.

**Comment by AshDeeming** [comment]
Hi @Simon-Homeflow 
Please confirm you have reviewed the below: https://foundations-documentation.reapit.cloud/platform-glossary#interpreting-department-data

If this is still unclear, please feel free to revert further

**Comment by Simon-Homeflow** [comment]
Thanks Ash, I have reveiwed the documentation and still do not understand as the sub-category? "Land Type" and "Style" and  value "Pasture" and "Stables" are not included in the documentation. I am a PM not a dev.

**Comment by HollyJoyPhillips** [comment]
Hi @Simon-Homeflow, if you cannot see the types in the 'mapped' values it will be listed under 'unmappedattributes'. This section in the documentation should hopefully help: https://foundations-documentation.reapit.cloud/whats-new#properties-api-6

**Comment by plittlewood-rpt** [comment]
HI @Simon-Homeflow to add to the above, anything you see in the unmappedAttributes collection isn't common across our customer base which is why they appear in that collection in the first place. When deciding how to handle the plethora of department options and 'what makes the cut' for the standard supported set, we did a heap of analysis on what options were in use out there. That's not to say we can't add to the list of supported attributes but we'd always recommend considering if any of the attributes _can_ be standardized to make integrations with other systems easier. This is something the agent's customer success manager at Reapit can help with, in conjunction with our service team if they decided it was something they wanted to explore.
