### ISSUE TITLE
Client RSB feedback dropdown returning no rows

### ISSUE THREAD

**Issue by Speedway1** [reapit/foundations#10763]
Dropdown menu in appointment 
Follow-up responses endpoint is returning no rows. 

This is the endpoint - /configuration/followUpResponses
Thank you

**Comment by Speedway1** [comment]
Hi All, is there an update on this please?

**Comment by plittlewood-rpt** [comment]
Hi @Speedway1 this customer are not using the pre-defined follow up feedback functions in the CRM which is why you are not getting anything back from that endpoint. They just enter follow up details manually, which is surfaced to you in the AppointmentModel returned from GET platform.reapit.cloud/appointments (`followUp.notes`). You should also note that for this customer `followUp.responseId` is always null/empty for the same reason. I hope this helps

**Comment by Speedway1** [comment]
The client is wanting to use this as part of the feedback service that we provide. The dropdown options included. How do we proceed? Thanks!

**Comment by plittlewood-rpt** [comment]
Hi there. The customer will need to reach out to our service team and request pre defined viewing feedback to be set up. Thanks
________________________________
From: Speedway1 ***@***.***>
Sent: Monday, February 26, 2024 9:21:58 PM
To: reapit/foundations ***@***.***>
Cc: Pete Littlewood ***@***.***>; Comment ***@***.***>
Subject: [EXTERNAL] Re: [reapit/foundations] Client RSB feedback dropdown returning no rows (Issue #10763)


External Message - Please be cautious when opening links or attachments in email
________________________________
The client is wanting to use this as part of the feedback service that we provide. The dropdown options included. How do we proceed? Thanks!

**Comment by Speedway1** [comment]
Thank you!
