### ISSUE TITLE
Can we get a CSV of the occupier's names from all tenancies for these client codes please?

### ISSUE THREAD

**Issue by GoYuno** [reapit/foundations#10859]
Timestamped CSV output to have... 

Client code
Property ID  
Address
Tenancy ID 
Tenancy Status 
Occupier names   

AEA,MTG,PAR,REG,SAV-GCHS,SAV-GUKL,URA

**Comment by AshDeeming** [comment]
Hi @GoYuno 
CSV outputs are not provided, you will need to use the related endpoints to pull the required data

**Comment by GoYuno** [comment]
you don’t have this available and the clients need us to have it.



Paul Conway

Founder & CEO of Yuno 


020 3848 2205 | 07701370756 | goyuno.com | ***@***.***









Reach UK Class of 2023 and Member of The Lettings Industry Council.

--- original message ---
On March 8, 2024 at 11:51 AM GMT ***@***.*** wrote:



Hi @GoYuno

CSV outputs are not provided, you will need to use the related endpoints to pull the required data

—

Reply to this email directly, view it on GitHub, or unsubscribe.

You are receiving this because you were mentioned.Message ID: ***@***.***>
--- end of original message ---

**Comment by plittlewood-rpt** [comment]
Hi @GoYuno - As my colleague states, we do not provide csv extracts of data from customer's databases from this Github project - any CSV extract is a point in time representation of the data, and in a customer like SAV that's an ever changing landscape. 

The customer can request this if it's absolutely necessary via our service desk. I would question that it sounds like you are trying to build an integration based on data that you _want_ to be available, rather than what _is_ available, all of which is well documented in the DeveloperPortal in the Docs -> API. Any data that you need access to via the API can be logged as a feature request and will be handled in accordance with our documented development processes however there is never a guarantee that all request logged will result in actionable work items.
