### ISSUE TITLE
Changes made via API shown as being made by a member of staff

### ISSUE THREAD

**Issue by robchett** [reapit/foundations#10864]
**Describe the bug**
When updating a Contact to change their marketing consent the change is being shown as made by a staff member when no staff were involved

**To Reproduce**
Steps to reproduce the behaviour eg:
1. Use PATCH /contacts/{id} to change marketing consent
4. See Activity feed for the contact

**Expected behaviour**
To show as API usage or unknown and not staff

**Screenshots**
 ![image](https://github.com/reapit/foundations/assets/5231691/5ebb4e30-8aed-4934-9aae-c80653611415)

**Device (please complete the following information for web issues):**
N/A

**Additional context**
N/A

**Comment by AshDeeming** [comment]
Thanks @robchett 
Please could you send any example Contact references & client Database ID to: sinfo@reapitfoundations.zendesk.com  for further review

**Comment by robchett** [comment]
@AshDeeming no problem, details sent

**Comment by plittlewood-rpt** [comment]
Hi @robchett this is by design. There is currently no way to attribute a journal entry to an app and as such where a journal entry is created by the API for a resource that has ownership information attached (in your case a contact is owned by one or more negotiators/offices) the journal entry will be attributed to the owner of the record. There is an item in the AgencyCloud engineering backlog to look at ways we can address this, as we've had a number of requests in the past about how to attribute journal records to an app rather than an individual. I can't see the email you've sent through but Ash will help me find it tomorrow, however I suspect you'll find that Francis Ewins is a negotiator on the contact record in the screenshot you've submitted. Thanks

**Comment by robchett** [comment]
Thanks @plittlewood-rpt. Happy to close this then if there is a ticket open elsewhere, I couldn't find one when looking at the issues list.

**Comment by plittlewood-rpt** [comment]
Thanks - linked item is #7013
