### ISSUE TITLE
Plus App staging pipeline is randomly sticking in Queued state

### ISSUE THREAD

**Issue by adrian-reapit** [reapit/foundations#10860]
**Describe the bug**
At random times the staging pipeline for Plus App will get stuck in Queued state and has to be cleared by cancelling the job in the database. This has happened several times in the past 2 weeks

**To Reproduce**
Trigger a pipeline build of Plus App at https://developers.reapit.cloud/apps/b328cd7c-82fa-49c1-a39b-a110a61e7c87/pipeline
Sometimes this stops in Queued

**Expected behaviour**
Build should complete or timeout after 10-15 mins of queueing or be manually cancelled with a 'Cancel' option in the dashboard

**Screenshots**
<img width="1102" alt="image" src="https://github.com/reapit/foundations/assets/152165863/d9e96e7d-1202-41b5-9be1-f09e54fa3e72">

**Comment by plittlewood-rpt** [comment]
@bashleigh would you mind reviewing this one please and adding a spec as necessary then we can look at getting this into a future sprint. Thanks

**Comment by bashleigh** [comment]
Remove `UnprocessableEntityException` from `deployPipeline` method within `GithubWebhookController`. 

The problem seems to be that the SQS message is not created after the pipeline runner entity is created with a status of `QUEUED`. This is likely because there are 6 concurrent promises running asynchronously which results in the pipeline runner being created and the exception is thrown within another concurrent run causing the SQS trigger not to happen. 

The image below is the log from the github webhook call which shows the 422 response from 17:00:00.  
<img width="765" alt="Screenshot 2024-03-19 at 16 25 17" src="https://github.com/reapit/foundations/assets/11574250/152f2329-b761-4125-b607-8521dde1a8e7">

Below is the code from the `deployPipeline` method

```ts
    if (
      pipeline.isPipelineDeploymentDisabled ||
      (await this.pipelineRunnerProvider.pipelineRunnerCountRunning(pipeline)) >= 1
    ) {
      throw new UnprocessableEntityException('Cannot create deployment in current state')
    }

    const pipelineRunner = await this.pipelineRunnerProvider.create({
      type: PipelineRunnerType.REPO,
      pipeline,
    })
    return Promise.all([
      this.eventDispatcher.triggerCodebuildExecutor(pipelineRunner),
      this.pusherProvider.trigger(`private-${pipeline.developerId}`, 'pipeline-runner-update', pipelineRunner),
    ])
```

Code from the handler that causes the concurrent asynchronous call

```ts
await Promise.all(pipelines.map((pipeline) => this.deployPipeline(pipeline, body)))
```
### To fix

To fix the issue, replace the throw `UnprocessableEntityException` to a console log and return within the condition. This will stop the prevention of other concurrent async calls from completing their run.

**Comment by abrahamseni** [comment]
@bashleigh 
I have the same issue with deployment.
The deploy button is on loading status, making it impossible to deploy manually.

![Screenshot 2024-03-21 024406](https://github.com/reapit/foundations/assets/94949137/d4fa00e1-1348-4cda-9e5d-8d0cdac45afc)

**Comment by bashleigh** [comment]
@abrahamseni can you send me the pipelineId/appId on teams please? Looks like the codebuild part failed which I've not seen before
