### ISSUE TITLE
Ticking "Apartment" in the Type section causes the RFPF API to return a null value

### ISSUE THREAD

**Issue by Simon-Homeflow** [reapit/foundations#10861]
**Describe the bug**
Ticking "Apartment" in ythe type field causes the RFPF API to return a nul value.

![image](https://github.com/reapit/foundations/assets/119927358/ddc56a0e-ae0c-4730-8d73-ff70ca8a5570)

Value returned in example:
![image](https://github.com/reapit/foundations/assets/119927358/cf57c84c-6c55-4396-a0be-fba1bc054154)

**To Reproduce**
Steps to reproduce the behaviour eg:
1. Go to 'Type" section in Reapit
2. Click on "Apartment"'
3. Send API request for property

**Expected behaviour**
Ticking "Apartment" in "Type" section adds a value of "apartment" or worst case "apartmentFlat" 

Apartment value is not documented.

Issue raised on behalf of White & Son Reapit ID WAS

**Specification**
- Projects; Reapit.Services.Departments, Reapit.Services.Applicants, Reapit.Services.Properties
- PL has replicated this and it's likely because both Flat and Apartment (as separate options) are both mapped to flatApartment in the API as these terms are typically used interchangeably and I've never seen both options as separate items in customer builds. As we have both options mapped to one type this might be something we can't do anything about and need to engage the CSM and customer to look at merging those two options together, however we should take the time to analyse the underlying cause. We could possibly look at ensuring Apartment gets returned in the unmappedAttributes list as this isn't happening either for some reason.
- Setup local build to have "Flat" and "Apartment" as separate property types in the TYPE column. Set a property or applicant to have just Apartment selected and observed that the types collection is empty.
- When resolved we should also confirm what happens for the write side. The outcome of passing flatApartment as a type in this kind of setup _should_ be that both Flat and Apartment get ticked

**Comment by plittlewood-rpt** [comment]
Hi @Simon-Homeflow it looks like this might be happening because the customer has both "Flat" and "Apartment" in their property type list which is very unusual as they tend to be terms used interchangeably. The Foundations API treats both terms the same and they are both meant to be badged as flatApartment. It looks like this is the only customer that has both options separated in their type list and there's a good chance this might be something we can't do anything about as it would effectively mean any write activity that sets type of flatApartment would result in both options being selected in the customers build which I suspect would be undesirable. We will discuss this in our next refinement session.

**Comment by RWilcox-Reapit** [comment]
Hi @Simon-Homeflow 
The properties API has now been updated to support multiple options mapping to the same field 'flatApartment' in this instance. 
This will be rolled out to Applicants and Departments in this follow-up ticket: #10987
Thanks
