### ISSUE TITLE
Can we access documents stored under 'Letters' via API?

### ISSUE THREAD

**Issue by amyfixflo** [reapit/foundations#10884]
Please take a look at our FAQ's before submitting an issue, as your question may already be covered in the documentation https://foundations-documentation.reapit.cloud/faqs

Fixflo are building an integration to sync PPM data from Reapit into Fixflo. To do this, we're accessing the Certificates stored against a Property in Reapit. However one client has said they store these documents under Letters rather than Certificates. Can we access this area via API? If so, please could you share the tech details for how we do this? We couldn't find anything in the API docs. Thanks!

**Detail and or supporting links and screenshots**

**Comment by plittlewood-rpt** [comment]
Hi @amyfixflo if the customer is storing them as documents against a property in the letters section, then yes you can. You just need to call `GET /documents?associatedType=property&associatedId=[propertyId]`. Hope this helps! We'd always encourage the customer to store the documents in the correct location, but ultimately they can choose to use the system in this way. Unfortunately due to the way they are doing it it's very likely you'll run into trouble attaching the documents back to the actual certificate resource. The only way to solve this problem is for the customer to store them in the correct location.
