### ISSUE TITLE
propertyImage url with embed feature on property service could have a different url

### ISSUE THREAD

**Issue by ss-dimasm** [reapit/foundations#10882]
**Describe the bug**
When accessing the property with propertyImages embedded, we could see the record with the proper data schema. However the propertyImage url it could have a wrong value for different customer Id.

**To Reproduce**
Steps to reproduce the behaviour eg:
1. Ensure to access with SBOX account
1. Hit property service with propertyImage embedded (propertyId: BCK150041)
2. Find the first embedded property image index, and see the url value
3. it will return a value, but we can't access the image url link with forbidden exception (invalid path)

**Expected behaviour**
seems we could have the valid property image link

**Additional context**
account to try is using `SBOX` customer id

if we try with SBOX id then the first embedded propertyImage would have this url (inaccessible) -https://assets.reapit.net/sbox/live/pictures/BCK/15/BCK150041_32.jpg (inaccessible - with SBOX id)
but if we access with ROD id, the first embedded propertyImage would have the different link (which is accessible)
https://assets.reapit.net/rod/live/pictures/BCK/15/BCK150041_32.jpg

**Comment by plittlewood-rpt** [comment]
HI @ss-dimasm this is just very old data. The physical image assets don't exist for that image in the sandbox, but they do in the ROD deployment. I suspect what's happened is the same database template was used when the ROD deployment was set up (which is why you've got files with the same reference, though its worth noting that those ids aren't globally unique anyway between systems), and this has had it's assets for older properties copied over, whereas they don't exist in the Sandbox any longer. There's nothing to really _fix_ here. We do have a mechanism for cleaning orphaned picture records from the database (where there is no corresponding file asset) which we could arrange to run on the Sandbox

**Comment by ss-dimasm** [comment]
ah! okay; so that's how they're work, thanks @plittlewood-rpt I'll close this issue
