### ISSUE TITLE
Fetching compliance documents but not appearing 

### ISSUE THREAD

**Issue by raymond2323** [reapit/foundations#10900]
Production Client: RER-GROS

Agent is telling us that compliance documents are available against the property with ID: DCI210145 in the UI

We are fetching the documents using the following endpoint but we are receiving nothing. 

https://platform.reapit.cloud/documents?associatedType=certificate&associatedId=HAP21001194

Any idea what we are doing wrong. 

We are using the following types for this agent: EI, GS, EC

<img width="1115" alt="image" src="https://github.com/reapit/foundations/assets/17427875/0c6f5365-9bc2-4aa7-955b-a3ab629f777b">

**Comment by plittlewood-rpt** [comment]
Hi @raymond2323 I've had a look at this and it looks like the customer has added the documents against the property rather than the certificate itself which is why you're seeing what you're seeing. As a result you need to fetch documents for the property, not for the certificate:

`GET /documents?associatedType=property&associatedId=DCI210145`

This customer does have document categories setup so you should be able to further filter by `typeId` - it's worth noting that it's dependent on the correct categorisation being applied by the end users:

![image](https://github.com/reapit/foundations/assets/30798627/7327723b-c13b-4a84-9a5a-bcf105374282)

I would try to encourage the users to store the certificate documents in the correct location so your experience with the API is correct and as designed.

Hope this helps :)

**Comment by raymond2323** [comment]
@plittlewood-rpt great that makes sense. Will speak to the customer. We can close the ticket.
