### ISSUE TITLE
Connect Session Server throws error

### ISSUE THREAD

**Issue by willmcvay** [reapit/foundations#10935]
**Background context or User story:**

_Not sure how many people use it but the Connect Session server function is broken. Instantiating the `ReapitConnectServerSession` class in a simple node script throws an error "ReferenceError: self is not defined:" - my guess is one of the methods is not bound to "this"._

**Specification or Acceptance Criteria:**

- Should correctly instantiate the server session class

**Replication Steps**
- Use the https://github.com/reapit/foundations-code-examples/tree/main/node-website-feed project
- Upgrade the reapit connect session package and other dependencies to see the error

**Comment by bashleigh** [comment]
Would you know their typescript/javascript setup? Sounds like a esbuild/ecmascript problem?

**Comment by willmcvay** [comment]
@bashleigh  https://github.com/reapit/foundations-code-examples/tree/main/node-website-feed

I found the bug trying to update the dependencies in this simple Node example - upgrade connect session and you should see

**Comment by bashleigh** [comment]
Thanks Will. Looking at that repo I think the problem is definately related to the build of the packages. I'd recommend we split the server package out into a seperate package and or with it's own seperate build method so we can include node and other requirements without the frontend related requirements
