### ISSUE TITLE
documents API returning 500 status

### ISSUE THREAD

**Issue by chestertons** [reapit/foundations#10964]
Attempting to retrieve data from https://platform.reapit.cloud/documents/?PageNumber=1&PageSize=100&sortBy=modified&modifiedFrom=2024-03-26T14:31:37Z

response is 
(
    [statusCode] => 500
    [dateTime] => 2024-03-27T11:55:26.7315594Z
    [description] => An unexpected error has been encountered when fulfilling this request. This incident has been logged and will be investigated. Please try again.
)

**Comment by AshDeeming** [comment]
Hi @chestertons 
Please could you advise which app this is referring to, along with which database i.e. SBOX or production?

**Comment by chestertons** [comment]
Production

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by plittlewood-rpt** [comment]
HI @chestertons I'm already aware of this from the logs and actively investigating. Thanks

**Comment by plittlewood-rpt** [comment]
Hi @chestertons this should now be resolved. There was some very old P2 Gold data lurking in the system which didn't have any record register information against it - one of those documents was amended recently which left the API in a state where it couldn't handle the row presented by the database. I've now populated this based on when the original conversion took place and no longer receive the error when making the same call as you. Please can you confirm the problem is now resolved for you also?

**Comment by plittlewood-rpt** [comment]
HI @chestertons the easiest thing to do is reach out via sinfo@reapitfoundations.zendesk.com where this can be discussed. Ultimately it's very old data that's causing these issues and it would be something our service desk needed to get involved in to resolve initially.
