### ISSUE TITLE
Tenancy Type is being erased when manually changing tenancy status from Arranging Tenancy to Current Tenancy 

### ISSUE THREAD

**Issue by raymond2323** [reapit/foundations#10978]
Production client with custom ID: RER-GFAL

Tenancies are being created and updated using POST Tenancy endpoint, and the tenancy type is correctly set to Assured Shorthold Tenancy. 

The Agent is manually setting (not through the API), setting the tenancy staus from Arranging Tenancy to Current Tenancy. When doing so, the Tenancy type is becoming blank. 

Any ideas why this is happening - Example tenancies are RPT241709 and RPT241893

Any reason for this happening?

**Comment by AshDeeming** [comment]
attempted to replicate on SBOX - TenancyID  - MKT230229 - 
Tenancy Type remained once tenancy status updated in CRM.

**Comment by raymond2323** [comment]
@AshDeeming  this is something specific to LSL I believe. 
@plittlewood-rpt maybe you can provide some insight. I can forward some screenshots if that helps?

**Comment by plittlewood-rpt** [comment]
Hi @raymond2323 I've had a look at one of the tenancies you've provided (RPT241709) and the typeId is being returned as AN as expected. Can I just confirm it's `TenancyModel.typeId` you're referring to here? Please feel to send any supporting doucmentation to me via email or to sinfo@reapitfoundations.zendesk.com

**Comment by plittlewood-rpt** [comment]
Hi @raymond2323 thanks - this looks like an AgencyCloud problem explicitly. I thought you meant the API was surfacing a blank tenancy type property when it was displayed in AgencyCloud, not that it wasn't displaying in the CRM itself. We'll get this looked into

**Comment by plittlewood-rpt** [comment]
Hi @raymond2323 I've had a look at this and found one of the PATCH events for one of the examples you provided. You are passing a typeId as "AS" which doesn't exist in this customer's system. When the CRM encounters a value it doesn't understand, it will appear as though nothing is selected. We will need to fix up the validation on the tenancies API which as it stands right now will be a breaking change for you due to passing the invalid value, so we'll hang fire releasing anything. You can access the list of tenancy types for a given customer at GET /configuration/tenancyTypes. Can you have a look to see if you've got "AS" hard wired anywhere in your own code?

**Comment by plittlewood-rpt** [comment]
hi @raymond2323 i'll close this item down. You can follow the linked ticket for updates on the validation - if you have any questions please reach out
