### ISSUE TITLE
Inquiry: Webhook Trigger for New Negotiator?

### ISSUE THREAD

**Issue by olorunfemiprospectorpro** [reapit/foundations#11030]
I will like to inquire whether a webhook is triggered when a new negotiator is created.

Looking forward to your response.

**Comment by HollyJoyPhillips** [comment]
Hi @olorunfemiprospectorpro, due to the structure of the DB in our Reapit CRM we cannot provide a topic for negotiators. We have the following ticket https://github.com/reapit/foundations/issues/6297 to address this in our long term backlog when the relevant changes have been made in the core product. I'll close this ticket but please subscribe for any updates .
