### ISSUE TITLE
Access to sandbox

### ISSUE THREAD

**Issue by katedeedman** [reapit/foundations#11097]
Hi team,

We're attempting to access our Reapit sandbox but being met with some error messaging. Have screenshotted and attached to this. 

![image (103)](https://github.com/reapit/foundations/assets/117754771/25fc1dbe-22d3-4f37-9014-b2c195ce983e)
[ZI0DHM0Z.log](https://github.com/reapit/foundations/files/15176586/ZI0DHM0Z.log)

Let me know if you need anything else from me.

-Kate 

(PM at Fixflo)

**Comment by katedeedman** [comment]
Hello! 

Sorry to reopen - we thought it just needed upgrading but that doesn't seem to have worked. Trying to install version 12.182.1.

-Kate

**Comment by AshDeeming** [comment]
Hi @katedeedman Please could you delete the current & previous versions in the registry

- Press Windows Key + R: This key combination opens the Run dialog box.
- Type “regedit”: In the Run dialog box, type “regedit” (without quotes) into the text field.
- Press Enter or click OK: Hit Enter on your keyboard or click OK to launch the Registry Editor

- Find CurrentVersion & PreviousVersion (HKEY_CURRENT_USER, SOFTWARE, Reapit
- right click both & delete.

Then relaunch RPS Developer Edition & you should see the Reapit Connect screen.

**Comment by asovdefixflo** [comment]
Hi, @katedeedman forwarded me your solution. I had previously tried to uninstall the old Reapit version and install a newer version (still getting the error message that was reported above). 
When looking in my registry under Reapit there was no CurrentVersion and PreviousVersion (perhaps it's because I uninstalled it).

![image](https://github.com/reapit/foundations/assets/118007795/71ff3e4b-dae9-4296-9e25-98cb393b76ac)

I tried to delete the Reapit registry keys and tried to restart the installation, but were still getting the error.

**Comment by asovdefixflo** [comment]
@AshDeeming any updates?

**Comment by AshDeeming** [comment]
Hi @asovdefixflo 
Please could you confirm you are launching the link via Edge once the versions have been cleared?

**Comment by katedeedman** [comment]
Ahh we've got that working now in Edge.

Thanks, Ash!
