### ISSUE TITLE
Interactive API Explorer with multiple Customer IDs

### ISSUE THREAD

**Issue by timr-yougroup** [reapit/foundations#11103]
We've recently added a second customer ID to our app but the interactive API explorer only returns data from the original customer. Is it possible to see the data from both? Would be useful as a way of quickly verifying something.  

Tested on the 'properties/{id}' endpoint, it returns the property data as our "first" initial customer sees it, and not as our new customer sees it. Actual API requests work fine but I was wondering if it was possible to do this on the interactive API explorer?

**Comment by plittlewood-rpt** [comment]
Hi @timr-yougroup the interactive API explorer will only allow you to see data that you as a developer can see. Typically that's just sandbox data, but in the case of a developer that belongs to one of our customer organisations which may be the case for you, you'd also be able to change your developer profile on the Profile page so that you get live customer data. It isn't possible to request data through the interactive explorer for one of your installations.
