### ISSUE TITLE
Client Services Dealbook Down

### ISSUE THREAD

**Issue by OliviaBDC** [reapit/foundations#11129]
![Snowflake](https://github.com/reapit/foundations/assets/169380805/e4aa946b-3c3b-47c8-aefb-987c104e956c)

Hello,

We're having an issue with data being sent through a database which has caused our Client Services Dealbook to stop functioning. We’ve looked in to the issue and from the logs the Snowflake database is returning an error to the query. The error started on 7th May at 10:19 so there has either been a change in the data structure, or there is an offending record that is failing query to run successfully.

The error response that displays in the Snowflake console is attached and would indicate an error with the GETEXTRA field – please see attached.

Let us know if you need additional information to get this resolved.

**Comment by OliviaBDC** [comment]
Can someone get on this please

**Comment by plittlewood-rpt** [comment]
Hi @OliviaBDC this is happening because you are trying to join on the value from GetExtra. The first parameter of this function may actually be null in your case because your earlier joins might fail. There are two ways you can resolve this:

1) Change your LEFT JOIN prp to INNER JOIN prp. This will ensure that prp.extra always exists when doing your later join using GetExtra() or 
2) Alter your join that's using GetExtra in the join condition to be `GetExtra(IFNULL(prp.extra, ''), 'pOldVendor')` as this will handle scenarios where you've got a diary appointment but no corresponding property

This could have started occurring because of properties being archived either by the branch or as part of bulk housekeeping processes.

**Comment by OliviaBDC** [comment]
Thank you! I have passed this back to dealbook for now
