### ISSUE TITLE
`outsideSpace` not being saved on applicant when created via the API.

### ISSUE THREAD

**Issue by seanhinton** [reapit/foundations#11188]
**Describe the bug**
`outsideSpace` not being saved on applicant when created via the API.

**To Reproduce**

Create an applicant via the API with the type/style/situation info as follows to the api end point `POST /applicants/`:

```
"type": [
    "house",
    "bungalow",
    "flatApartment"
  ],
  "style": [
    "terraced",
    "detached",
    "semiDetached",
    "linkDetached"
  ],
  "situation": [
    "outsideSpace"
   ],
```

The applicant when looked up afterwards is created without the `outsideSpace` option on situation:

This is what you get when you look up the created applicant above:

```
"type": [
    "house",
    "bungalow",
    "flatApartment"
  ],
  "style": [
    "terraced",
    "detached",
    "semiDetached",
    "linkDetached"
  ],
  "situation": [],
```

**Expected behaviour**

The applicant should have outside space as it was submitted:

```
"type": [
    "house",
    "bungalow",
    "flatApartment"
  ],
  "style": [
    "terraced",
    "detached",
    "semiDetached",
    "linkDetached"
  ],
  "situation": [
    "outsideSpace"
   ],
```

**Device:**
This is via the api.

**Additional context**

**Specification**
- To discuss: consider adding department validation

**Comment by plittlewood-rpt** [comment]
hi @seanhinton please can you confirm which customer you are working on behalf of and the example above relates to (or indeed if it's the Sandbox environment)?

**Comment by seanhinton** [comment]
@plittlewood-rpt this was an applicant created in the sandbox with the above . Would you like me to create an example and post the id here?

So an applicant was created and the relevant feilds were:

```
"type": [
    "house",
    "bungalow",
    "flatApartment"
  ],
  "style": [
    "terraced",
    "detached",
    "semiDetached",
    "linkDetached"
  ],
  "situation": [
    "outsideSpace"
   ],
```
And then `situation` returned a blank array when that applicant was looked up afterwards.

Is there anything that would prevent `outsideSpace` from being saved?

What's also interesting is that other values are rejected, so `outsideSpaceABC` will return an error, but `outsideSpace` is valid to be submitted but is never saved.

**Comment by plittlewood-rpt** [comment]
Hi @seanhinton Outside Space is not actually available on the Sandbox which is why it's not saving. The available options for each customer can be obtained at GET /departments which should help you. We are missing a little validation here in the API. You'll get an error if you pass a completely unsupported value (ie myRandomValue) but you won't get an error if you pass a supported value that doesn't exist in the customers configuration (Sandbox in this case). I'll spec this item out to consider adding some extra validation, however you will want to be making sure you check the response from GET /departments to understand what options are available in each build. I hope this helps, please let me know if anything is unclear. Thanks

**Comment by seanhinton** [comment]
@plittlewood-rpt Ok, thanks, that's super helpful! Cheers for this. I think this is good to close then as it's a non-issue. Thanks again.
