### ISSUE TITLE
Customer unable to see document uploaded via api

### ISSUE THREAD

**Issue by iWader** [reapit/foundations#11218]
**Describe the bug**

We've uploaded a document to the tenancy, however the customer is unable to see this document in RPS

Document looks to have uploaded all correctly. We can retrieve this document both via the id and searching documents for the relevant tenancy.

Property `TIL120043`
Appointment `TIL1700041`
Tenancy `TAL160016`
Document `RPT24016820`

**To Reproduce**

1. `POST /documents/signedUrl`
2. `POST <signedUrl>`
3. `POST /documents` with below payload

```json
{
    "associatedType": "tenancy",
    "associatedId": "TAL160016",
    "typeId": "FPI",
    "name": "Property Inspection on 2024-06-01.pdf",
    "fileUrl": "<signedUrl>"
}
```

**Expected behaviour**

Customer can see the document when viewing property/tenancy letters

**Additional context**

Ashley asked us to file this issue and suggested is possibly related to the users office groups.

**Comment by iWader** [comment]
It's Parkers Properties

**Comment by plittlewood-rpt** [comment]
Thanks. I can see this document fine against the tenancy, which is what you're attaching to (slight difference in the filename but assuming that's expected)

![image](https://github.com/reapit/foundations/assets/30798627/267b56b5-c383-49a3-8d1a-0a7d75f80827)

Please can you confirm what the customer is expecting so we can try to work backwards?

**Comment by iWader** [comment]
Different document name is expected, mine was just a sample payload. Confirmed that the timestamp of `2024-06-10T17:04:14` from our logs matches up with timestamp in your screenshot.

We've requested further examples from the customer.

**Comment by plittlewood-rpt** [comment]
Thanks very much. I have a hunch that they might be expecting to be able to see this either in the property letters section (which won't happen because the document is attached to the tenancy), or possibly they're expecting it to be attached to the inspectionn appointment. If the latter, you need to PATCH the respective appointment, setting the documents properties respectively eg:

```
PATCH /appointments/{id}
{
   "documents": {
       "finalPropertyInspectionReportId": "ABC1234567"
   }
}
```

ABC1234567 would be your document id, so RPT24016820 in your above example. This will cause AgencyCloud to link the appointment to the document:

![image](https://github.com/reapit/foundations/assets/30798627/52c7df66-3bda-48b6-854c-dcd64da9e4e8)

This is a fairly new feature so it might be that you're not aware of it. There's also the facility to upload a draft report, please refer to the Swagger spec for `PATCH /appointments/{id}` for more details

**Comment by iWader** [comment]
We should already be updating the documents on the appointment, from our logs I see we attempted to do this. I have added more detailed logging to confirm the api responds as expected. 

Waiting on further examples and details from the customer.

**Comment by iWader** [comment]
Have received no further updates on my side for this, so assume the issue the customer was facing is resolved.
