### ISSUE TITLE
Webhooks not received for enabled Customer ID

### ISSUE THREAD

**Issue by olliebennett** [reapit/foundations#11228]
We (Goodlord) recently enabled a customer - `LSLi (LSI)` - for the `tenancy.modified` webhook (which we use for a few other customers already).

The customer informs us that they have modified multiple tenancies in the last few days, but no webhook has been received.

Please could you check our permissions, or identify any other reason why the webhook may not be received?

Example properties in which the tenancy was modified;

Address: 501 Eden Apartments / Ref: JLE080216
Address: 509 Eden Apartments / Ref: JLE090296

Thanks

**Comment by plittlewood-rpt** [comment]
Hi @olliebennett it seems that event capture had not been switched on for this customer which is why the webhooks were not being sent. I've set this up now and forced events through for the two tenancies you mention above. You should receive updates for this customer going forwards. If you can confirm receipt before I close this issue down I'd be grateful. Many thanks

**Comment by olliebennett** [comment]
Thanks very much, Pete - yep the webhooks are coming through now. 👍
