### ISSUE TITLE
Unable to connect Reapit Bookings integration

### ISSUE THREAD

**Issue by jazzlall** [reapit/foundations#11231]
We're receiving an issue when trying to connect Bookings to a clients Reapit database. 
After retrieving the logs from IRE's end it's returning the following error 

{
    "statusCode": 500,
    "dateTime": "2024-06-13T12:05:04.2857173Z",
    "description": "An unexpected error has been encountered when fulfilling this request. This incident has been logged and will be investigated. Please try again."
}

The full client code we're using to connect because the marketplace groups **SAU-GUKL**. They have successfully installed it which you can see in the Marketplace admin page for the app.  Could this be investigated as we're attempting to UAT with them shortly. 
Thanks

**Comment by plittlewood-rpt** [comment]
Hi @jazzlall the database queries are timing out, likely due to the database size. We'll review them, but unfortunately there's not a great deal we can do as it stands at the moment as the query looks to be as performant as it can be, however there's some work in flight in AgencyCloud to improve how we store (and therefore) office relationships which is ultimately what's causing the problem here because the GUKL office group has a really long list of offices in it. From the query it looks like you're trying to pull all properties of a certain type for this office group. Do you really need _all_ properties to come back? You'll be able to improve performance by reviewing how you're calling the API, and including additional filters to shrink the resultset.

**Comment by jazzlall** [comment]
Understood, I'll have to get the team to add some additional detail here as I can't explain technically what happens when we try enable the integration. 

The steps we follow in the UI is to enter the company code for the database we're connecting to. After that we then specify the office codes for the properties we want which in this case and in most cases won't be every single office in a clients build. I can show you a live demo of this on a demo system but it won't give much more insight to what I've already explained.

**Comment by jazzlall** [comment]
Feedback from the team:  
We are currently hitting the property endpoint with no filters to grab any property and confirm that we get data back for the customer ID to validate the company database code. 

We are asking for "?pageSize=1&pageNumber=1", but evidently that is still grabbing all the properties to calculate the pages. Are we able to include a parameter to just grab any 1 property from the database without needing more pages calculated? If not, we can work out something else to confirm the customer ID is connected.

**Comment by jazzlall** [comment]
Thanks Pete, will suggest that and something we'll amend going forward.
