### ISSUE TITLE
Linley Simson contact audit

### ISSUE THREAD

**Issue by BYMIntegrations** [reapit/foundations#11237]
Please take a look at our FAQ's before submitting an issue, as your question may already be covered in the documentation https://foundations-documentation.reapit.cloud/faqs

**Summary**

Can you please supply us with a date and time for when the contact LLN24000017 was marked as consent denied for the customer Linley Simson

**Detail and or supporting links and screenshots**

The customer is claiming that this contact should already be marked as consent denied in their BYM system but I can see the last modified date was earlier today.

**Comment by plittlewood-rpt** [comment]
Hi @BYMIntegrations  this contact was marked as Consent Denied at 1:39pm today (17/06/2024). There have been no other changes since the contact was registered on 20/02/2024 when the initial marketing consent was set to "Not Asked" which should be inferred as denied given they haven't explicitly opted in to marketing communications.  It's worth noting that assuming your app has access to journal data, you should be able to check this data yourslef by calling GET /journalEntries?associatedType=contact&associatedId=LLN240000017&typeId=CC

Please let me know if you need any further assistance else I'd be grateful if you can close this down if you have all the information you need. Many thanks
