### ISSUE TITLE
GET Appointment API endpoint returns 500 error code

### ISSUE THREAD

**Issue by paganvarg** [reapit/foundations#11308]
**Background context**
When I make GET call to `/appointments?start=2024-07-17&sortBy=-start&officeId=MYS&includeCancelled=true&pageSize=25` endpoint I keep getting 500 error code back. This seems to be related to the office id - MYS. The error message says:

> An unexpected error has been encountered when fulfilling this request. This incident has been logged and will be investigated. Please try again.

**Specification**
This happens in Prod Savills account

**Comment by AshDeeming** [comment]
migrated to; PBI-5871

NB  This ticket will be updated once further updates completed on the above

**Comment by AshDeeming** [comment]
Hi @paganvarg 
Please note that the team have investigated this & following attempted to replicate this error locally they have not been able to with all requests going through fine. 

The logs show we did experience a large number of 500’s with the appointments service which have been resolved since the start of September.
