### ISSUE TITLE
Query regarding publishing the app

### ISSUE THREAD

**Issue by jcncnn** [reapit/foundations#11312]
Hello Team,

We are developers and currently new to Reapit CRM. We have developed an app in development mode (sandbox mode) and want to publish it in the marketplace. As per the documentation, it is stated that publishing the app will take 2 to 7 weeks. It is also mentioned the two categories to publish app or integration. Could you please explain what is meant by “integration” in this context? Please see the linked image below for reference.

Also is it necessary to publish the app in the marketplace to fetch customer data, or can customers install the app from the developer mode since it is an organisational environment?

![IMG_2238](https://github.com/user-attachments/assets/f0a38830-0915-494f-ab0a-c042ab05a959)

**Comment by AshDeeming** [comment]
Hi @jcncnn 
We refer to an app as an application which will launch within the CRM product
If the application is a server side data feed, this would be referred to as an integration 
NB the timeframes provided are a guideline 

In order to obtain access to a customer database, the app will need to be submitted, approved & then enabled/Installed
