### ISSUE TITLE
application support search in Marketplace 

### ISSUE THREAD

**Issue by AshDeeming** [reapit/foundations#11373]
**Background context or User story:**
users have reported an issue with using the https://marketplace.reapit.cloud/support feature

when searching for a 3rd party application, for example thirdfort, no apps appear:
![image](https://github.com/user-attachments/assets/2f296503-b8dd-4d6d-ba3a-bbe7070bac6b)

**Specification or Acceptance Criteria:**
Search for apps once any match the search criteria

**Comment by plittlewood-rpt** [comment]
This page will only return information for apps which are installed by the customer which I would suggest is by design. I've just run through this and it does seem to behave in this manner. Can you give me some more information about the expected behaviour and what users are expecting? It could just be that we need to put some explanatory text on to explain how this behaves
