### ISSUE TITLE
API returning wrong status on market appraisal lettings

### ISSUE THREAD

**Issue by asovdefixflo** [reapit/foundations#11401]
It seems that whenever a property has a Letting with status market appraisal in Reapit it comes through with the status valuation in the API instead (we've tested this in our Reapit sandbox environment). I'm attaching screenshots of the property in Reapit AgencyCloud as well as raw json response from the API and a debug screenshot of the status.
The property we created in the test environment had Id: MKT241190

We had a customer approach us regarding a property that we imported from Reapit into our system even though it should not have passed the checks we have in place. The check that should have stopped the property from being imported was the ignore status check we have which has marketAppraisal as one of the statuses that this customer wants to ignore in the property imports. 
Atm, this property had a different status so I was unable to verify that the same issue was present in live. However, if the issue we faced in the sandbox environment is the same in live then it explains why the property got imported.

![BugTicket 29778 - Reapit MarketAppraisal Property debug](https://github.com/user-attachments/assets/e5457339-7e47-4257-a013-bcdbd5e10069)
[BugTicket 29778 - Reapit MarketAppraisal Property.json](https://github.com/user-attachments/files/16676718/BugTicket.29778.-.Reapit.MarketAppraisal.Property.json)
![BugTicket 29778 - Reapit MarketAppraisal Property](https://github.com/user-attachments/assets/d78aaaea-ca76-47b1-97bf-9be1898859f4)

**Comment by plittlewood-rpt** [comment]
Hi @asovdefixflo this is by design. Valuation and Market Appraisal are used interchangeably but mean the same thing in the database. The API uses 'valuation' however you can use the GET /configuration/terminology endpoint to understand how a particular agent's system is configured. You'll see for the customer concerned in your screenshots above, `properties.useMarketAppraisal` will be set to true, which tells any using the API that the agent uses "Market Appraisal" inside their CRM. I hope this helps. Thanks

**Comment by plittlewood-rpt** [comment]
It's worth also noting that the valid status options can be found in the Swagger documentation and you'll see `marketAppraisal` isn't one of them. Thank you

**Comment by asovdefixflo** [comment]
Thanks for clarifying.

**Comment by asovdefixflo** [comment]
Closing this issue as we have a resolution.
