### ISSUE TITLE
Create infra for Appointment Planner API

### ISSUE THREAD

**Issue by willmcvay** [reapit/foundations#1222]
**Background context or User story:**

_The Appointment Planner Component has it's own API. It will aggregate available viewing slots and return to the Appointment Planner_

**Specification or Acceptance Criteria:**

- Depends on #1218 should live in the AppointmentPlanner/server folder
- Needs to be registered as an application, have it's own client id and API key
- Needs to have isWebComponent set as a boolean on the app via Postman
- Needs permissions to Read: appointments, offices, negotiators
- Should have an express app with 2 routes - a ping see #1221 and a route GET `/appointment-slots`
- Task is to scaffold a Lambda and add to the web components Serverless deployment

**Comment by tanphamhaiduong** [comment]
hi @willmcvay, cloud you help me to delete this stack and I'll try to re-deploy it again. Because I dont have permission to delete `IamRoleLambdaExecution`
```
The following resource(s) failed to delete: [IamRoleLambdaExecution].
```

![image](https://user-images.githubusercontent.com/22660833/82984425-5becde80-a01c-11ea-9d1e-d324d4fbd96d.png)
![image](https://user-images.githubusercontent.com/22660833/82984977-5d6ad680-a01d-11ea-95ed-1cb3199497e6.png)
