### ISSUE TITLE
As a ‘Developer’, I want to manage by company information and members 

### ISSUE THREAD

**Issue by HollyJoyPhillips** [reapit/foundations#1342]
**Summary:** We will soon be supporting the concept of Organisations. This means that the first person to register a company will be the ‘Admin’ and will have access to 'Profile', ‘Organisation’ and ‘Billing’, this ticket is to create the UI  for the ‘Organisation’ page

**Dependent on ticket:** https://github.com/reapit/foundations/issues/1340

**Task:** To create the UI for the ‘Organisation’
- **First Section:** Company Information 
- Fields: 
Company Name
- Sub heading: Address
Building Name
Building Number
Line 1 
Line 2
Line 3
Line 4
Postcode
Country - Dropdown TBC
Telephone
Website
Office Email - should validate it is a correct format 
VAT 
REG
- Logo – Add an ‘Upload Logo’ button 
About  - text box (chars limit TBC)
- Save Button 

- **Second Section:** Members
- Column headings: 
Name – Should Display Full Name and Job title underneath 
Email
Tel
User Account (TBC)
Status (TBC) 

Full page mock up:
![Admin View3](https://user-images.githubusercontent.com/52408607/83062839-303b1a00-a057-11ea-923b-96f11df3e505.png)

**Comment by phmngocnghia** [comment]
@HollyJoyPhillips 

- Line1 contain *, It sems to be a required field based on our app convention. Should I validate it as required (the description doesn't mention that)
- The image upload on the mock contain an image preview, should I use the old image upload component (e.g. developer submit app icon field)
- Should I used the old spacing pattern, or follow spacing in the mockup: E.g. (bellow image)
- I have made a few changes (and suggest to change) from the mockup: the spacing pattern, and the size of input, because it will make the spacing consitence when comparing to other space. What you think about it?


![image](https://user-images.githubusercontent.com/36730355/83986626-9f721180-a967-11ea-9bba-d8706c22f622.png)

**Comment by willmcvay** [comment]
@phmngocnghia Can you use a 4 col grid for all those values with the exception of "About" and "Logo"  which should be the same as current. Like we do on the submit app form,

**Comment by HollyJoyPhillips** [comment]
@phmngocnghia With regards to the validation we will come back to it later as we need to handle international addresses so this ticket is just for the UI for now.

**Comment by phmngocnghia** [comment]
> @phmngocnghia Can you use a 4 col grid for all those values with the exception of "About" and "Logo" which should be the same as current. Like we do on the submit app form,

@willmcvay Hi, I'm confuse about keep "About" and "Logo" field as the same as current. You mean it should be on 2 col layout, and 4 col layout for other fields? Would be great if you provide a simple example layout wireframe  for me. Thanks

**Comment by phmngocnghia** [comment]
@willmcvay What do you think about this? Looks better?
![image](https://user-images.githubusercontent.com/36730355/84879946-1ae56880-b0b6-11ea-9cbe-319d6b4406a1.png)
