### ISSUE TITLE
Client Portal Mobile Testing

### ISSUE THREAD

**Issue by HollyJoyPhillips** [reapit/foundations#1423]
**Summary:** Please see below the results of testing the Client Portal on a mobile using Edge/Chrome

**Browse Apps** – Scroll down to select page 2 – page loads but is still on the bottom of the page – should load page 2 at the top
Page 1
 
![image](https://user-images.githubusercontent.com/52408607/83183332-8b384400-a11f-11ea-8ba0-f3416e7e490a.png)

Click on page 2:  
![image](https://user-images.githubusercontent.com/52408607/83183346-91c6bb80-a11f-11ea-9440-0fa39a5a3718.png)

**Installed Apps** – the icons are all different sizes (same for an iPad and smaller web browser screens) 
 
![image](https://user-images.githubusercontent.com/52408607/83183367-97240600-a11f-11ea-9293-4eff5121df8a.png)

![image](https://user-images.githubusercontent.com/52408607/83183482-cb97c200-a11f-11ea-819c-c7aee1376a3c.png)

**Comment by ant066** [comment]
Hi @HollyJoyPhillips,  about this issue 
`Installed Apps – the icons are all different sizes (same for an iPad and smaller web browser screens)`
The problem is all the icons have different size on iPad, small web browser. But currently, I check on dev it have the same size.
![Screen Shot 2020-06-03 at 11 03 01 AM-min](https://user-images.githubusercontent.com/30467048/83594782-51859400-a58a-11ea-8b52-35634d6c5315.png)

**Comment by HollyJoyPhillips** [comment]
@ant066 I've just looked again on Dev in Chrome & Edge and also on my mobile and it looks correct now, thanks. I'll close the ticket.
