### ISSUE TITLE
Issue with filtering apps by App Name or Company Name 

### ISSUE THREAD

**Issue by HollyJoyPhillips** [reapit/foundations#1475]
**Summary:** It looks as though something has changed with the query we run or there is a bug when clients use the 'browse' by app name or company name in the marketplace as it is not returning any results: 
**Location:** https://dev.marketplace.reapit.cloud/client/apps

**Notes:** 
The URL should be appName=GEO 
But it's showing as: https://dev.marketplace.reapit.cloud/client/apps?search=geo&searchBy=appName&page=1

It might not be related but thought it worth flagging.

**To replicate:** Log in to Client Portal > Browse > search by company name or app name
![image](https://user-images.githubusercontent.com/52408607/83406557-d0ea5a80-a406-11ea-8501-c01b1fc11afb.png)

![image](https://user-images.githubusercontent.com/52408607/83406602-ecedfc00-a406-11ea-85ea-75f6bb627cd1.png)

**Comment by vuhuucuong** [comment]
hi @HollyJoyPhillips the navigation issue has been fixed in this PR https://github.com/reapit/foundations/pull/1484
About the URL when searching, I think it's the expected behavior to handle search with different criteria, the URL may different from the query.
If it's `appName=geo`, then it shows no result, but if it's `search=geo&searchBy=appName`, then it shows the result correctly
