### ISSUE TITLE
[Submit App] Should not show message error when inputting from 991 to 999 characters into "Description" field

### ISSUE THREAD

**Issue by tanphamhaiduong** [reapit/foundations#1518]
**Describe the bug**
Show message error when inputting from 991 to 999 characters into "Description" field

**To Reproduce**
1. Login with Developer role
2. Go to "Submit App" page
3. Input more than 990 characters into ""Description" field"
4. Observe "Description" field

**Expected behavior**
Should not display message error when inputting from 991 characters to 999 characters 

**Screenshots**
![image](https://user-images.githubusercontent.com/22660833/83609463-8b659300-a5a8-11ea-93eb-b012f65df93a.png)

**Comment by vuhuucuong** [comment]
Hi @HollyJoyPhillips @willmcvay , this relates to the HTML Editor that I talked to you before, because it includes HTML tags inside: https://reapitgroup.slack.com/archives/CSADPSA1Z/p1589363678005100
I've fixed the copy/paste behaviors, but it's still included with at least one `<div></div>` tag, so the count will be larger than what you see.

E.g.
If you enter `a` into description field, it's actually `<div>a</div>` and the count will be 12 instead of 1

So this is expected behavior

**Comment by willmcvay** [comment]
@vuhuucuong That's fine but the bug for me is why is that input stretching like that, looks really ugly

**Comment by vuhuucuong** [comment]
Note:
The PR will fix stretched `Description` field instead, as Will commented

**Comment by vuhuucuong** [comment]
Verified on dev
![adsa](https://user-images.githubusercontent.com/26746668/84010108-66a15f00-a99e-11ea-9d92-3459f69bd85a.png)
