### ISSUE TITLE
Separated Customer Name Details - Applicants Webhook

### ISSUE THREAD

**Issue by RichardBetteridgeMAB** [reapit/foundations#1766]
**Is your feature request related to a problem? Please describe.**
When using the applicant web hook, we want to store a customer record from 'related'.  However currently we need to make an extra call to get title-first name-last name to ensure accuracy rather than using the concatenated version ('name')  in 'related' 

**Describe the solution you'd like**
Add title, first name, last name to 'related' as separate fields in the applicant web hook payload.

**Describe alternatives you've considered**
We could make a call to the Contact API to get the name in the format we need but this would require hitting your system again for three fields you already send.

Use regex to separate the name however this could be error prone due to input from users (eg. middle names being including or a double barrelled name)

**Comment by cbryanreapit** [comment]
Appreciate the feedback @RichardBetteridgeMAB - we agree that we can make improvements here and serve the granular parts of the name here.

- We will surface `title`, `forename `and `surname` fields in the `related` collection contained within our applicant entity
- This fields will only be populated when the associated entity is an individual and not a company (denoted by the `type` field)
- This will contain the same name data as you would find the `GET /contacts` response, removing the need for that additional call
- The new fields will be returned in the response from `GET /applicants` and `GET /applicants/{id}`
- Since our webhooks share that same schema, the applicants webhooks will be updated to match up with that automatically
- This change should be applied to other entities that work similarly (governed by separate tickets)

**Comment by cbryanreapit** [comment]
@RichardBetteridgeMAB you should now find that the additional fields are being returned from both our applicant webhook and APIs. Let us know if you hit problems.

**Comment by RichardBetteridgeMAB** [comment]
Thanks for completing this work so quickly.
