### ISSUE TITLE
Generate email containing download link for Agency Cloud developer edition when subscription added

### ISSUE THREAD

**Issue by cbryanreapit** [reapit/foundations#1829]
We should generate an email to the account holder when we provide access to the Agency Cloud developer edition.

- Should contain basic textual content explaining purpose of email (@HollyJoyPhillips to provide)
- Sent to the email address that the account is for
- A download link to the installer
- We should use our URL shortener on the link.

**Comment by HollyJoyPhillips** [comment]
@cbryanreapit Email content: 

Dear DEV

You are receiving this email because you have recently subscribed to the Developer Edition of Agency Cloud.

Please click the link below to begin the installation process.

**Insert link**

If you would like further information or instructions on using Agency Cloud, please click here (TBC).

Best Regards
Reapit Ltd
