### ISSUE TITLE
Update layout of the keys on the ‘Services’ bar chart

### ISSUE THREAD

**Issue by HollyJoyPhillips** [reapit/foundations#1882]
**Summary:** We have recently introduced additional keys on the services bar chart, this ticket is to handle how they are presented. 

**Location:** https://dev.marketplace.reapit.cloud/developer/analytics/costexplorer

**Task:** To stack the services on the 'Services' bar chart
- On a web browser, to the right, max 2 on each row
- On mobile stack on one line. 

Current view:
![image](https://user-images.githubusercontent.com/52408607/86093771-6d0b8e00-baa7-11ea-884d-2a065688f36d.png)

Stacked: 
![image](https://user-images.githubusercontent.com/52408607/86093815-7c8ad700-baa7-11ea-8e37-af3bf8b3cc60.png)

**Comment by phmngocnghia** [comment]
TODO: fix/replace the bar chart component on element v2

**Comment by nphivu414** [comment]
Hi @HollyJoyPhillips 
It said that the layout of additional keys on the services bar chart should be stacked on one line on mobile but I see that there's not enough room for it because mobile screens are usually too small.
Can we just let them show in 2 rows like this?
![image](https://user-images.githubusercontent.com/22409039/88016801-6aec9a80-cb4e-11ea-8f70-ef2f3f8ea430.png)

It will look basically the same on the desktop, the only difference is that it will be aligned to the right:
![image](https://user-images.githubusercontent.com/22409039/88016823-8061c480-cb4e-11ea-8de5-37135b07526b.png)

**Comment by HollyJoyPhillips** [comment]
Hi @nphivu414, Yes that makes sense and looks good. Thanks.
