### ISSUE TITLE
UI Tweaks to GEO Diary V2

### ISSUE THREAD

**Issue by HollyJoyPhillips** [reapit/foundations#2189]
**Summary**: This ticket is just to address a small UI fix to the address tooltip and to look at the notification that gets seen on mobile: 

**Location:** https://d2hls69nl7onvi.cloudfront.net/

The address tooltip when viewing a specific appointment appointment plotted on the map needs additional spacing. (Seems ok when all appointments are plotted on the map (when first loading the page and not selecting an appointment) 

See when you load the ‘Today’ page: 
![image](https://user-images.githubusercontent.com/52408607/88554461-747a7480-d01e-11ea-8bc9-e3d0d71e3d87.png)
 
When you click on ‘Directions’ for the same appointment:  
![image](https://user-images.githubusercontent.com/52408607/88554477-7c3a1900-d01e-11ea-8983-c9b8b05e5f8e.png)

**To replicate:** Load GEO Diary and select an appointment - click on 'Directions' > click on the pin icon to see tooltip spacing

**Notification on mobile**
On mobile, the message regarding a new version and how to refresh doesn’t really apply and is not clearly visible. Ideally on mobile the message should read: A new version is available, please clear your browsing history or not display at all? 
![GEO Refresh](https://user-images.githubusercontent.com/52408607/88554984-18642000-d01f-11ea-8556-4f8bcd5c98dd.jpg)

**Comment by willmcvay** [comment]
@nphivu414 Am getting an issue where with the current rendered appointment, if I ask for direction, it renders an alert error - see screenshot. Because alerts don't show in Mobile Safari, it blocks the thread.
<img width="719" alt="Screenshot 2020-08-07 at 11 29 01" src="https://user-images.githubusercontent.com/4630495/89637161-ac48ae00-d8a1-11ea-8471-57b4b66f1938.png">
