### ISSUE TITLE
Developer's profile page show wrong information

### ISSUE THREAD

**Issue by tanphamhaiduong** [reapit/foundations#2325]
**Background context or User story:**
![image](https://user-images.githubusercontent.com/22660833/89774886-e7144580-db30-11ea-8d45-16bfa3d6b60b.png)

**Specification or Acceptance Criteria:**
- Developer profile should render the correct information to the form
- Currently the form is rendering the information for the current logged in developerId - it should render the info for the member of the developer org
- You can get the member information by using the `developers/:id/members` endpoint and use a query string with the current logged in user's username (email address), so it only returns the logged in user info.

**Comment by vuhuucuong** [comment]
Hi @willmcvay and @HollyJoyPhillips 

So now I can get full info and showing it, by fetching both `/developers` & `/developers/:id/members` endpoints and merge it together (Because `members` endpoint doesn't have **COMPANY NAME** and **TELEPHONE**). Here is the returned value of `/members` endpoint
![image](https://user-images.githubusercontent.com/26746668/89973927-d7f5da80-dc8b-11ea-8fd7-797d358b33e0.png)


But when updating should I call both endpoints to update? Can a **member** update info of a **developer**?
Or we should make **COMPANY NAME** and **TELEPHONE** fields read-only by graying it out

**Comment by willmcvay** [comment]
@phmngocnghia  Member can't update a developer, only members with an admin role however, they are separate forms. Company Name and Telephone are not part of member so should be removed. Thanks
