### ISSUE TITLE
Fix Reapit Cloud uptime tests

### ISSUE THREAD

**Issue by willmcvay** [reapit/foundations#2459]
**Background context or User story:**

_See Slack Sentry channel - uptime tests are failing_

**Comment by vuhuucuong** [comment]
Hi @willmcvay , so the tests are failing in admin-portal because when we go to prod admin-portal https://developer-admin.reapit.cloud/login it's immediately redirected to reapit connect (It's fixed in dev https://dev.developer-admin.reapit.cloud/login but we can't release it yet).
So can we park it and I'll temporarily disable the tests. After we go live, we can re-enable the tests and fix any issue

**Comment by vuhuucuong** [comment]
The problem should go away after we finish migrating to the new production infra. Keep monitoring this ticket and fix any rising problem after that
