### ISSUE TITLE
Clean up sentry error

### ISSUE THREAD

**Issue by tanphamhaiduong** [reapit/foundations#2553]
**Background context or User story:**
- Clean up sentry alert after release prod
**Specification or Acceptance Criteria:**
- Clean up sentry alert after release prod
**Suggested solution:**
- Clean up sentry alert after release prod
- Fix bug cause alert

**Comment by vuhuucuong** [comment]
So in the PR, I fixed all the errors like this. But we need to release prod for it to take effect because our Sentry is connected to prod environment :) 
![92223479-b5419500-eeca-11ea-9948-6c9c5af1c6ea](https://user-images.githubusercontent.com/26746668/92453028-f5658800-f1e8-11ea-95a6-622043034071.png)
