### ISSUE TITLE
The docs wrapper should provide a better experience for non React users

### ISSUE THREAD

**Issue by willmcvay** [reapit/foundations#2613]
**Background**

_Elements UI library is being refactored to ensure better DX, UX and a more lightweight, flexible library with a more consistent API_

**Task**

- See spec here: https://github.com/reapit/foundations/blob/master/packages/elements-next/src/index.mdx
- As per spec, we need to give an equally good experience for our non-React users - this means showing a rendered HTML output so markup-only users can just apply elements classes from the React Components.
- Currently we are using a DocsWrapper component to do this. In the example below, we can't see the rendered Modal output in the HTML section so the modal classes are not usable. 
- The DocsWrapper component should render all HTML output for all components in an attractive and usable way
- If we can find a plugin or similar for Docz to do this, please use!

**Comment by nphivu414** [comment]
Hi @willmcvay ,
About the problem when we can't see the rendered Modal output in the HTML section, it's not because of our DocsWrapper, it was caused by our current Modal rendered outside DocsWrapper scope (it was rendered outside our root actually).
I can fix the problem but I just don't know if we should re-write it completely like what Bulma did (no javascript needed, only css) instead.
That way, we can see all HTML output in DocsWrapper and can also support our non-react user better.
What are your thoughts on it?

**Comment by willmcvay** [comment]
@nphivu414 Cool, yes, I agree. There is a ticket in the backlog to replace the modal with a simple version. The current one is overkill for what we need - it's just a simple hide and show and yes, will be much better for non React Users. They should just be able to toggle an `isActive` class and it "just works". No need to overthink it!

On the docs wrapper, I guess we will have to do it on a component by component basis but can you use this to experiment a bit and see if you can make any general improvements to the DocsWrapper. If not, just put this ticket back in the backlog and we can review the whole styleguide when all the components are migrated.
