### ISSUE TITLE
[ Agency Cloud ]  Have a customer install another app from my primary app?

### ISSUE THREAD

**Issue by buonzz** [reapit/foundations#2779]
**Summary**
Hello Guys :)

I have a couple of app:

* Movinghub - is the primary app, this uses Connect Session and is what primarily where user is interacting with
* Movinghub Sidekick - is the secondary app, this uses Client Credentials authentication flow. It's purpose is augment the functionality of the primary app.

Question:

When the customer have installed my primary app (Movinghub), it runs a first-time installation wizard. In the steps of this wizard I wanted to encourage them to install the other app (Movinghub Sidekick). Something like

```
For more enhanced features and easier integration, We highly recommend to also install Movinghub Sidekick.
Click Here to Install
```
What URI should I point the `Click Here to Install`? so that it will go to the page where the user can install it?

**Detail and or supporting links and screenshots**
https://drive.google.com/file/d/1q6wCx5BKHA-TsSKMLDLeHFmuP6Pj8vgS/view?usp=sharing

**Comment by willmcvay** [comment]
@buonzz The url you need is `https://marketplace.reapit.cloud/apps/:appId` where app id is the id in the url of your app detail page in the developer portal ie `https://developers.reapit.cloud/apps/:appId`. This however will not work inside the desktop CRM. When inside the CRM you need to use the agencycloud link schema eg `agencycloud://process/webpage?url=https://marketplace.reapit.cloud/apps/:appId` so that Agency Cloud can load the page in a new Chrome process. 

To check if you are in desktop mode either use the `connectIsDesktop` property in `@reapit/connect-session` or you can check the existence of `window.__REAPIT_MARKETPLACE_GLOBALS__` a property we set in Agency Cloud to pass values to apps. See: https://foundations-documentation.reapit.cloud/api/desktop-api and https://foundations-documentation.reapit.cloud/app-development/connect-session for more.

**Comment by willmcvay** [comment]
Can I close this off @buonzz ?

**Comment by buonzz** [comment]
yep, thanks
