### ISSUE TITLE
AML Checklist - Saving Primary ID 

### ISSUE THREAD

**Issue by AshDeeming** [reapit/foundations#2952]
**Describe the bug**
Once searched for a contact, can update the 'Personal Details' no problem however once entered the 'Primary ID' details & upload the supporting document, the below error is thrown;

![image](https://user-images.githubusercontent.com/61687775/98359883-c7ea5e80-2020-11eb-8fa5-0829a223a45b.png)

Sentry Alert:
https://sentry.io/organizations/reapit-ltd/issues/2011523913/?project=1885615&referrer=slack

**To Reproduce**
Steps to reproduce the behaviour eg:
1. Go to 'https://aml-app.prod.paas.reapit.cloud/checklist-detail/MKT20000130'
2. Click on 'Primary ID'
3. Enter details & upload a file to 'Upload file'
4. Save or Next to See error

**Expected behaviour**
Save the details & uploaded file

**Screenshots**

![image](https://user-images.githubusercontent.com/61687775/98360052-17308f00-2021-11eb-801a-165144cc9fd2.png)

 - Browser [Chrome]
 - Version [86.0.4240.183 (Official Build) (32-bit)]

**Comment by willmcvay** [comment]
@AshDeeming This was because you were logged in as a developer and so you don't have a negotiatorId in your idToken. This is actually correct behaviour so rather than fixing the bug, have added a notification to stop the error from throwing.

<img width="460" alt="Screenshot 2020-11-09 at 14 57 19" src="https://user-images.githubusercontent.com/4630495/98557759-81a13380-229c-11eb-8503-b4ca77944ca7.png">
