### ISSUE TITLE
Support relationships between development plots

### ISSUE THREAD

**Issue by Nialld** [reapit/foundations#3756]
Currently in desktop RPS you can create properties and build relationships between master and sub plots in new home developments. There is no ability to view these relationships between properties via the API. I would like to suggest that this is supported via API so that relationships between multi lot developments are discoverable.

**Comment by david-silverink** [comment]
Would agree, this is crucial to delivering the correct content via the API.

**Comment by awogan06** [comment]
On our website our New Homes Developers want us to advertise the Development and then the different types of units for sale within the development.  The Master record gives an overview of the Development and appears on our website either on it own (prior to a launch) or with the type of units for sale within the development listed with the development details (see sample below)    The individuals subplots also appear in the search results within an area, price etc on the site and from these units we need to link users on the website back to the master development record for more details on the Development.   To allow us do this we need to be able to view the relationship between the subplots and Master records via the API, as we could in our SOAP API. 

 
Sample
https://www.sherryfitz.ie/buy/house/kildare/kilcock/ledwill-park-kilcock-co-kildare-817060

**Comment by rajeshwl** [comment]
One of our mutual client has New Homes Developments to be advertised separately using the master - sub plot mapping.  We are trying to implement the New Homes development logic with the Master/ sub plot mapping. However, we could not find a way to achieve this with current API. This was possible in the older version. It would be greatly appreciated if you could work this on priority and update us. 

--Starberry

**Comment by cbryanreapit** [comment]
After review, we will look to implement the following behaviour:

**Specification**
- Add query string filter to `GET /properties` to search for sub plots based on one or more master development ids
- For example, `GET /properties/?masterId=RPT123456` will return the sub plots belonging to property `RPT123456`
- Since this is an extension of the existing properties endpoint, this filter will work in conjunction with all existing `GET /properties` functionality
- We will add a `subPlots` link to the GET property payload links collection for master property records to indicate that the property is a master record and to serve as a fast means of navigating to the subplots
- We will add a `master` link to the GET property payload links collection for subplots to indicate that that the property is a subplot and to serve as a fast means of navigating to the master property record
