### ISSUE TITLE
Client Arrears API

### ISSUE THREAD

**Issue by asifuran2019** [reapit/foundations#3769]
**Describe the solution you'd like**
An API to get the list of arrears a tenant has towards his landlord.

**Comment by cbryanreapit** [comment]
Hi there, can you please update your ticket with the information we request in our template below: Thanks.

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

**Describe the solution you'd like**
A clear and concise description of what you want to happen.

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered.

**Additional context**
Add any other context or screenshots about the feature request here.

**Comment by cbryanreapit** [comment]
Closing ticket due to lack of response, please provide information required if this is still needed. Thanks.
