### ISSUE TITLE
Add retry logic to POST enquiries endpoint

### ISSUE THREAD

**Issue by plittlewood-rpt** [reapit/foundations#3993]
**Background**
There are a number of "duplicate key" errors appearing in the application logs for the `POST /enquiries` endpoint. This is likely due to the fast paced nature of writes to this service and the fact we also have other internal tools writing to the same data store which can result in conflicts.

(See Foundations logs for 20/04/2021 08:00 to 20/04/2021 09:00) for example error data

**Specification**
- We should look at adding retry logic to this endpoint to reduce the risk of these errors occurring
- 3 retries should be sufficient
- Continue to return 500 exception if the request hits the same problem 3 times
- Catch as specific exception as possible from DbContext to govern retry behaviour

**Comment by plittlewood-rpt** [comment]
Issue is still occurring

**Comment by plittlewood-rpt** [comment]
PR 3919 opened to enhance retry mechanism

**Comment by HollyJoyPhillips** [comment]
The issue seems to be still occurring "ReapIT response: {'statusCode': 500, 'dateTime': '2021-05-06T08:39:50.2484948Z', 'description': 'An unexpected error has been encountered when fulfilling this request. This incident has been logged and will be investigated. Please try again.'}"

Reported by Yomdel for 'Julian Waddon'

**Comment by plittlewood-rpt** [comment]
PR 3973 opened to improve the retry handling further. Unfortunately for this entity the key generation is different to other entities
