### ISSUE TITLE
Request for BER semi structured property fields

### ISSUE THREAD

**Issue by david-silverink** [reapit/foundations#4025]
Please find below extra fields requests for Sherry FitzGerald.

1 BER fields

This was the initial request on Github https://github.com/reapit/foundations/issues/3851 I believe this is now available but we need to know the exact field names to use in the query string.

![image](https://user-images.githubusercontent.com/80890331/115705334-50a54e80-a364-11eb-8619-100afb98190a.png)

**Comment by cbryanreapit** [comment]
Hi @david-silverink - issue 2,3,4 won't be covered off by the new 'extras field' mechanism. We'll review and prioritise those issues rather than this one as per our development processes outlined in our [developer portal documentation](https://developers.reapit.cloud/api-docs). 

I've tightened the scope of this ticket to be for BER related fields, and logged a new ticket on your behalf to surface the PSRA license number [here](https://github.com/reapit/foundations/issues/4027)

**Duplicates:**
2. Linking between plots: https://github.com/reapit/foundations/issues/3756
3. Auctions: https://github.com/reapit/foundations/issues/3169
4. Open houses: https://github.com/reapit/foundations/issues/3743

**Responses to the questions you asked:**
5. Custom appointment types are supported
6. This is a textual change in the agency cloud UI - the API will present this as `offersInRegion`

**Comment by david-silverink** [comment]
Much obliged - apologies for the duplicates

**Comment by plittlewood-rpt** [comment]
Hi @david-silverink 

I have sent you an email directly with the information you need to get access to the data requested.

Thanks
Pete
