### ISSUE TITLE
Reinstate archive support to platform services

### ISSUE THREAD

**Issue by cbryanreapit** [reapit/foundations#4176]
**Background context**

This functionality is was under review - we are now happy for it to be turned back on for the number of platform services that support it currently.

**Specification**
- Reinstate the archive support for all services that previously provided it
- Review previous PRs to assess the change required to turn this back on
- appointments, tenancies, applicants, vendors, properties, contacts, companies

**Comment by Mike-PygottandCrone** [comment]
As an estate agent It's useful for us to be able to re-use archived files when appropriate, to reduce "clutter". We create applicant files through the API as well as manually in RPS. A typical scenario might be:

1. A person makes an enquiry about a particular property, perhaps over the phone
2. Member of staff creates them an applicant file
3. For whatever reason the enquiry does not proceed into anything, and the person "goes cold" on us - so we archive the file
4. A few months later that person then emails in via Rightmove about another property
5. Before creating them a fresh applicant file, we would GET /applicants using the email address and fromArchive set to true, to see if they already had a file in the archive
6. If an archived file could be surfaced, we would then update that file with the details of the new enquiry.
7. Member of staff would be notified to say that previous applicant had made a new enquiry etc, and take it forward.

Being able to automatically recover a file from the archive would be useful, so that when the member of staff searches for the file in RPS it would automatically show in the search results rather than them having to search in the archive.
