### ISSUE TITLE
Write specification for GraphQL Service versioning

### ISSUE THREAD

**Issue by willmcvay** [reapit/foundations#420]
- Should be versioned against a stable API version
- Should generated definitions from platform API at this API version date
- Should support multiple API versions v1, v2 etc that can be patched independently
- Should have a mechanism to deprecate versions when they stop being used
- Task is to create a spec for this behaviour, agree with team and implement

**Comment by tanphamhaiduong** [comment]
After I discuss with the team about the solution. There are 3 solutions for us to approach API versioning for the GraphQL Server:
## The solutions to maintain versioning in the GraphQL server
### We'll versioning by add suffix to query or mutation like `getContactsV1` or `getContactsV2` and also add description API version to the query description
We'll add a suffix to the queries and mutations
The Old One `getContactsV1`, `getIdentityChecksV1`, `getNegotiatorsV1`  
The New One `getContactsV1`, `getContactsV2`, `getIdentityChecksV1`, `getIdentityChecksV2`  
* Pros:
  * We only maintain one endpoint `/graphql` for entire backend
  * If there is any change in the services we only add new queries and mutations for the changes, no need to maintain new schema.  
  For example, there are 3 services: Contact, IdentityCheck, Negotiator. So only Contact service change schema for the only Contact and add new queries and mutations for it  
  The Old One `getContactsV1`, `getIdentityChecksV1`, `getNegotiatorsV1`  
  The New One `getContactsV1`, `getContactsV2`, `getIdentityChecksV1`, `getIdentityChecksV2`  
  So the web apps can use also the old version or the new version which they prefer, but we'll give the recommend the users to use the new one instead of old one and support the back compatible
* Cons:
  * The `V1` or `V2` suffix cannot describe what versioning on the API by date but we can use description to show that
  * We have to add suffix for the Types like `ContactModelV1` and `ContactModelV2`
### We'll versioning by routes
We'll add 2 routes for the GraphQL server `/v1/graphql` and `/v2/graphql`  
* Props:
  * The queries and mutations are clearer than the solution 1
  * We don't need to add suffix for the Types like `ContactModelV1` and `ContactModelV2`
* Cons:
  * We have to maintain 1 BE, and also 2 routes
  * If there is any change on services we have to add the new schema
  For example, there are 3 services: Contact, IdentityCheck, Negotiator. So only Contact service change schema for the only Contact and add new queries and mutations for it  
  For version 1 `/v1/graphql`: `getContacts`, `getIdentityChecks`, `getNegotiators`  
  For version 2 `/v2/graphql`: `getContacts`(The New Schema), `getIdentityChecks`(The Old One), `getIdentityChecks`(The Old One)  
  We have to add new `schema.graphql` file  
  * For the user they have to change endpoint if they do migration, but for example, if they want to use `getContacts` in the V2 endpoint and want to use `getIdentityChecks` on the V1 so they have to create new Apollo Client and add new Providers, but It'll not make sense for GraphQL when using only one endpoint
### Maintain 2 BE by branch
* Props:
  * The queries and mutations are clearer than the solution 1
  * We don't need to add suffix for the Types like `ContactModelV1` and `ContactModelV2`
* Cons:
  * We have to maintain 2 BE
  * If there is any change on services we have to add the new schema and new BE  
  For example, there are 3 services: Contact, IdentityCheck, Negotiator. So only Contact service change schema for the only Contact and add new queries and mutations for it and it also runs on 2 BE and endpoint  
  For version 1 `/v1/graphql`: `getContacts`, `getIdentityChecks`, `getNegotiators`  
  For version 2 `/v2/graphql`: `getContacts`(The New Schema), `getIdentityChecks`(The Old One), `getIdentityChecks`(The Old One)  
  * For the user they have to change endpoint if they do migration, but for example, if they want to use `getContacts` in the V2 endpoint and want to use `getIdentityChecks` on the V1 so they have to create new Apollo Client and add new Providers, but It'll not make sense for GraphQL when using only one endpoint
## Other things need to be applied
* Schema change validation on the CI
https://www.apollographql.com/docs/graph-manager/schema-validation/#set-up-schema-validation
* We need to change workflow for the cronjob ts-definition. So right now the cronjob will run automatically and see the diff. If there is diff on the code it'll commit the new one and publish. So in this case we cannot aware what're happening on the changes. So the team proposes changes workflow for it. Cron will run automatically everyday and see the diff as usual, but if there are changes, it should create PR and need us to review after merged and publish. In this case, we'll aware of what has been changed and create a ticket to do that
* For the TS definition it'll be copied by hand to GraphQL server and maintain like
  * `/v1/platform-schema.ts` and `/v2/marketplace-api-schema.ts`
  * For the new schema, there are 2 ways to maintain it.
    1. We only commit changes to folder `/v2/platform-schema.ts` and `/v2/marketplace-api-schema.ts` to avoid duplication code
    2. We commit all things to folder `/v2/platform-schema.ts` and `/v2/marketplace-api-schema.ts`
