### ISSUE TITLE
Design approach for ongoing management of Zapier integration

### ISSUE THREAD

**Issue by cbryanreapit** [reapit/foundations#4311]
**Background context**
We need to ensure the processes are put into place to allow us to effectively develop, test and support the Zapier integration.

**Specification**
* Understand versioning and best practise behind this
* Understand if/how we can test a new version of the integration before making it public
* Understand how we'll receive and action development requests
* Understand if there is a requirement for dev/prod instances and if Zapier supports this notion

**Comment by RWilcox-Reapit** [comment]
Findings:

**Understand versioning and best practise behind this**
Have multiple versions to release too. A testing version which is private (invite only) and a production version open to integrators. (This will be parameterized and set in the release pipelines)

**Understand if/how we can test a new version of the integration before making it public**
The approach above gives us the ability to create zaps on the private testing version before releasing to production

**Understand how we'll receive and action development requests**
We would need to parameterize authentication.ts and environment.ts to point to development url and app for the dev versioning releases.
The alternative is to allow dev zaps to run against a PROD TST customer which may be simpler?

**Understand if there is a requirement for dev/prod instances and if Zapier supports this notion**
From the various forums read it has been reported to used a staging and production versioning approach listed above

I've created the build pipeline as part of this which runs tests and builds the artifact for the release pipeline. 
The release pipeline is a bit trickier due to authentication and is not in scope of this ticket so it has been left.
