### ISSUE TITLE
Investigate and resolve the marketplace migration issue

### ISSUE THREAD

**Issue by RWilcox-Reapit** [reapit/foundations#4480]
**Describe the bug**
Currently when a migration is added to Marketplace there are TempId's and Customer FK's added as part of the migration.
This looks to be overhang from a previous broken migration. 

**To Reproduce**
Open marketplace and add a migration with no changes

**Expected behaviour**
The migration should be empty when there are no changes on your branch

**To do**
Investigate and resolve the issue which is causing TempId's and FK's to be generated on each migration

**Comment by m-abdalla** [comment]
This issue seems to be happing due to entity framework migration being out of sync.

After looking at various solutions I found 2 options that are available and can be used to resolve this issue.

The first is clearing the migration history; this would mean removing the migration history table and all the migration files and then creating a new initial migration (this can result in an error as the tables already exist, so so comment out all the code inside up(), then database-update and uncomment to inside the first row is created in the entity framework history table). However, this would mean losing the migrations added previously.

The second option is to ignore the out-of-sync, similar to what we have been doing recently of manually removing the incorrect section of the migration. To ignore the property completely [NotMapped] can be added to the property, which would mean it is always ignored.
