### ISSUE TITLE
Speed issue on Cost Explorer

### ISSUE THREAD

**Issue by HollyJoyPhillips** [reapit/foundations#4554]
**Summary**: When loading the cost explorer for willmcvay@me.com, the services and cost and usage sections are taking quite a few seconds to load

See video: https://www.dropbox.com/s/cjo0qeim5h5ltd5/Loading.mp4?dl=0

**Comment by willmcvay** [comment]
<img width="516" alt="Screenshot 2021-07-13 at 10 02 58" src="https://user-images.githubusercontent.com/4630495/125424298-864c851a-7d3a-420b-a96a-5809764b174e.png">

@HollyJoyPhillips So I had look at this and I am 90% certain it's because we are pulling in like 15months of transactions. Suggest you scope out how many months you want to display for each query and paginated the request on date.
