### ISSUE TITLE
Multipe authentication flows

### ISSUE THREAD

**Issue by jmsfwk** [reapit/foundations#4807]
Is it possible to use both the client credentials and authorization code flows with one application?

**Comment by willmcvay** [comment]
@jmsfwk It is, yes but you will need to register two "apps" in the dev portal because a single client id can only be tied to a single OAuth flow. That's just a restriction of the technology rather than a product decision at our end.

There are a few developers that list both server and client side applications in the marketplace to handle this use case where they need both a client side portal and a machine-to-machine access to our APIs.

**Comment by willmcvay** [comment]
@jmsfwk Closing this as I am assuming this answers the question. Feel free to re-open if you need any more info.
