### ISSUE TITLE
Ensure textual analytics computed columns are casted to an appropriate length

### ISSUE THREAD

**Issue by cbryanreapit** [reapit/foundations#4891]
**Background context**
This doesn't happen automatically, so we should sweep and cast fields.

**Comment by plittlewood-rpt** [comment]
@cbryanreapit I have approached this slightly differently as we are going to run into truncation problems trying to enforce column length limits (fine for AC data but becomes problematic if we start pulling in data from other sources). The SF documentation confirms there's no performance benefit to doing this, therefore rather than alter the schema, I've removed the column length altogether from the documentation which looks a lot tidier. 

I'll complete this item based on the above, but possibly one to discuss if you disagree
