### ISSUE TITLE
Foundations 401 errors on subsequent calls

### ISSUE THREAD

**Issue by sdasnet** [reapit/foundations#4910]
Were having an issue sending a set of requests to the Foundations API.
After 30 or so requests on the same endpoint, one after the other, the response time on an endpoint gradually increases up to around two minutes.
About 10 or so calls later, we receive 401 responses for further requests on the same endpoint.
We are then able to query another endpoint, eventually, until the issue repeats.
This issue didn't occur previously, before Foundations was live. Can you clarify if this is an issue at your end?
Many thanks.

**Comment by plittlewood-rpt** [comment]
Hi @sdasnet 

Thanks for reaching out - please can you provide some steps to replicate this behaviour? It would be useful if you could provide some response body/response header examples of when you get 401s as that would suggest your token has expired.

Can you also let me know the timeframe in when this occurred so I can have a look in logs at our end.

Thanks

**Comment by cbryanreapit** [comment]
We are unable to progress this without further information

**Comment by jpswade** [comment]
This seems to be related to this existing issue: https://github.com/reapit/foundations/issues/3295

**Comment by smurfoid** [comment]
Please see below from Stephen Davey, Agent Software (Spectre) regarding this ticket:
---
Thu 23/09/2021 15:33
Hi Steve Murphy, 

Our issue is that after making around 30 responses to the same endpoint, the response time gradually increases up to about two minute in between request and response, sometimes increasing to 5 minutes.
After making around 10 more calls we start to receive 401s. This issue persists until we switch to look at a different endpoint, but then the process repeats.
In between looking at endpoints, the 401s stop. Im not acquiring a new token, however the slow request/response time remains and the 401s come back after a lower amount of requests.
So I dont think the 401s happen due to time based token expiry.
Im currently waiting for the request to complete and then almost immediately hitting the next request as soon as possible after weve finished processing.
Since I am doing this, it may be possible that the activity is being registered as a DDOS on the foundations end, however, this previously was ok before foundations was live.
However we only do the one request at a time, we dont hit the 20 requests per second limit as outlined in the rate limiting rules. As a result, theres about 2 or 3 seconds between requests.
So at max, 1 request in a second.

Thanks,
Stephen Davey, Agent Software (Spectre)
stephen@agentsoftware.net

**Comment by plittlewood-rpt** [comment]
Hi @smurfoid 

Are you able to provide any details about any specific requests (date/time, request id from the response headers etc)? Which endpoints are you seeing this on and for which customers? If you can provide some more specific details I can start looking in logs to try and identify what's going on here.

Thanks
Pete

**Comment by cbryanreapit** [comment]
Reopened due to new activity. However as @plittlewood-rpt says, we need detailed replication steps to be able to take this further

**Comment by sdasnet** [comment]
Hi again, 

Turns out the speed issues between were all on my part: apologies. I am now able to query from the api reliably.

I just need a clarification on the 401s: I've been able to get the error out from the 401s, which is:
ApiException: { "statusCode": 401, "dateTime": "2021-09-28T16:30:09Z", "description": "The request could not be completed due to a missing or invalid authorization token. Please generate a new access token and try again." }

As it turns out. I was refreshing the token on the next endpoint, so I was able to continue. I wasn't aware I was doing this: apologies again. I notice the 401 error above happens after querying the api for about 70 minutes, can you please clarify if there is an expiry time on the token + what policy should I adopt in refreshing the token? (every x calls, every x minutes)

Many thanks.

**Comment by Mike-PygottandCrone** [comment]
The access token expires after 60 minutes, this is all detailed in the Documentation here https://foundations-documentation.reapit.cloud/api/api-documentation#using-access-tokens

I store the token locally and then I have a standalone routine that requests a new one every 55 minutes, and updates locally. I've not experienced any issues doing it that way.
