### ISSUE TITLE
Create appointments webhook fires twice when two negs are assigned to an appointment

### ISSUE THREAD

**Issue by willmcvay** [reapit/foundations#4932]
**Background context**

_It was reported that when creating an Appointment where two negs are assigned to the appointment, two identical webhooks are fired, save for the event id differs. They have the same time stamp and etag and have verified they are identical in all other fields. Have verified also that there is not a duplicate webhooks listening on the same event_ 

**Specification**

- See live chat #z-bassem-murad-625 for examples
- User says that it can be replicated but the issue is intermittent - they re-tried three times and were able to replicate after these repeats. Looks like an edge case, albeit a replicable one

**Comment by bisoh** [comment]
There is similar scenario where when we cancel an appointment, we get a cancelled then a modified webhook. Not sure if its the same bug or a different one. I have attached the screenshot of the logs and the payload.

![image](https://user-images.githubusercontent.com/3708220/132348645-0a99ef8f-2bd4-4d9f-86aa-a21692a9a185.png)
[webhook-logs-payload2-1.json.txt](https://github.com/reapit/foundations/files/7121654/webhook-logs-payload2-1.json.txt)
[webhook-logs-payload2-2.json.txt](https://github.com/reapit/foundations/files/7121656/webhook-logs-payload2-2.json.txt)

**Comment by plittlewood-rpt** [comment]
Hi @bisoh the behaviour you describe in your latest comment is as expected. When an appointment is modified, an appointments.modified notification will get fired irrespective of any of the more granular appointment.* topics you are subscribed to. The benefit to having the more granular topics is so that you can only receive those type of events, if that's all you're interested in.

Regarding the issue that this issue relates to, we will look into this as soon as we can

**Comment by plittlewood-rpt** [comment]
I have been able to replicate this issue which is ultimately caused by how the data is managed in Agency Cloud and then streamed out to the platform. Currently considering possible solutions to the issue

**Comment by maxcivino** [comment]
Hi, 
we verified that the issue is still happening on Sandbox. When an appointment is created with two negotiators, Reapit fire two created events with the same payload.
Could you please let use will be able to test the fix in the Sandbox.

Thanks

![image (4)](https://user-images.githubusercontent.com/91464141/134891022-17fa1e1d-bff0-4028-b764-9b14d0494f1e.png)
![image (3)](https://user-images.githubusercontent.com/91464141/134891029-1a79a7ef-a157-4d7e-a01e-f45efb501796.png)

**Comment by cbryanreapit** [comment]
To be investigated further in next sprint - perhaps 2 different issues in play here.

**Comment by maxcivino** [comment]
Hi, 
the issue raised on the 6th of October has been resolved. There were two active Webhooks on the same env (SANDBOX) that were causing the duplication of the events.

It is still happening the main issue raised one month ago.

So, this bug is still one.

Let me know if you have any question.

Max

**Comment by plittlewood-rpt** [comment]
@maxcivino  Thanks I was confused by that one I must admit and that was going to be the first thing to check!

**Comment by plittlewood-rpt** [comment]
Hi @maxcivino  this is interesting - I can't replicate the original issue at all anymore since the update went out yesterday. There's a small possibility that the old containers were still running when you ran these tests. Would you be able to run a couple more for me at some point and report back, please? I've just added ten new appointments all with two negotiators assigned and not had a single duplicate hook through

**Comment by plittlewood-rpt** [comment]
Hi @maxcivino I'm having no success replicating the problem at all now since the update went out. Can you just confirm the exact steps you are taking in Agency Cloud to get the result you are seeing? I'm adding a brand new appointment from the diary screen and assigned 2 negotiators to it and then clicking Save. Every time I do this I only get a single webhook sent so I'm starting to think you might be doing something slightly different.

**Comment by maxcivino** [comment]
Hi @plittlewood-rpt ,
thanks for your reply.

First if all I would like to remind you the version I'm running. RPS 12.132.2.

The steps are quite simple and you can verify in the log data I attached in my previous messages:
- login to Reapit Property System - Developer Edition (RPS 12.132.2, user: max.civino@savills.com)
- select property MKT210412 (49 - 49 Fynamore Gardens, SN11 0UA)
- select key
- select New Appointment
- select Accompanied Mrs Adele DesignReact (Oxford OXF)
- select Negotiators Mr Martin King (Oxford OXF, first in the list)
- save appointment

Let me know if you would like more details.

Thanks

**Comment by plittlewood-rpt** [comment]
Hi @maxcivino - I've finally managed to replicate this today and _think_ I might have got to the bottom of it. I need to do some more testing tomorrow as the problem only seems to surface when there's a lot of traffic flowing through the system and I think the reason I've not managed to replicate it before now is because of the time of day I've been testing it. I'll keep you posted as I go - apologies that this one is dragging on, it's ultimately caused by the way Agency Cloud runs some updates out to the database which can cause things to get processed in the wrong order when it hits the webhooks pipeline

**Comment by maxcivino** [comment]
Thanks @plittlewood-rpt .

Let us know when we can test it again

**Comment by plittlewood-rpt** [comment]
Hi @maxcivino - I think this is finally under control. Please can you run your tests again and let me know the outcome?

**Comment by maxcivino** [comment]
Hi @plittlewood-rpt , I did run a test with 10 scenarios and none of them is reporting duplicated events.
It looks like the bug has been fixed.

Thanks for you help and support

**Comment by plittlewood-rpt** [comment]
Best news I’ve had all week! Thanks for confirming. If you notice anything else odd with this please just reach out
________________________________
