### ISSUE TITLE
We are receiving multiple webhooks when a record is updated.

### ISSUE THREAD

**Issue by jennyCognio** [reapit/foundations#5229]
There are two issues that may be related.

1. We are receiving multiple webhooks when a record (contact / applicant / property) is updated. Up to 15 within the space of a minute or two. 

This doesn't happen every time, but when it does they can be within seconds of each other. Far faster than a user would be clicking save. Each one triggers an API call (sometimes multiple calls if we need to get embedded data). 
We're not sure if the webhooks are being received multiple times, or if they're firing each time an individual piece of data is updated on the record rather than when the save button is clicked.
My concern is that if the webhooks are firing separately to the save button being clicked, the negotiators may not have wanted that data to be published / it may not be complete.
Additionally, there may be cost implications that need to be discussed separately.

2. API calls are being rate limited when the rate is being determined by the volume of webhooks being received.

When a contact / applicant / property is added/updated to Reapit the webhook triggers an API call so we can update the website/database.  We've had several instance (the latest being around 12:40 11/10/21 ) where our API calls are returning the error "Request failed with status code 429".  We got hundreds of errors within the space of 5 mins or so. 

Ollie has said this may have been caused by a hosting issue, but it's happened several times and the rate limit should be set high enough to accept the API calls that are triggered by your own webhooks. Hopefully if point 1 is a bug, this will become a moot point. If point 1 isn't a bug, then this needs to be looked at.

Thanks
Jenny

**Specification**
- Investigation and test into webhook pipeline behaviour. Please read all comments before commencing any work
- Run tests when there's a lot of data going through the webhooks pipeline. This tends to be towards the start of the day

**Comment by jon64digital** [comment]
Hi,

I thought I'd add some info here, just to clear up any confusion. 

We're not sure if anything is duplicated, it's just that sometimes the same property or contact seems to be updated many times in quick succession so we're querying what the trigger for a webhook is. Where we're seeing 3 webhooks called in the space of a few seconds for one property (see log below) it seems that this can't be a negotiator in branch saving the property 3 times that quickly. We're wondering if the webhook triggers each time the user changes a field or moves from one textbox/control to another rather than waiting until they click save? We've had instances where a property is updated 20 times in the space of 20 minutes and it doesn't feel right.

Unfortunately we don't log event_ids on our end at the moment but we do have a log of dates/times/propertyIDs which I can send you separately. Here's an example of a property being updated 8 times in a row this morning. It's possible that the user is going in and out of the property and saving it multiple times but the timestamps are fairly close together.

![image](https://user-images.githubusercontent.com/2878796/142434587-63c9ba46-b04f-4269-bc27-f30ef4dd7552.png)

A better example may be this one...

![image](https://user-images.githubusercontent.com/2878796/142434873-56953d5e-3e55-4eee-a794-20578d4a1d31.png)

You can see that there were 3 webhook calls this morning at 10:54 and 30/34/41 seconds. maybe the user didn't think it had saved so hit the save button multiple times within seconds? It would be good to know if there's another explanation though as this does seem to happen a lot and it's not uncommon for us to see a stream of logs for the same property or contact. I think the biggest we've seen is over 50 updates to a property in an hour.

Many thanks.

**Comment by plittlewood-rpt** [comment]
Hi @jon64digital thanks for this information. Can I just confirm which customer this is for, and the id/type of entity that your example came from?

**Comment by jon64digital** [comment]
Hi there.

It's when somebody updates a property, it seems that either they're updating the property many times or the webhook is being called multiple times for the same update. It's possible they're just pressing the save button many times or that the webhook is called before they actually submit it?

**Comment by plittlewood-rpt** [comment]
Hi @jon64digital if you can give me the webhook ids from your screenshot (we submit them all with a guid) I can track them down and try and unpick the order of events that resulted in them being fired.

**Comment by jon64digital** [comment]
Ah, sorry, we don't log those.

All we'd like to know is what the trigger is for calling the property updated webhook. That's probably easier than trying to hunt down what's happened with specific calls.

**Comment by plittlewood-rpt** [comment]
The properties.modified webhook only gets triggered by someone actually updating the property record itself. Some other topics have events which cascade (ie if a contact surname gets updated, that would cascade events for applicants.modified/landlords.modified/vendors.modified where appropriate, as we surface the contact name on those other models), but for properties it's a pretty standard 1-1 relationship so the behaviour you describe sounds slightly odd. We do have a retry mechanism in place which will retry transmission up to 6 times with an exponential backoff if we don't get a 200 response from your endpoint fast enough. A few developers have fallen foul of this in the past where they haven't built asynchronous processing, so even though they are processing the message, if it took a certain amount of time the event would end up being retried. We normally pick up on this on our monitoring platform though and I haven't seen anything that looks like one of yours, so I'd like to understand what's going on here. I'll look at logs this end to try and tie it up with your example and go from there

**Comment by jon64digital** [comment]
Thanks very much. I have a feeling that the answer is that they are simply going back in and editing the record a lot of times, or saving often because they don't want to lose their progress filling it in. The fact that this happens over the course of 20 minutes rather than 20 seconds would point to that.

**Comment by plittlewood-rpt** [comment]
I'll let you know if I find anything. Incidentally, if it's specific changes on a record you're interested in it might be worth you logging a feature request for a more granular webhook topic (you'll see there are various topics that deal with very specific changes to a record). This would allow you to cut down on any unnecessary noise. We also have a long term ticket #4289 , not yet scheduled or scoped out, for allowing developers to set their own change detection schema so you can fully control which changes you get transmitted. Feel free to comment on this ticket too as the more people asking for it the more likely it is to get more attention when we refine our backlog.

**Comment by plittlewood-rpt** [comment]
Moved back into To Review as we need to spend some time running tests on the webhooks pipeline to try and replicate this behaviour. From here we may be able to get a better idea of whats gone on. PL has some log output which confirms the behaviour that the reporting user has experienced which may help diagnosing the problem

**Comment by plittlewood-rpt** [comment]
@jon64digital is it fair to say that this issue is the same as the one describe in #6651?

**Comment by plittlewood-rpt** [comment]
Closing this ticket as it's essentially the same as #6651
