### ISSUE TITLE
Include Transactions in Data warehouse Analytics Schema

### ISSUE THREAD

**Issue by StuartLaw99** [reapit/foundations#5230]
We have Created a Share with the Analytics Schema but transactions are not included in the model. The option to create a share for the Operational Database is not available - Maybe this has the transactions in it?

**Comment by dawson** [comment]
@StuartLaw99 The Operational Database you refer to is a legacy schema that was available to a small number of enterprise customers on our old Rackspace infrastructure and has since been depreciated as part of our migration to AWS. However, your request for access to transactions within the new analytics schema has been added to our long term backlog for future consideration next year.
