### ISSUE TITLE
Error when attempting to get property images from API Explorer

### ISSUE THREAD

**Issue by kiqbal-reapit** [reapit/foundations#538]
Summary:
When attempting to get property images in the API Explorer.  The general search - `/propertyImages` seems to work okay.

Steps to reproduce:
Requested
Made a request with PropertyId - BCK150180 - in`/propertyImages/{id}`

Expected Results:
Images data

Actual Results
Error:
TypeError: 

> Origin https://marketplace.reapit.cloud is not allowed by Access-Control-Allow-Origin.

**Comment by cbryanreapit** [comment]
Hi @kamran-iqbal 

The `GET /propertyImages/{id}` method is for fetching the details a single image. It's expecting the id of the image rather than an id of the associated property.

To fetch images for a property, or list of properties, you can do` GET /propertyImages/?propertyId=XXX&propertyId=YYY`

I note two issues coming out of my investigation on this:

- https://github.com/reapit/foundations/issues/542 - documentation needs to be clearer
- https://github.com/reapit/foundations/issues/543 - interactive API explorer not surfacing 404 errors for subset of getById endpoints

**Comment by plittlewood-rpt** [comment]
@kamran-iqbal  #543 is now resolved so you'll get the correct response back now
