### ISSUE TITLE
Full List of Document Codes

### ISSUE THREAD

**Issue by MSB89** [reapit/foundations#5395]
Is it possible to get a full list of document codes, this doesn't appear to be documented anywhere. 

I.E. LET, FPO, HMR, EPC etc.

**Comment by plittlewood-rpt** [comment]
Hi @MSB89 

Thanks for your query - you should find that each document returned from `GET /documents` and `GET /documents/{id}` contains a `type` link in the `_links` collection that is a navigation to the `GET /configuration/documentTypes/{id}` endpoint. The configuration API gives you a lookup from the code to the readable value. Document types are configurable on a customer by customer basis which is why the data is presented in this manner.

Please let me know if this doesn't answer your query

Thanks

**Comment by HollyJoyPhillips** [comment]
This looks to be resolved, if still an issue, please let us know.
