### ISSUE TITLE
eTag being reused in events and incorrectly being set in old events

### ISSUE THREAD

**Issue by bisoh** [reapit/foundations#5418]
**Description**
When making changes to an appointment, the same eTag is reused or changed in old appointment. 

**Steps to reproduce the behaviour (sandbox):**
1. Create an apointment with 'Adele DesignReact' as the main negotiator and the first 'Martin King' in the Oxford office.
2. Save and get transaction log
3. Open the appointment and remove Martin.
4. Save and get transaction log
5. Add the same Martin King again.
6. save and get transaction log.

**Output from logs following steps above**
1. Log 1: appointment created with `New.Etag` _A_
2. Log 2: appointment modified. `New.Etag` is _B_ and `Old.Etag` is _B_
3. Log 3: appointment modified. `New.Etag` is _B_ and `Old.Etag` is _B_ . (along with other relevant changes)
 
**Expected behaviour**
To get an appointment.modified event in the transaction log with correct Etag created. Based on the above example, the correct etag behaviour would be

1. Log 1: appointment created with `New.Etag` _A_
2. Log 2: appointment modified. `New.Etag` is _B_ and `Old.Etag` is _A_
3. Log 3: appointment modified. `New.Etag` is **C** and `Old.Etag` is _B_ 

**Device (please complete the following information for web issues):**
 - Device: PC
 - OS: Windows10 20H2
 - RPS Developer Version 12.132.2

I have attached the 3 log files for the creation and 2 modifications. 

[logs_etag.zip](https://github.com/reapit/foundations/files/7498134/logs_etag.zip)

**Comment by maxcivino** [comment]
Hi, 
I would like to add another scenario.

Steps:

- Create an appointment in Reapit with a primary(Martin) and secondary(Adele) negotiator
- Save the appointment
- Right click on Adele's calendar appointment and select Cancel Appointment

Reapit is firing two different events (created and modified) with the same etag.

Attached the two event logs:

[reapit-webhook-logs-payload-2021-11-08T14_45_06.543+00_00.log](https://github.com/reapit/foundations/files/7498672/reapit-webhook-logs-payload-2021-11-08T14_45_06.543%2B00_00.log)

[reapit-webhook-logs-payload-2021-11-08T14_45_04.839+00_00.log](https://github.com/reapit/foundations/files/7498673/reapit-webhook-logs-payload-2021-11-08T14_45_04.839%2B00_00.log)

**Comment by plittlewood-rpt** [comment]
Hi @maxcivino - on your second scenario, can you just confirm that the created and modified events are NOT being sent at the same time (rather than created event comes after your second two steps and the modified event comes after the cancellation).

**Comment by maxcivino** [comment]
Hi @plittlewood-rpt, yes I confirm that the Creation and the Deletion haven't' been done at the same time. I hope I understood your question

**Comment by plittlewood-rpt** [comment]
Hi @maxcivino - the reason this is happening is because of the way AgencyCloud has been built. If the only change on an appointment is to add or remove an additional negotiator, the modified date on the parent appointment record doesn't actually get changed which is what our eTags are based on. Please can I ask you to raise this with our service desk initially to see if they can provide a way of this date being modified in this scenario.

**Comment by plittlewood-rpt** [comment]
Hi @maxcivino looking at your second point and the attachments you have provided, you are getting a cancelled event and a modified event through. This is expected behaviour if you have a subscription to appointments.modified AND appointments.cancelled. You will always still get the .modified event through if you are also subscribed to one of the more granular event types, like appointments.cancelled. If this is indeed an issue, please can you log this as a new item as there are two conflicting things listed on this issue, which I will now close as your initial request needs to go through the AgencyCloud channels
