### ISSUE TITLE
Add Additional Property Marketing Fields to the API

### ISSUE THREAD

**Issue by azura-mg** [reapit/foundations#5601]
**Is your feature request related to a problem? Please describe.**
On the Marketing Page under a Property there are a number of fields in here which don't appear to be visible via the API. The "Type" field under the "Sale Board" category is missing. The "URL" field under the "Internet" header also appears to be missing. 

**Describe the solution you'd like**
The Sale Board Type field and Internet URL fields would need to be added to the Property model for Webhooks and API Requests.

**Describe alternatives you've considered**
Since the fields are missing from the API there is no other way for us to obtain these.

**Additional context**
Issue #4415 was created previously to add one of these fields, but since then we've had confirmation from our customer that we need more data from the Marketing page.

**Comment by plittlewood-rpt** [comment]
We need to research or gather more information relating to your request. We have moved this issue into our ‘Not Ready’ column whilst we obtain the information required.
For more information on our processes, please click here https://foundations-documentation.reapit.cloud/

**Comment by plittlewood-rpt** [comment]
Hi @azura-mg 

The sale board status, notes, and last updated date is already available in the properties API. We felt that there wasn't enough need to include the type however, as it's a very limited set of options and 99% of the time they are either left empty or set to the same value. That said, we could expose this field for a particular customer as part of the extrasField functionality if it's a specific customer you are working for.

Unfortunately there's currently no easy way to surface the property URL due to how AgencyCloud stores the data

**Comment by plittlewood-rpt** [comment]
@azura-mg Just to update you, ticket #5953 will be prioritised soon to deal with the property URL. We can only expose this field where it has been explicitly set by users
