### ISSUE TITLE
Refactor: Refactor auth context for no redux options in scaffolding

### ISSUE THREAD

**Issue by tanphamhaiduong** [reapit/foundations#568]
Context:
Auth flow for no redux options in scaffolding quite complexity

Ouput
Refactor: auth context for no redux options in scaffolding to more simpler and add test

**Comment by willmcvay** [comment]
Tested this locally and throws an error when logging out am afraid, sorry.

<img width="942" alt="Screenshot 2020-03-19 at 10 16 45" src="https://user-images.githubusercontent.com/4630495/77057527-0072f480-69cc-11ea-9df1-66231e1b0ceb.png">

**Comment by tanphamhaiduong** [comment]
@willmcvay could you give me more detail about the step to replicate it?

**Comment by tanphamhaiduong** [comment]
@willmcvay I think there is lack of config, so that is the reason why it show error redirect_uri is not present

**Comment by willmcvay** [comment]
@tanphamhaiduong Sorry but am getting a `refresh-user-session.ts:20 Bad request, failed to refresh session, Error: Both UserPoolId and ClientId are required.` error. I think it's because the UserPoolId needs to be included in the bas config. This is fine to commit as it's just an id not a key or token.

**Comment by tanphamhaiduong** [comment]
@willmcvay you should add UserPoolId and ClientId of new app to config.json before using it.
