### ISSUE TITLE
Offer data does not contain the related[] collection immediately after being created in Agency Cloud

### ISSUE THREAD

**Issue by david-silverink** [reapit/foundations#5752]
This has been observed on occasion in late December 2021.

Sequence of events:

- A new applicant is added to Agency Cloud
- Separately, a new offer is then added to Agency Cloud for that applicant
- Offers webhook notifies our endpoint that an offer has been updated
- We immediately check the Foundations API offers endpoint and retrieve latest offers
- related[] collection missing
- On recheck (e.g. 1 minute later), related[] collection including contact is present

**Comment by plittlewood-rpt** [comment]
Hi @david-silverink - thanks for reaching out. Is this something that can be replicated fairly easily? There shouldn't be any noticeable lag here so it's something we'll need to look into

**Comment by david-silverink** [comment]
Thanks @plittlewood-rpt We'll attempt to replicate and revert, cheers.

**Comment by plittlewood-rpt** [comment]
Hi @david-silverink - this has all the hallmarks of being caused by replication lag between master and slave servers (the webhook event is generated from CRUD operations on the master server, and when you hit the API it will hit a slave. If there's a noticeable lag, you'd see the behaviour you have reported). I've opened up a thread with our internal infrastructure team as the lag isn't something I have visibility of so I can't confirm or deny, but it's an avenue we should certainly explore).

**Comment by plittlewood-rpt** [comment]
HI @david-silverink - do you have a more accurate timeframe of when this occurred? I can ask our infrastructure team to look at lag between master/slave databases

**Comment by plittlewood-rpt** [comment]
Hi @david-silverink - are you able to provide any more information as requested above? I've run through all the steps in Sandbox and cannot replicate this problem. The behaviour you are describing would suggest that the webhook you receive for offers.created is also missing the `related` collection. Do you know if that is the case?

**Comment by david-silverink** [comment]
Hi @plittlewood-rpt we've been working on a couple of post-launch issues so apologies for the delay in coming back. I will have the opportunity to investigate further next week. We are using the offers web hook only to notify that there has been an update, we make a separate connection to the offers endpoint immediately following that. Thanks

**Comment by plittlewood-rpt** [comment]
No problem thanks for letting me know. I'll move this over to next sprint

**Comment by plittlewood-rpt** [comment]
I am going to close this ticket due to lack of activity. If this happens again please come back to us with the date/time of occurrence and any supporting information that we can use to try and track this down as so far we've been unable to replicate it. I'd be particularly interested to see the content of the webhook you get (ie does that have the related contacts populated in it)
