### ISSUE TITLE
Rest API - Property not being returned when using properties endpoint

### ISSUE THREAD

**Issue by mfosberry** [reapit/foundations#5825]
**Describe the bug**
A client has raised that certain properties are not syncing into their Fixflo system.  When testing this using the properties endpoint I can see that they are not being returned

**To Reproduce**
for client LOC-GBRV
page through properties using the below endpoint
"/properties/?pageSize=100&sortBy=modified&fromArchive=false"
**Expected behaviour**
Properties BHL210011, BHL210012,BHL210151 are expected to be returned in one of the pages.

**Additional context**

**Comment by plittlewood-rpt** [comment]
hi @mfosberry - the three properties you have provided as an example are associated with office code BHL. The customer id you are calling our API with is one relating to an office group which does not contain office BHL. As a result, you won't get the record back. It looks like the Fixflo app has been installed for that particular office group rather than the whole company, so you will only see data that relates to the offices in that group.

**Comment by plittlewood-rpt** [comment]
Closing due to no further response.
