### ISSUE TITLE
The "reapit-customer" header requirement is missing from the Swagger documentation

### ISSUE THREAD

**Issue by jpswade** [reapit/foundations#586]
If you don't supply a reapit-customer header, you get the following (incorrect) error:

`The request could not be fulfilled as no reapit-customer header was provided. Please generate a new access token and try again.`

This is missing from the Swagger documentation as a required parameter.

**Comment by cbryanreapit** [comment]
Hi @jpswade 

Thanks for the feedback!

`reapit-customer` is only required for applications that make use of the Client Credentials OAuth 2.0 flow. For applications that use Authorisation Code flow ([Reapit Connect](https://foundations-documentation.reapit.cloud/api/reapit-connect#overview)) there is no requirement for this header to be provided as there is a user in context.

Our platform API documentation details both flows and rather than document the same lengthy information in two places, we provide a link to that documentation from our swagger

**Comment by jpswade** [comment]
We have chosen to use the 'Client Credentials OAuth 2.0 flow' as it appears to be the most appropriate for our use case.

To be clear, the `reapit-customer` is completely absent from the API specification documentation, yet it is reported by the API as a required field.

The Swagger documentation should match your API specification exactly.

If you have two flows, then you should be explicit about both, otherwise the API specification will be incorrect.
