### ISSUE TITLE
Need to be able to access Journal Entries relating to Works Orders

### ISSUE THREAD

**Issue by whanno-lsl** [reapit/foundations#5875]
**Is your feature request related to a problem? Please describe.**
We have a requirement to read certain journal entries for Works Orders, and also potentially create our own, but the API doesn't look to allow this currently.

**Describe the solution you'd like**
Be able to read/write works order journal entries using the journalEntries API endpoint, say using an "associatedType" of works order

**Describe alternatives you've considered**
Only to create our own separate journal store using metadata & webhooks which we would like to avoid.

**Specification**
- Project: Reapit.Services.WorksOrders
- Expose works order journal entries (which are stored in JnlMisc and NOT the Jnl table)
- These will only appear from GET /journalEntries when associatedType is set to worksOrder
- Allow journal entries with a associatedType of worksOrder to be written back to the API. These entries should be stored in JnlMisc

**Comment by plittlewood-rpt** [comment]
Hi @whanno-lsl - thanks for getting in touch. We will discuss this at our next refinement session

**Comment by HollyJoyPhillips** [comment]
We are reviewing this ticket as part of this ticket #6400. We will update this ticket once complete.

**Comment by HollyJoyPhillips** [comment]
PL, RW & HP: Associated ticket moved 'to review'. Ticket will be updated accordingly.

**Comment by roscoe2001** [comment]
Could I ask what the up to date position on this one is please? There's sort of 3 parts to the request: -
- Read all Notes for a Works Order
- Write Notes against a Works Order
- Reads all Works Order notes entered by a user in a given time frame (e.g. return me all the Works Order notes a user created today)

If there is an existing way of doing any of those 3 - please let me know (otherwise it would be good to know the position of the changes required to support them)

**Comment by plittlewood-rpt** [comment]
Hi @roscoe2001 

We are actually working on the mechanism to support this as part of #6400. Once this is completed, we should be able to move on this ticket.

Thanks
Pete
