### ISSUE TITLE
Works Order 

### ISSUE THREAD

**Issue by roscoe2001** [reapit/foundations#5936]
We have built a new screen where you can see all the Works Orders assigned to a certain member of staff (other filters are available to). At the moment to 'link' through to the WO itself you have to go Property > WO Selection Screen > Main WO Screen

We'd like the ability to call the main (single) WO Screen directly

There's no real 'slick' alternative (without going through the property screen like we are doing at the moment)

**Comment by plittlewood-rpt** [comment]
@AshDeeming I think this would be an AC behavioural change. Please can you provide initial support on this ticket. Thanks

**Comment by AshDeeming** [comment]
HI @roscoe2001 
The Works Order screen is currently available from the Property record within AgencyCloud. 
If you plan to have your screen available to users via AgencyCloud, this would require a Works Order 'Desktop Type' - allowing for the current Works order screen to be overwritten & users directed to your App once the app has been installed. 
In order to request a new Desktop Type to be added to the Foundations Platform, this will needs to be requested via a Client's CSM.

**Comment by roscoe2001** [comment]
Hi @AshDeeming - sorry to go on a bit on this one! Can I just double check we're not at cross purposes i.e. "allowing for the current Works order screen to be overwritten & users directed to your App once the app has been installed" < That's not what we're trying to do.

What we're wanting to do is call the existing Agency Cloud Works Order screen using a hyper link from a Foundations App e.g. in a similar way to how you would call the property screen using agencycloud://properties/{id} we would need agencycloud://worksorder/{id}

I've included a screen shot in the attached pdf 
[WorksOrder.pdf](https://github.com/reapit/foundations/files/7913932/WorksOrder.pdf)

Sorry if I've misunderstood you reply.

**Comment by AshDeeming** [comment]
Thank you @roscoe2001 for clarifying 

I can see you're referring to the AgencyCloud schema - Unfortunately Works Orders is not currently available & will need to be requested. Features relating to AgencyCloud, will be handled by a different department.  The request will therefore need to be sent to the Reapit Service Desk by the Reapit Customer.
