### ISSUE TITLE
Undocumented types of TypeId in Appointments

### ISSUE THREAD

**Issue by jpswade** [reapit/foundations#598]
Although the TypeId in the Appointments model is documented, it's unclear what they mean.

We're missing the documentation for the types of TypeId and what they mean.

For example, the Appointments returns appointments with various types, such as TK, MI, ME, AP.

I need some kind of index to tell me what each of these are.

Thanks.

**Comment by cbryanreapit** [comment]
Since each of our clients can configure the appointment types they choose to use, we expose this information as a RESTful endpoint. See `GET /configuration/appointmentTypes/`

Each appointment in the payload from `GET /appointments` and `GET /appointments/{id}` includes a link to it's specific type resource. 

Our interactive API explorer will give you a view of the links that each appointment presents - each representing a related resource - as below:

![image](https://user-images.githubusercontent.com/34191069/76424899-c472da80-63a0-11ea-8b31-41c2c9645a53.png)

You can choose to optionally fetch this resource with your appointment response by using our [embed functionality](https://foundations-documentation.reapit.cloud/api/api-documentation#embedding-data)
