### ISSUE TITLE
Include the ‘Release Notes’ in Foundations-Documentation (Gitbook) 

### ISSUE THREAD

**Issue by HollyJoyPhillips** [reapit/foundations#599]
**Summary:** We should be including the release notes from the Foundations Repo in the Foundations-Documentation repo so they are visible when browsing the documentation in the Developers Portal. 

**Task:** To take the release notes from the main repo and raise a PR against the foundations-documentation repo

**Name:**  Web change log 
**External link:** https://foundations-documentation.reapit.cloud/ 
**Releases logs:** https://github.com/reapit/foundations/releases

**Comment by vuhuucuong** [comment]
Hi @willmcvay  @HollyJoyPhillips 
Currently, I'm thinking about creating a `GitHub action's workflow` that listens to `release` event, and write a script for this (We need to add a [personal access token](https://help.github.com/en/github/authenticating-to-github/creating-a-personal-access-token-for-the-command-line) as a secret to this repo, because the `GITHUB_TOKEN` only works for the current repo, not other repos, maybe we use @willmcvay personal access token or someone else?).

The script's flow will be like this:
  - A release is made, wait for release:prod finished, then the title will have `released` title at the end ->  catch this event
  - Clone the `foundations-documentation` repo
  - `git checkout -b <random-branch-name>` 
  - Appending to the appropriate `.md` file
  - `git add` -> `git commit` -> `git push`
  - Finally using Github API to create a PR in `foundations-documentation`

But I need some more info:
- Where should I append the release note to? I mean which `.md` file?
- Will all the release note get append to one `.md` file, or each package has its own `.md` file? I see that we're having a lot of duplicated commit in the release note.

**Comment by HollyJoyPhillips** [comment]
Hi @vuhuucuong, I have created the associated md files for all packages, and moved to a new folder 'change-logs' (https://github.com/reapit/foundations-documentation/tree/master/change-logs) 

aml-checklist.md 
cognito-auth.md
congnito-custom-mail-lambda.md
config-manager.md
demo-site.md
elements.md
foundations-ts-definitions.md
geo-diary.md
graphql-server.md
lifetime-legal.md
marketplace.md
eact-app-scaffolder.md
smb.md
web-components .md

Let me know if you need anything else :)

**Comment by vuhuucuong** [comment]
@HollyJoyPhillips cool, thank you 👍
