### ISSUE TITLE
Contacts: "This application has not been gra (truncated...)

### ISSUE THREAD

**Issue by jpswade** [reapit/foundations#602]
```
ApiException: [403] Client error: `GET https://dev.platform.reapit.cloud/contacts/` resulted in a `403 Forbidden` response:
{
  "statusCode": 403,
  "dateTime": "2020-03-11T17:55:42.0722257Z",
  "description": "This application has not been gra (truncated...)

### ApiException (403): This application has not been granted the required scope to interact with this endpoint. If your application requires access to this resource, please use the Reapit Foundations Developer portal to request permission to access this resource
```

How?

**Comment by cbryanreapit** [comment]
I can see that when you registered your application in the marketplace, you didn't request the permission/scope required to interact with the `GET /contacts` resource (contacts.read).

Load your app in the 'Apps' section of the portal and hit 'Edit Detail'. You can then submit a revision with the required scope in place, which we'll subsequently review/approve. 

Your application needs to request the scopes that it requires in order to function which will subsequently be presented to our users at the point that they choose to install your app.

I can see that you've previously submitted a revision but let us know if you're struggling. More details on this topic available [here](https://foundations-documentation.reapit.cloud/developer-portal)
