### ISSUE TITLE
Properties are not syncing across to Fixflo (due to office code?)

### ISSUE THREAD

**Issue by vikiecseri** [reapit/foundations#6100]
**Describe the bug**

From Reapit the following properties sync across: 

AgentRole=Managed.

We have some of the properties not syncing across from Reapit to Fixflo: 

BHL210324
BVT170078
BHL210154

According to an answer given to us on a previous ticket: the issue seems to come from the office code. There are some properties that sync across with the office codes but our developer has raised this issue before here but it hasn't been resolved:
https://github.com/reapit/foundations/issues/5825

It has been raised here as well: https://reapit.atlassian.net/servicedesk/customer/portal/1/RSD-165081

On the Fixflo sandbox however, we have properties with EXT REF that start with BHL, which means that the office code shouldn't affect the sync.
 
Can you please have another look and see why those particular properties are not syncing across?

**To Reproduce**
Steps to reproduce the behaviour eg:
1. Go to Brand Vaugh Reapit account
2. Properties with 'Managed Let' status should match to the properties on Fixflo

**Expected behaviour**

All properties with status from Reapit are pulling across to Fixflo that meet the criteria:

AgentRole=Managed.

We exclude properties where the letting status =
valuation
sold
letbyotheragent
letprivately
provisional
withdrawn

**Screenshots**

<img width="1018" alt="Screenshot 2022-02-07 at 18 00 08" src="https://user-images.githubusercontent.com/97969621/152845805-fd301c10-36e7-4356-90a8-e5d5520b6f36.png">

<img width="1199" alt="Screenshot 2022-02-07 at 18 00 33" src="https://user-images.githubusercontent.com/97969621/152845845-2f0afc3e-b7cf-4e15-909d-e049ec8e683f.png">

**Device (please complete the following information for web issues):**
**Additional context**

**Comment by vikiecseri** [comment]
I have added a list of the missing properties - please see it attached here.
[Reapit & Fixflo Match.xlsx](https://github.com/reapit/foundations/files/8033947/Reapit.Fixflo.Match.xlsx)

**Comment by plittlewood-rpt** [comment]
Hi @vikiecseri - as mentioned on the previous ticket, this is happening because of the way offices have been grouped together in the LOC system - there is a group for Brand Vaughan by the look of it. I have however confirmed that all the properties you mention in your initial issue summary above are being returned when hitting the API with the reapit-customer header set correctly. If you can provide a request id where this is not working as you expected we should be able to find it and let you know what the issue is.

It's worth highlighting that if you are switching out the values provided in your reapit-customer header, you MUST get a new access token every time you change it as the token is cached along with the customer id, so changing it will make no difference until the cached entry gets purged. This is something we are currently addressing in #5864 and #6119

**Comment by plittlewood-rpt** [comment]
Hi @vikiecseri - please can you come back to me on the above. The work in the tickets mentioned above has now been completed and as such it is no longer necessary to get a new authorization token when switching between customer datasets. This may well resolve your issue if it was indeed the cause.
