### ISSUE TITLE
High volume of staff updates in negotiator endpoint for SFG

### ISSUE THREAD

**Issue by david-silverink** [reapit/foundations#6172]
We are monitoring updates to these records within the _modifiedFrom_ parameter. The amount of data being returned is high and does not seem to reflect actual updates to staff profiles. We only need to check changes to phone, email, etc. This has been highlighted before and we were advised there was a fix due. Currently in order to keep up to date with the number of changes we need to check the endpoint regularly, resulting in a large portion of the overall API usage.

**Comment by plittlewood-rpt** [comment]
Hi @david-silverink - can you let me know where this was previously raised please? It comes down to the way AgencyCloud stores some of it's session information against the negotiator record. As the session gets updated, so does the modified date and as the Platform doesn't return session information, it looks like the date is just being updated and nothing else. Its something I've actually been speaking to our desktop development team about as we are wanting to setup webhooks for negotiator updates but this behaviour is effectively blocking that work because of the frequency of updates. A possible approach for altering this has been discussed and is been reviewed in more detail but until this work is done unfortunately the negotiators API will continue to behave as it currently does

**Comment by david-silverink** [comment]
Thanks @plittlewood-rpt - this was initially raised on the support chat, maybe Oct/Nov last year. Apologies, I don't have a transcript of the conversation. What you mention above is more or less what the feedback was then too, thanks. I'll feed the info back to the client.

**Comment by plittlewood-rpt** [comment]
Closing this ticket as it got removed from the board so was overlooked in last cleanup

**Comment by david-silverink** [comment]
Thanks @plittlewood-rpt Has this problem been fixed? If so, can we reliably use the modifiedFrom parameter for actual negotiator profile updates?
