### ISSUE TITLE
Enquiries API endpoint 'forename' field character limit

### ISSUE THREAD

**Issue by adamboother** [reapit/foundations#6214]
There is a 12 character limit on the 'forename' field within your enquiries API endpoint. Can we increase this please? An enquiry was rejected due to the users double-barrel first name ('Ruxandra Cristina') being over that 12 character limit. This is the response I received:

{"errors":[{"field":"forename","message":"The value provided exceeds the maximum length of 12 characters"}],"statusCode":422,"dateTime":"2022-02-22T10:59:42.4843876Z","description":"One or more validation failures have occurred. Please refer to Errors list for details"}

To reproduce:
Post an enquiry to https://platform.reapit.cloud/enquiries with the forename set as 'Ruxandra Cristina'

**Comment by plittlewood-rpt** [comment]
Hi @adamboother - this is a limitation in AgencyCloud and would need to be increased there before we can increase it in Platform. If you are a Reapit customer, you can raise this on the Self Service Portal, otherwise if you are working on behalf of a customer, please can you ask them to raise this with their account manager or directly on the self service portal. Many thanks

**Comment by HollyJoyPhillips** [comment]
When the work has been completed via the Desktop team, we will review this.
