### ISSUE TITLE
Update default swagger selection

### ISSUE THREAD

**Issue by HollyJoyPhillips** [reapit/foundations#6426]
**Task:** 
If clientCode is set to 'SBXA' default swagger to 'AgencyCloud Australia' 
If clientCode is set to 'SBOX' default swagger to 'AgencyCloud'

**Comment by willmcvay** [comment]
@HollyJoyPhillips I take the value for the product from the idToken ie agencyCloud or agencyCloudAus and then get the swagger from that. 

If I switch to clientCode, what happens when the user is in client data mode ie RES or similar? Feels like the current way is more reliable unless you tell me different?
