### ISSUE TITLE
Not able to search international numbers from API

### ISSUE THREAD

**Issue by fahadrashid92** [reapit/foundations#6429]
While integrating Reap IT API from Developers Portal; 
Endpoint:   https://platform.reapit.cloud/contacts/?contactDetail=xxxxxxxxxxxxxx
Contact search endpoint is working with the UAE phone number, but it returns an empty response when we search an international number. We also tried to add 00 at the start of the number, but it still shows Empty Response.
Could you please check and advise

**Specification**
- Await information from developer
- Step through issue and consider why reported behaviour is occurring, paying attention to the underlying data and that it could, depending on how the customer's system is configured, be out of sync. Speak to wider team for assistance as required
-

**Comment by plittlewood-rpt** [comment]
Hi @fahadrashid92 - please can you provide some information about the request you are making and for which customer? It's likely going to be due to the underlying data so if you can give us as much detail as you can about your request parameters and the expected response, we can have a look into this for you. I'll move this into this week's sprint on the assumption you'll be able to come back to us before the end of the week.

**Comment by plittlewood-rpt** [comment]
Hi @fahadrashid92 - please can you provide some more information as requested. We will close this ticket at the end of this sprint if we cannot move forwards with it. Thanks
