### ISSUE TITLE
BriefYourMarket Contact Feed Issue with Pygott and Crone Foundations

### ISSUE THREAD

**Issue by BYMIntegrations** [reapit/foundations#6503]
Hello Support,

I hope you are well.

We have been informed by the customer that there are some issues with the contact numbers. We have performed some analysis on our end and have found that the foundations data is missing the following branches:

Horncastle - Residential, Lincoln - Lettings and Lincoln New Homes.
Have these branches been closed or merged with other branches?

Also the analysis showed that the following two branches have some concerning contact number differences:

Grantham - Residential has 51,525 contacts which is 122,763 less than the old Reapit system.
Grimsby - Residential has 84,046 contacts which is 64,574 less than the old Reapit system.

Is there any reason for this? Have the contacts been merged into a different branch?

If there is any further information you need then please do let me know.

Thanks in advance,

Toby Hunter
Integrations and Support Analyst

0344 800 84 24 (Ext 222) | [TobyH@briefyourmarket.co.uk](mailto:TobyH@briefyourmarket.co.uk)
[www.briefyourmarket.com](http://www.briefyourmarket.com/)

**Comment by plittlewood-rpt** [comment]
Hi @BYMIntegrations 

I have checked the Pygott & Crone system

Horncastle - Residential is Closed and has no contact data associated with it
There is no office called Lincoln - Lettings or Lincoln New Homes in their system

Grantham Residential have 9,827 live contacts and 29,525 archived contacts making a total of 39,352 contacts. Querying `GET /contacts?officeId=GAR` returns 9,827 contacts and `GET /contacts?officeId=GAR&fromArchive=true` returns 29,525 so the figures match exactly

Grimbsy Residential is a similar pictures. They have 25,588 live contacts and 39,624 archived contacts, making a total of 65,211 contacts.  Querying `GET /contacts?officeId=GRR` and `GET /contacts?officeId=GRR&fromArchive=true` returns 25,588 and 39,624 contacts respectively so again the figures match exactly.

I don't believe therefore that there is a problem with the Platform API here. Please come back to me with any further comments as you feel necessary otherwise please close the ticket if you are happy with the response. Thanks

**Comment by plittlewood-rpt** [comment]
Ticket being closed due to lack of further response
