### ISSUE TITLE
Floorplans coming through as featured image

### ISSUE THREAD

**Issue by madebyparent** [reapit/foundations#6566]
We have a few instances where we're getting a floorplan as the featured image. But, it's not set that way in Reapit front-end

Is there any reason why the feed might show different to the software?

Listing - https://curchods.designbyparent.co.uk/display/CER220115/

**Comment by AshDeeming** [comment]
Hi @madebyparent 

I can't replicate this issue currently. Can you provide any other details to reproduce please?

**Comment by plittlewood-rpt** [comment]
HI @madebyparent - there is a known issue with AgencyCloud where the image order index does not always get set correctly. In the case of the example property, the image with order index 1 is actually set to the floorplan which is why you are seeing the behaviour described in the API. A similar issue was reported in #5642 last year. Users can resolve the problem themselves if they drag the main image to position 2 and then back to position 1 again. If you can ask them to do this and confirm back to us if this resolves the problem, there is a workaround until the bug in AgencyCloud gets resolved. This is already logged with our desktop development team
