### ISSUE TITLE
Analytics Schema Docs in developers portal failure to load

### ISSUE THREAD

**Issue by christopherbarclay** [reapit/foundations#6583]
**Describe the bug**
Analytics Schema Docs in developers portal failure to load

**Device (please complete the following information for web issues):**
Chrome
![analytics schema docs expected](https://user-images.githubusercontent.com/103132416/162251061-fd0eb529-c758-4f09-8b5e-cdff8c61ae37.png)
![analytics schema docs now](https://user-images.githubusercontent.com/103132416/162251076-78cebae8-defd-4e1c-8c24-f64dc54d41e9.PNG)

**Comment by willmcvay** [comment]
Hi @christopherbarclay thanks for reporting, yes, this was a bug our end caused by a configuration issue our end. See screengrab below, the docs are back now. You may need to do a hard refresh of the page to clear your browser cache of the page if you still don't see them. Apologies for any inconvenience.
![Uploading Screenshot 2022-04-08 at 09.43.06.png…]()
