### ISSUE TITLE
'extras' fields access request for integration

### ISSUE THREAD

**Issue by alexanderg-deleteagency** [reapit/foundations#6586]
Hello,

We would like to request access for several fields in the 'extras' field, for the website integration we are working on.

The details for the request are as follows:

**Customer name:** 
Carter Jonas (CJO)

**Fields required:**
- [ ] Featured Property flag
- [x] Acres
- [x] Rural Tenancy Type
- [x] Buildings Description
- [x] Land Description
- [x] Development Property Kinds (titled 'Development' in the UI)
- [x] Development Plot Ranges (titled 'Plot Range' in the UI)

**Screenshot:**
- Showing the Development and Plot Range attributes in the Agency Cloud UI
![image](https://user-images.githubusercontent.com/78922196/162404497-9dea8153-e73e-42e1-b91d-341e3b8d12af.png)

**Use case:** 
For processing search logic on the website; and for display of the data on the website.

**Comment by plittlewood-rpt** [comment]
We need to split this ticket up as it isn't really appropriate to use the extras field functionality for a lot of these requirements as it's likely developers will want to write these values as well as read.

**Comment by plittlewood-rpt** [comment]
I have begun separating the concerns in this ticket. See above

**Comment by plittlewood-rpt** [comment]
Hi @alexanderg-deleteagency 

Apologies for the delay. To update you on this item:

I cannot see how CJO are marking properties as Featured. Do you have this information? 

Acreage information is already available as part of the `PropertyExternalAreaModel` (property.externalArea) that comes back in the response from `GET /properties` and `GET /properties/{id}`

The three items regarding rural tenancies (rural tenure, buildings and land descriptions) has now been completed as part of [this milestone](https://github.com/reapit/foundations/milestone/137)

The final points about property attribute values is something we are currently reviewing and will be handled in #6910. This is quite a complex undertaking due to the nature of how AgencyCloud is heavily customisable in this area and as such I cannot provide a timescale at this time.

If you can come back to me on the point about featured properties I'd be grateful

Thanks
Pete

**Comment by HollyJoyPhillips** [comment]
Hi @alexanderg-deleteagency, please can you reply regarding the featured property information. If not required any more, we will close this issue. 
Thanks
Holly
