### ISSUE TITLE
Architect further separation of concerns on webhooks pipeline

### ISSUE THREAD

**Issue by plittlewood-rpt** [reapit/foundations#6690]
**Background context**
We recently added more compute resource to process changes from our customer databases (1 replication instance per cluster), however all these events are currently being streamed through a single Kinesis stream. There is a limit into how many concurrent batches can invoke the next stage of the pipeline from a single Kinesis stream and as such we should look at improving this.

There are two options:
- Increase the number of shards and keep a single Kinesis stream
- Increase the number of kinesis streams in a similar way to how we have altered the infrastructure for the replication instance/cluster ratio (1 stream per db cluster)

We should do a cost analysis in the first instance to understand the commercial impact this will have

**Specification**
- Review cost of both options above
- Log implementation tickets to suit chosen approach

**Comment by gnthackray-reapit** [comment]
Right

So I looked into this. Its quite hard to give a definite answer about what is the best approach. But something to consider are as follows:

Using the provisioned model

Shards work out at about $13 a month.

As we have a peak throughput of about 8000k messages a minute. We would need 8 shards, to comfortably accommodate all the logs being generated.  So that's about $104 a month to resolve the bottlenecks with additional shards.

We could split this up into separate streams.  It doesn't appear that there is any additional cost in having this split up over a number of streams, as the cost seems to be calculated on the basis of shards used. 

So far as I can make there isn't any drawback to having multiple streams. Other than the work involved in setting them up. Breaking up our single kinesis stream into multiple ones perhaps on a per db cluster basis, might insulate each stream from problems effecting an individual cluster.

Using on demand provisioning

Possibly this will be cheaper, as shards will be allocated only as they are required. Our average throughput is about ~1300 a minute, which is a lot less than 8000!. Having 8 shards just to handle the rare occasions demand reaches 8000, feels like an inefficient approach, as we'll spending money on something that's standing idle most of the time.

At the time of writing the aws kinesis cost calculator was down, so I can't give specific costs. Hopefully I can update this ticket when it becomes available again.

**Comment by plittlewood-rpt** [comment]
To discuss further this week. Implementation tickets to fllow
