### ISSUE TITLE
PATCH appointment returns 404 but GET returns 200

### ISSUE THREAD

**Issue by bisoh** [reapit/foundations#6854]
Hello, 

I am trying to update the description of appointment BRS2103459 and it fails with a 404 error. The message in the response , "_Entity \"LiveContact\" (BRS210509) was not found._". When doing a GET {reapitApiUrl}/appointments/BRS2103459, the appointment comes up.

Patch request body
```
{
   "description":"some text"
}
```
Patch request header contins 
**If-Match = "the correct etag"**

Can someone explain to me what the error means and how to resolve it ?

Much appreciated.
Bassem

**Comment by plittlewood-rpt** [comment]
HI @bisoh - this is happening because contact BRS210509 appears to have been deleted so as far as the API is concerned the appointment is now orphaned. The error message returned aligns with the status code, but you'll get a 200 back because the appointment itself does exist. To allow your patch to work, you'd need to clear the attendee at the same time. Hope this helps
