### ISSUE TITLE
Add latest meter readings to Property API

### ISSUE THREAD

**Issue by SteveRad** [reapit/foundations#6879]
**Is your feature request related to a problem? Please describe.**
We download property information and a request was made to pull in, for example, the Council Tax band and the latest electric and gas meter readings from Reapit, Council tax band is an available field on the property object, however the meter fields aren't available on the property object

**Describe the solution you'd like**
To have the latest submitted meter readings available on the property object 

**Describe alternatives you've considered**
Adding new APIs to sync tenancy meter readings, which is not possible at this time

**Comment by plittlewood-rpt** [comment]
Hi @SteveRad - meter readings are attached to tenancies rather than properties, and are therefore exposed on the tenancies endpoint. To access this data you would need to update your accordingly. It is worth noting that tenancy data can be embedded in the response from the properties endpoint (eg `GET /properties?embed=tenancies`)
