### ISSUE TITLE
Transpose legacy REST API endpoints

### ISSUE THREAD

**Issue by jazzlall** [reapit/foundations#6935]
Not sure if this has already been requested by Sapphira as I can't find anything. We have the following endpoints in the legacy REST API that need to be available in Platform

GET /negotiators/{ID}/availability
GET /negotiators/{ID}/appointments
GET /valuationAppointments
GET /viewingAppointments
GET /availability
DELETE /appointments/{ID} 

The context for this is for the new version of the Booking a Valuation/Viewing functionality (previously known as RDA) that the AP will be building and cannot against the legacy API's

**Comment by HollyJoyPhillips** [comment]
Hi Jazz, 

With regards to the following:

GET /negotiators/{ID}/appointments
GET /valuationAppointments
GET /viewingAppointments
DELETE /appointments/{ID}

The APPOINTMENTS endpoint already allows for searching by type and by negotiator.
Appointment types are customisable, so we provide a configuration endpoint GET /configuration/appointmentTypes

You can cancel appointments but not delete. This is by design for audit trails etc and we won’t be able to add a delete endpoint.

With regards to following (availability):

GET /negotiators/{ID}/availability
GET /availability

To provide availability, we would have to add quite a lot of business logic and user specific configuration on the Platform. The Platform was not designed in this way and not something we would want to do.

However, we did look into this early last year and the way to do this would be for AP to write the logic in the app/integration. For example, they could obtain all appointments for a specific negotiator/office and then surface in the app, the available time slots. This is available to do now.

**Comment by jazzlall** [comment]
Thanks @HollyJoyPhillips , based on your feedback I'm happy to close this.
