### ISSUE TITLE
No Brochures appearing for certain properties

### ISSUE THREAD

**Issue by MSB89** [reapit/foundations#6957]
We have been given reports that some Brochures are not coming through in API calls for said documents.

Example properties are:
KEL20070, ECM220001, ECM210014, ECM220011

The developers in this project are from an outside agency, I am posting on their behalf so I do not have eyes on the API response but if there are any questions I can feed back to them.

**Comment by MSB89** [comment]
@MSB89 
Sure, the company is Galbraith.

**Comment by plittlewood-rpt** [comment]
HI @MSB89 - please can you ask the developers you are working with for some more information? I've just checked our properties API and for all but the first property (which doesn't seem to exist so they may have given you the wrong reference)  the brochures are returning without a problem. Please can you find out what API calls they are making and what the problem seems to be?

It's worth also noting that we have added a new field at the backend of last week that exposes a publicly accessible URL to the brochure which they may find useful.

Thanks
Pete

**Comment by plittlewood-rpt** [comment]
Hi @MSB89 - please let us know if we can be of further assistance. This item will be closed at the end of the week based on the above unless more information is provided. Thanks
