### ISSUE TITLE
What has happened to the DateMarketed field?

### ISSUE THREAD

**Issue by eddybennett** [reapit/foundations#7271]
**Summary**
In the legacy feed we had the DateMarketed field, this is no longer available and there doesn't seem to be an equivalent?
How do you find out the date at which a property goes from sale unavailable to sale available?

Thanks

**Comment by eddybennett** [comment]
Hi @AshDeeming, 

I am not sure, but is that the date at which the property goes from for sale unavailable to for sale available?

The client is saying that they see a note of this in the activity log.

Thanks

**Comment by MarkFieldhouse** [comment]
HI @AshDeeming 

Michael Holgate commented on case:
Hi Mark,
Thank you for your email. If you would like to pull through new properties based on the date that the status was changed to Available, then you can look at the DateMarketed field. An example shown below:
Property - CHE202771

Please see image below: 
![perry b new listing status date marketed](https://user-images.githubusercontent.com/108399838/178957556-40159570-55d1-426a-b0b0-4cabf925bbe8.PNG)

Where can we find the datemarketed field in the api for that property? 

We have taken a data dump of that property- can you please highlight the field we should focus on to associate for new properties?

CHE202771 DUMP

 "id": "CHE202771",

  "created": "2020-08-28T16:05:32Z",

  "modified": "2022-06-07T13:54:35Z",

  "marketingMode": "selling",

  "currency": "GBP",

  "alternateId": null,

  "address": {

    "buildingName": "Flat 11 Jubilee Court",

    "buildingNumber": "",

    "line1": "Commercial Street",

    "line2": "Leckhampton, Cheltenham",

    "line3": "",

    "line4": "Gloucestershire",

    "postcode": "GL50 2AJ",

    "countryId": "GB",

    "geolocation": {

      "latitude": 51.8912,

      "longitude": 2.078985
    }

  },

  "areaId": "",

  "strapline": null,

  "description": "A fantastic two bedroom retirement apartment located in a desirable residential area within easy walking distance of Bath Road.",

  "longDescription": "A beautifully presented two bedroom first floor retirement apartment for the over 60’s located in a quiet and desirable residential area just off the Bath Road. \r\rThe practical and bright accommodation provides large reception room with feature fireplace and plenty of space for a dining table, white modern fitted kitchen with electric cooking facilities, white extractor and stainless sink and drainer with mixer tap , shower room with large glazed shower enclosure and built in vanity unit and fully tiled walls and two good size bedrooms. \r\rFurther benefits include a lift, a wall mounted security intercom handset with pull cord facility, off road parking (on a first come first served basis,) a launderette, communal recreation / coffee lounge. For visitors living further afield there is a guest room and facilities (to be booked in advance.) There is warden assistance if needed within set times. No onward chain.",

  "localAuthorityCompanyId": "TET20000011",

  "summary": "• Luxury retirement apartment\rTwo bedrooms
\rLarge reception room
\rFirst floor
\rCommunal lounge
\rDesirable location
\rWarden assisted
\rParking
\rClose to Bath Road
\rCommunal garden"
,

  "departmentId": "G",

  "negotiatorId": "RMA",

  "bedrooms": 2,

  "bedroomsMax": 0,

  "receptions": 1,

  "bathrooms": 1,

  "numberOfUnits": 0,

  "parkingSpaces": 0,

  "councilTax": null,

  "internetAdvertising": true,

  "isExternal": false,

  "viewingArrangements": "Stephen away from 27/02/22 - 27/03/22. Contact Michael instead 01242 221 671 / [elekton000@protonmail.com](mailto:elekton000@protonmail.com)\rLIZ, MANAGER : passed away Fe '21. As of 2/06 no-one else yet appointed.\rNew manager = Mike Grover. 01242 579653\rAGE LIMIT = 60 years \rE&M (Berkley House) = managing agents\r2/06 Lift now working.\r26.11 Lift still not working - waiting on a new panel to be delivered. \rProperty vacant - Keys hold fob for\"security\" pass for front door\rCheltenham Borough Council - Band D\rLeasehold 125 years from 2003\rService Charge £3,838 Ground Rent £399pa\rManaged by first Port Retirement Property Services \rMains Water, Sewerage, Electric\rNO GAS\rStop tap under the sink \rNew hot water tank in 2018\rElectric Storage Heaters\rCircuit board in the hall\rOver 60's\rLift \rLaunderette (washing machine is NOT allowed to be fitted in the partment)\rV thinks about 20 flats there give or take. \rParking never had issues parking there, would guess about half residents have cars.",

  "videoUrl": "https://property-teaser-video.s3.eu-west-1.amazonaws.com/85faf10f-9e8d-415c-a496-0080518537e1.mp4",

  "videoCaption": "Niche Video",

  "video2Url": null,

  "video2Caption": null,

  "notes": "",

  "boardStatus": null,

  "boardNotes": null,

  "featuredImageUrl": null,

  "url": null,

  "groundRent": 0,

  "groundRentComment": null,

  "groundRentReviewDate": null,

  "groundRentIncrease": null,

  "serviceCharge": 0,

  "serviceChargeComment": null,

  "boardUpdated": null,

  "archivedOn": null,

  "fromArchive": false,

  "rural": null,

  "externalArea": null,

  "internalArea": null,

  "epc": {

    "exempt": false,

    "eer": 75,

    "eerPotential": 77,

    "eir": 0,

    "eirPotential": 0

  },

  "selling": {

    "instructed": "2020-09-16",

    "price": 270000,

    "priceTo": null,

    "reservationFee": 0,

    "qualifier": "askingPrice",

    "status": "forSale",

    "disposal": "privateTreaty",

    "completed": null,

    "exchanged": null,

    "accountPaid": null,

    "tenure": {

      "type": "leasehold",

      "expiry": null

    },

    "vendorId": "CHE202771",

    "agency": "soleAgent",

    "agencyId": "SA",

    "fee": {

      "type": "percentage",

      "amount": 1.25

    },

    "exchangedCompanyFee": null,

    "recommendedPrice": 0,

    "brochureId": "CIR20003524",

    "publicBrochureUrl": null,

    "exchangedPrice": 0,

    "exchangedOfficeId": "",

    "decoration": [],

    "sharedOwnership": {

      "sharedPercentage": null,

      "rent": null,

      "rentFrequency": ""

    }

  },

  "letting": null,

  "commercial": null,

  "regional": null,

  "type": [

    "flatApartment"

  ],

  "style": [],

  "situation": [],

  "parking": [

    "residents"

  ],

  "age": [],

  "locality": [],

  "specialFeatures": [

    "Retirement"

  ],

  "rooms": [],

  "roomDetailsApproved": false,

  "officeIds": [

    "PBL"

  ],

  "lostInstructionDate": null,

  "lostInstructionNote": null,

  "extrasField": {},

  "_eTag": "\"70B1F9D61905306C5DA1CFD723297534\"",

  "_links": {

    "self": {

      "href": "/properties/CHE202771"

    },

    "images": {

      "href": "/propertyImages/?propertyId=CHE202771"

    },

    "documents": {

      "href": "/documents/?associatedType=property&associatedId=CHE202771"

    },

    "offers": {

      "href": "/offers/?propertyId=CHE202771"

    },

    "appointments": {

      "href": "/appointments/?propertyId=CHE202771"

    },

    "negotiator": {

      "href": "/negotiators/RMA"

    },

    "offices": {

      "href": "/offices/?id=PBL"

    },

    "department": {

      "href": "/departments/G"

    },

    "vendor": {

      "href": "/vendors/CHE202771"

    },

    "sellingBrochure": {

      "href": "/documents/CIR20003524"

    },

    "sellingAgency": {

      "href": "/configuration/agencyTypes/SA"

    },

    "localAuthority": {

      "href": "/companies/TET20000011"

    }

  },

  "_embedded": null,

  "metadata": {}

}

**Comment by MarkFieldhouse** [comment]
@AshDeeming - Can you come back to me on this please asap?

**Comment by MarkFieldhouse** [comment]
> Hi @eddybennett I assume you're referring to the instructed date, in which case it's in the Property.Selling.Instructed field
> 
> Alternatively, please provide a screenshot of the field in AgencyCloud & we'll have this reviewed.

**Comment by plittlewood-rpt** [comment]
HI @eddybennett 

The field Ash mentions is the date the property was instructed - typically when a property goes from Market Appraisal/Valuation to For Sale. This field is on the Financial screen in the AgencyCloud CRM. 

If you are wanting to get hold of dates from the activity feed, you need to use the `GET /journalEntries` endpoint with the appropriate filters

Please let me know if this does not answer your question

**Comment by MarkFieldhouse** [comment]
@plittlewood-rpt @AshDeeming 

Hi Guys,

We have taken a extract of a property - [https://www.perrybishop.co.uk/property/FAR220259/] please see below;  But we can't see anywhere in the data dump from swagger/ grapql where the 'what seller love' appears within the api? Can you please highlight within the code where this data field can be found? I have also attached screenshots below of the What seller loves data field looks like in Reapit. 

(https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.perrybishop.co.uk%2Fproperty%2FFAR220259%2F&data=05%7C01%7Celizadunlop%40perrybishop.co.uk%7C3036525c980d4af1848b08da8c281fb3%7C288cfde6c6904a04a3e86b2bfaac096f%7C0%7C0%7C637976401268692028%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=DvJT%2FnbkRyWH8M%2B1kaepSEMaqKS1tPDSdJMaknT5o3E%3D&reserved=0)
 
{
  "id": "FAR220259",
  "created": "2022-07-14T11:12:47Z",
  "modified": "2022-08-31T11:50:50Z",
  "marketingMode": "selling",
  "currency": "GBP",
  "alternateId": null,
  "address": {
    "buildingName": "",
    "buildingNumber": "39",
    "line1": "Ferndale Street",
    "line2": "Faringdon",
    "line3": "Oxfordshire",
    "line4": "",
    "postcode": "SN7 7AH",
    "countryId": "GB",
    "geolocation": {
      "latitude": 51.657927,
      "longitude": -1.580205
    }
  },
  "areaId": "",
  "strapline": null,
  "description": "Beautiful period cottage in the heart of Faringdon",
  "longDescription": "A beautifully presented two-bedroom cottage situated in the heart of Faringdon. This home has the most wonderful feel and is deceptively spacious throughout.\r\rYou enter into the living room which has an exposed stone fireplace with log burning stove, wooden beams and a wood floor. There are several in-built storage cupboards and access to a downstairs cloakroom.  From the living room, you are led through to the dining area with French doors out to the patio garden and a wooden staircase to the tanked basement which is currently set up as a crafts room/study. At the rear of the property is a wonderful fitted kitchen with ample floor and wall mounted units and integrated oven, fridge/freezer and dishwasher. \r\rUpstairs are two good-sized double bedrooms and a family bathroom.\r\rOutside, the property boasts a lovely patio courtyard garden which is incredibly private and sunny.\r\rVendor quote: \"The fact I have lived here for almost 24 years is a good indication of how much I love this house. The sense of light, space and calm makes me happy. I have the perfect combination of period and modern since the cottage was fully renovated in 1988. The cool cellar is one of the main reasons I was able to stay here for the whole time my children were growing up. It has been used as a play room, TV room, bedroom, hobby room and just as a useful storage space. Ferndale Street sits between the wonderful Folly Woodland and the Town Centre shops, pubs and restaurants and that has massive appeal for me too.\"\r\rCouncil Tax Band: C",
  "localAuthorityCompanyId": "TET20000010",
  "summary": "• Period cottage\r• Two double bedrooms\r• Lovely decor\r• Open fireplace\r• Basement study / crafts room\r• Dining area\r• Fitted kitchen\r• Family bathroom\r• Courtyard garden\r• Central location",
  "departmentId": "G",
  "negotiatorId": "GMI",
  "bedrooms": 2,
  "bedroomsMax": 0,
  "receptions": 2,
  "bathrooms": 1,
  "numberOfUnits": 0,
  "parkingSpaces": 0,
  "councilTax": "C",
  "disabledPortalIds": [],
  "internetAdvertising": true,
  "isExternal": false,
  "viewingArrangements": "vendor been there 24 years-end of chain as moving into rented\rVIEWINGS = Vendor needs notice owing to 3 dogs in property\rWHY = Vendor has identified an onward she would like to buy (end of chain)\rCOUNCIL TAX = Band C\rELECTRICS = last tested unknown. Circuit board in downstairs loo\rBOILER = 2007 when kitchen was refurbished.  Serviced within 12 months. just serviced aug 22.  Hot water tank in airing cupboard, cold water tank in loft\rAGE OF PROPERTY = originally 1800-1850.  Fully refurbished in 1988\rFREEHOLD\rMAINS DRAINS\rSTOP COCK = Under kitchen sink\rLOFT = Partially boarded - there is a loft ladder installed\rGARAGE = None\rPARKING = None\rGUARANTEES = FENSA (windows), tanking of basement\rEXTENSIONS - Extended in 1988\rFENCES - This property has right of egress over garden of #41 into the alleyway\rFLOODING\rFridge, freezer, narrow dishwasher, electric oven and gas hob all integrated.\r\rWoodburning stove has been in place since 1988 and is a Villager. \rThe new regulations put in force that by 2022, all NEW log burners and wood-burning stoves must restrict their emissions to an agreed level. In other words, the old log burners can remain operational, but the new ones have to be more efficient.\rMine is a Villager Stove and they now united under the Arada brand along with Aarrow and Stratford stoves. The model I have will no longer be available but there are no regulations regarding its use simply that it cannot be sold anymore.",
  "videoUrl": null,
  "videoCaption": null,
  "video2Url": null,
  "video2Caption": null,
  "notes": "VENDOR USING BOWER BAILEY AND MARK WESTON FOR ONWARD MORTGAGE",
  "boardStatus": null,
  "boardNotes": null,
  "featuredImageUrl": "[https://assets.reapit.net/pba/live/pictures/FAR/22/FAR220259_39.jpg](https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fassets.reapit.net%2Fpba%2Flive%2Fpictures%2FFAR%2F22%2FFAR220259_39.jpg&data=05%7C01%7Celizadunlop%40perrybishop.co.uk%7C3036525c980d4af1848b08da8c281fb3%7C288cfde6c6904a04a3e86b2bfaac096f%7C0%7C0%7C637976401268692028%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=CsXjN7BBbUy8UkZ%2FSw5GO1HNfLMc73jJRomXcQpdvKs%3D&reserved=0)",
  "url": null,
  "groundRent": 0,
  "groundRentComment": null,
  "groundRentReviewDate": null,
  "groundRentIncrease": null,
  "serviceCharge": 0,
  "serviceChargeComment": null,
  "boardUpdated": null,
  "archivedOn": null,
  "fromArchive": false,
  "rural": null,
  "externalArea": null,
  "internalArea": null,
  "epc": {
    "exempt": false,
    "eer": 55,
    "eerPotential": 76,
    "eir": 0,
    "eirPotential": 0
  },
  "selling": {
    "instructed": "2022-07-26",
    "price": 290000,
    "priceTo": null,
    "reservationFee": 0,
    "qualifier": "offersInExcess",
    "status": "forSale",
    "disposal": "privateTreaty",
    "completed": null,
    "exchanged": null,
    "accountPaid": null,
    "tenure": {
      "type": "freehold",
      "expiry": null
    },
    "vendorId": "FAR220259",
    "agency": "soleAgent",
    "agencyId": "SA",
    "fee": {
      "type": "percentage",
      "amount": 1
    },
    "exchangedCompanyFee": null,
    "recommendedPrice": 0,
    "valuationPrice": 0,
    "brochureId": "CIR22013008",
    "publicBrochureUrl": "[https://assets.reapit.net/pba/live/pdf.php?p=FAR220259&t=S](https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fassets.reapit.net%2Fpba%2Flive%2Fpdf.php%3Fp%3DFAR220259%26t%3DS&data=05%7C01%7Celizadunlop%40perrybishop.co.uk%7C3036525c980d4af1848b08da8c281fb3%7C288cfde6c6904a04a3e86b2bfaac096f%7C0%7C0%7C637976401268692028%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=XZ1r8nhRdZIthCFzG5X8qU9Txbhtqcou0qeAquf3G%2BA%3D&reserved=0)",
    "exchangedPrice": 0,
    "exchangedOfficeId": "",
    "decoration": [
      "veryGood"
    ],
    "sharedOwnership": {
      "sharedPercentage": null,
      "rent": null,
      "rentFrequency": ""
    }
  },
  "letting": null,
  "commercial": null,
  "regional": null,
  "type": [
    "house"
  ],
  "style": [
    "terraced"
  ],
  "situation": [
    "patio"
  ],
  "parking": [],
  "age": [
    "period"
  ],
  "locality": [
    "townCity"
  ],
  "specialFeatures": [],
  "unmappedAttributes": [],
  "rooms": [],
  "roomDetailsApproved": false,
  "officeIds": [
    "FAR"
  ],
  "lostInstructionDate": null,
  "lostInstructionNote": null,
  "extrasField": {},
  "_eTag": "\"F5030129A0D5C5D7889F1D728C8B7EE3\"",
  "_links": {
    "self": {
      "href": "/properties/FAR220259"
    },
    "images": {
      "href": "/propertyImages/?propertyId=FAR220259"
    },
    "documents": {
      "href": "/documents/?associatedType=property&associatedId=FAR220259"
    },
    "offers": {
      "href": "/offers/?propertyId=FAR220259"
    },
    "appointments": {
      "href": "/appointments/?propertyId=FAR220259"
    },
    "negotiator": {
      "href": "/negotiators/GMI"
    },
    "offices": {
      "href": "/offices/?id=FAR"
    },
    "department": {
      "href": "/departments/G"
    },
    "vendor": {
      "href": "/vendors/FAR220259"
    },
    "sellingBrochure": {
      "href": "/documents/CIR22013008"
    },
    "sellingAgency": {
      "href": "/configuration/agencyTypes/SA"
    },
    "localAuthority": {
      "href": "/companies/TET20000010"
    }
  },
  "_embedded": null,
  "metadata": {}
}

<img width="1091" alt="Screenshot 2022-09-05 at 11 54 52" src="https://user-images.githubusercontent.com/108399838/188433024-d24fdadc-fc64-4208-a06c-b02d49eb53b3.png">

<img width="1440" alt="Screenshot 2022-09-05 at 12 01 20" src="https://user-images.githubusercontent.com/108399838/188434122-71bdbe63-7e7d-4565-ae8f-a136ffef4de2.png">
