### ISSUE TITLE
Not able to fetch open house attendees

### ISSUE THREAD

**Issue by komalpuri27** [reapit/foundations#7285]
**Describe the bug**
We are not able to fetch openHouseAttendees
**To Reproduce**
Steps to reproduce the behaviour eg:

1.  Go to the API /appointments/MKT2201683/openHouseAttendees, it returns null result.
2.  While we can see attendees in the appointments API for the same appointment  id  MKT2201683

**Expected behaviour**
We would like to use API /appointments/{id}/openHouseAttendees, since this gives us more information about the attendee as well.

**Screenshots**
![image](https://user-images.githubusercontent.com/94682169/178921224-ccaf793f-4566-47bc-bd63-4525533a4e03.png)
![image](https://user-images.githubusercontent.com/94682169/178921264-10e68569-df90-4d10-85d8-d595b4105ea7.png)
![image](https://user-images.githubusercontent.com/94682169/178921307-60484e63-eed3-481e-9b4b-b7dbf876e1f1.png)
![image](https://user-images.githubusercontent.com/94682169/178921698-adf0efab-b2ae-4969-bdc7-d005d6bed4fd.png)

**Comment by plittlewood-rpt** [comment]
Hi @komalpuri27 - the appointment id you have specified is for a single viewing appointment and not the open house appointment, which has an appointment id of RPT2101879 - you should find that GET /appointments/RPT2101879/openHouseAttendees returns the data you are looking for. As the endpoint name would suggest, the openHouseAttendees sub resource will only ever return data for open house appointment types (typeId = 'OH')

Please let me know if this does not resolve your query. Thanks

**Comment by komalpuri27** [comment]
Wow thanks for the explanation @plittlewood-rpt appreciate it, that explains it well. So, if I may get a little more clarity on the appointment types 'VW' and 'PI'.

Also, then does that mean the three types OH, VW and PI are all kind of inspection type of appointments.

Sorry, if my question is a little weird, but I want to understand how we treat all the three types.

**Comment by plittlewood-rpt** [comment]
No problem. Each customer can have custom appointment types so no single system will be the same, which is why using the /configuration/appointmentTypes endpoint is crucial to understand a customer's configuration. Typically they will have these three types (Open House functionality is not enabled in all systems though)

VW = Viewing. Typically used for a single viewing appointment
OH = Open House appointment. Treat this as a 'parent' appointment which has lots of sub appointments underneath. These have a type of HV (instead of VW) and can also be accessed directly at GET /appointments/{id} (one example is MKT2201691 that is associated to your open house appointment from your screenshot above)
PI = Property Inspection. I think this is used interchangeably with Viewing by some agents in Australia

**Comment by komalpuri27** [comment]
thanks @plittlewood-rpt this can be closed now
