### ISSUE TITLE
App Installed for YOM - not showing all branches

### ISSUE THREAD

**Issue by roscoe2001** [reapit/foundations#7495]
I raised this on the chat earlier but wanted to also put it on here just so it's not lost (the chat mentioned I should be receiving an email).

Basically we have an app installed for the whole organisation (YOM) - Works Order Management

It was installed for an Office Group but was then changed to be installed for the whole orgnisation but it's still only showing data from the Office Group it was originally installed for (we've logged in / out etc)

Is there something we additional we need to do to make it work for the whole of YOM?

![YOMWO](https://user-images.githubusercontent.com/96238131/183706473-5f6a4b02-d413-45c1-9ef7-4ab84c636278.png)

**Comment by HollyJoyPhillips** [comment]
@roscoe2001 FYI, I'm picking this up and investigate.

**Comment by roscoe2001** [comment]
@HollyJoyPhillips - if the quickest thing to solve this one is to : -
- I uninstall it
- You then clear any settings behind the scenes
- Then I reinstall it
Then I'm happy to go ahead on that basis

**Comment by HollyJoyPhillips** [comment]
@roscoe2001 Apologies for the delay on this one I had to review the logic. Unfortunately, that's not how the app is intended to work. Whilst the app is installed for the whole organisation, it will still respect office grouping. If the user that logs into the app is part of office group, they will only see data for offices within that group. We cannot change that logic because of how other customers are using the app. 

However, it's possible we could add another layer but that will require scoping, development and input from another department. I will raise a seperate ticket to review with the team.

**Comment by roscoe2001** [comment]
The layer sounds interesting but your answer did actually help slightly.

I noticed you said 'If' i.e.: -
>> 'If' the user that logs into the app is part of office group

So I removed myself from the Office Group and it started working as I expect.

Which is quite interesting because what would also be good is if : -
An App is installed for 2 Office Groups but the user who's logged in isn't part of either Office Group then they see across both Office groups (in a similar way to how the see across the organisation if it's installed for the whole organisation)

**Comment by HollyJoyPhillips** [comment]
@roscoe2001 Yes, if a user is not associated to an office group they will have access to all data.

**Comment by roscoe2001** [comment]
Which is good if the App is installed for the full organsiation (I've changed it so it's working like that for now).

The problem is I (in effect) want the App to be installed for 2 office groups with the user having access to both office groups (but obviously if they're aren't in either office group they don't have the app installed at all!)
