### ISSUE TITLE
Negotiator Endpoint and SUMS

### ISSUE THREAD

**Issue by soilleir** [reapit/foundations#7517]
I can successfully create the neg account via the API but it isnt enabled in SUMS.

How do I enable SUMS  when creating a new (or patching an existing) negotiator via the API?  I can't find any documentation about it.  

Thanks in advance

**Comment by AshDeeming** [comment]
Hi @soilleir 
Currently in order for a Negotiator to be created & added to Reapit Connect/SUMS, this must be done in AgencyCloud's Negotiator Setup screen

Write requests via the Platform won't result in a User being created in Reapit Connect or SUMS.

If you would like to request this functionality, please use & populate the below template. We will then ensure this is reviewed by the relevant team for consideration. 



**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

**Describe the solution you'd like**
A clear and concise description of what you want to happen.

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered.

**Additional context**
Add any other context or screenshots about the feature request here.

**Comment by AshDeeming** [comment]
Hi @soilleir 
As we haven't had a response for over 7 days, i'll close this ticket however - as above, if you would like to request this please raise a Feature Request ticket
