### ISSUE TITLE
Unusually bad performance from AU

### ISSUE THREAD

**Issue by NickStallman** [reapit/foundations#7520]
**Describe the bug**
We've found an API call which takes an incredibly long time.

![image](https://user-images.githubusercontent.com/136553/184301241-43bfc23c-d263-4e72-a8d4-6bbbfd15bae8.png)

**To Reproduce**
```
curl --location --request GET 'https://platform.reapit.cloud/properties/?pageSize=25&pageNumber=1&sortBy=modified&modifiedFrom=2016-12-08T16:46:58Z&embed=appointments&embed=images&embed=landlord&embed=vendor&embed=tenancies&id=BDF140688' \
--header 'Accept: application/json' \
--header 'Authorization: Bearer 12345'
--header 'reapit-customer: ROD'
--header 'api-version: 2020-01-31'
```

It's ok without the embeds so it's something to do with them.

**Expected behaviour**
Since this is filtering for a specific id, I'd expect a result in <1 second typically.

**Comment by plittlewood-rpt** [comment]
Hi @NickStallman - The embed operations effectively make additional API calls to the relevant endpoints in the background. It's a convenience mechanism for developers but still uses the same APIs under the hood. It's likely a specific embed operation that's causing the bulk of the slowdown (possibly appointments, since that's quite a complex service). I've started discussions with our infra team about looking at altering the global traffic routing policy so that traffic is routed to the nearest the customer _database_ rather than the infrastructure nearest the API caller. Naturally this won't be something we can do overnight, but early discussions are happening

**Comment by NickStallman** [comment]
Yep the global API routing will be a big benefit, I opened this as a separate ticket just in case there was something particularly inefficient about this query that could be optimised and benefit even local API calls.

**Comment by plittlewood-rpt** [comment]
Hi Nick, I'm going to close this one as there's another ticket running. In any case, this should be resolved now as per my comments last week. Thanks
