### ISSUE TITLE
Cannot create an applicant with a non GBP currency

### ISSUE THREAD

**Issue by eazynow** [reapit/foundations#7522]
**Describe the bug**
When creating a new applicant, there is no field to pass in the currency, however on the GET of applicant it does return one.

Passing a `currency` element does nothing and is ignored. How do we set the currency on a per applicant basis?

**To Reproduce**
POST to /applicants in sandbox with following payload (noting the currency has been set to EUR):
```json
{
  "currency": "EUR",
  "marketingMode": "buying",
  "active": true,
  "notes": "Looking to move his mother back into the area",
  "lastCall": "2019-11-12",
  "nextCall": "2022-12-29",
  "departmentId": "G",
  "solicitorId": "OXF18000012",
  "type": [
    "house",
    "maisonette",
    "cottage"
  ],
  "style": [
    "detached",
    "semiDetached"
  ],
  "situation": [
    "garden",
    "patio"
  ],
  "parking": [
    "garage"
  ],
  "age": [
    "period"
  ],
  "locality": [
    "rural"
  ],
  "bedroomsMin": 4,
  "bedroomsMax": 5,
  "receptionsMin": 1,
  "receptionsMax": 2,
  "bathroomsMin": 1,
  "bathroomsMax": 0,
  "parkingSpacesMin": 0,
  "parkingSpacesMax": 0,
  "locationType": "areas",
  "locationOptions": [
    "SOL",
    "BHM",
    "WLV"
  ],
  "buying": {
    "priceFrom": 250000,
    "priceTo": 275000,
    "decoration": null
  },
  "renting": null,
  "externalArea": {
    "type": "acres",
    "amountFrom": 2,
    "amountTo": 3
  },
  "internalArea": {
    "type": "squareFeet",
    "amount": 1500
  },
  "source": {
    "id": "RMV",
    "type": "source"
  },
  "officeIds": [
    "BGV"
  ],
  "negotiatorIds": [
    "AAAD"
  ],
  "related": [
    {
      "associatedId": "OXF22000210",
      "associatedType": "contact"
    }
  ],
  "metadata": {
    "CustomField1": "CustomValue1",
    "CustomField2": true
  }
}
```

**Expected behaviour**
GET applicant by ID should return the applicant with the correct currency, however it always returns GBP.

**Additional context**
Is this related to #7204 ?

**Specification**
- Project: Reapit.Services.Applicants
- Add multi currency mechanism to this service as per what we did recently in the properties service. Ensure that the currency conversions are done when an applicant is stored in a non-base currency. Leverage existing data in dynamo table to access exchange rate information (CF stack may need additional permission on the IAM role to be able to access this table)
- Update `CreateApplicantModel` to allow currency to be set when initially creating a new applicant
- Ensure this is thoroughly tested

**Comment by shawnzvinis** [comment]
@AshDeeming @plittlewood-rpt @HollyJoyPhillips This issue affects one of your largest clients.
When we create/update Applicants their budgets are incorrectly added in GBP rather than in EUR (for their European branches). They are reporting this is causing significant operational issues on their end. As my colleague Erol stated, "currency" is returned on GET requests, but not available on POST and PATCH requests. The resolution we require is to be able to provide "currency" on POST and PATCH requests for Applicants to ensure the correct data is added to Reapit. Please can you re-review based on this additional information and look at escalating the issue, as the client requires resolution as soon as possible. Thank you.

**Comment by plittlewood-rpt** [comment]
Hi @eazynow this is now in Production. Please let me know if you encounter any issues
