### ISSUE TITLE
Robinson and Hall Field Request

### ISSUE THREAD

**Issue by Matt-Marsh** [reapit/foundations#7557]
- Client: Robinson & Hall
- Required fields:
**GENERAL  PROPERTIES SALES**
Length of lease (no. of years remaining)
Current ground rent (£)
Ground rent review period (no. of years/months)
Annual ground rent increase (%)
Annual service charge (£)
Council tax band - England, Wales and Scotland (including "TBC" option for New Homes)
**GENERAL PROPERTIES LETTINGS**
Tenancy length - Attributes panel
Council tax band - additional information

- Screenshots:
**LENGTH OF LEASE**
![image](https://user-images.githubusercontent.com/55884592/185587469-27d46d0c-4c0a-42c3-be1a-fe3162e07fac.png)
**GROUND RENT, GROUND RENT REVIEW PERIOD, ANNUAL GROUND RENT INCREASE AND ANNUAL SERVICE CHARGE**
![image](https://user-images.githubusercontent.com/55884592/185587587-d4cc2d22-c35a-4675-8f0d-c74ba3a6f1bd.png)
**COUNCIL TAX BAND**
![image](https://user-images.githubusercontent.com/55884592/185587657-ecd4d1d3-d35d-4981-9079-0a2456ee4e29.png)
**TENANCY LENGTH**
![image](https://user-images.githubusercontent.com/55884592/185587688-1beaf98c-45cd-4d86-a48b-065661ceec7a.png)
**COUNCIL TAX BAND**
![image](https://user-images.githubusercontent.com/55884592/185587726-cb5d0fea-17b5-4c65-83a0-ba2b99178a87.png)

- Use case: We require this data to showcase it on our website.

**Comment by plittlewood-rpt** [comment]
Hi @Matt-Marsh - a lot (if not all) this data is already available. Please can you review the Swagger specification and update this item with the fields which are missing and we will re-review.

Thanks

**Comment by steelcm** [comment]
There are two fields which we can't find in the swagger docs:

- Length Of Lease (Tenure Years/Months).
- Tenancy Length (Tenure Minimum Term (months)).

**Comment by plittlewood-rpt** [comment]
Hi @steelcm thanks. 

The length of lease is a calculated field based on `selling.tenure.expiry` - it's currently up to you to calculate the number of years/months until this date (AgencyCloud does the same thing, rather than storing it - you'll notice if you change those values the expiry date changes, which is what gets stored in the database)
The tenancy minimum term can be found in `letting.minimumTerm`

I think this covers of all your points - can you please let me know if that's the case and we can then close out this ticket

Thanks

**Comment by plittlewood-rpt** [comment]
Closing as all queries have now been answered
