### ISSUE TITLE
GET appointments endpoint ignored start and end dates

### ISSUE THREAD

**Issue by merisis-aaron-parkes** [reapit/foundations#7564]
**Background context**
We have a system which calls the API to retrieve appointment data which is then used to complete reports for properties.

**Specification**
On the 28th of July at between 09:00 and 09:30 UTC a get appointments call was made with the start and end dates set as the 25th of July and 11th of August respectively. The dates appear to have been ignored and all appointments, starting from back in 2018, were returned.

The URL the request was fired at is the following:
https://platform.reapit.cloud/appointments/?pageSize=99&pageNumber=1&includeCancelled=true&includeUnconfirmed=true&officeId={{OFFICE_ID}}&typeId=PI&start=2022-07-25T09%3A13%3A11%2B00%3A00&end=2022-08-11T09%3A13%3A11%2B00%3A00

This call on the 28th was the first occurrence of this issue that we were made aware of; today another request has been made which appears to suffer from the same problem:

https://platform.reapit.cloud/appointments/?pageSize=99&pageNumber=1&includeCancelled=true&includeUnconfirmed=true&officeId={{OFFICE_ID}}&officeId={{OFFICE_ID}}&typeId=CO&typeId=PI&start=2022-08-19T08%3A03%3A46%2B01%3A00&end=2022-09-05T08%3A03%3A46%2B01%3A00

The first appointment returned from a GET request to that URL has a "start" date of "2019-02-27T15:00:00Z"

**Comment by plittlewood-rpt** [comment]
Hi @merisis-aaron-parkes - it's likely that the appointments being returned are recurring appointments where a recurrence would fall inside the date range being queried. These previously were not returned at all. The update was released on 21st July. You should use the `recurring` property and `recurrence` object to understand this data.

Please can you have a look at the data being returned and confirm if this is the case - if it is, this is by design and intended behaviour. If not, please can you share more detail (the customer you are retrieving data for etc)

**Comment by merisis-aaron-parkes** [comment]
Hi @plittlewood-rpt,
It looks like recurring appointments are the cause here, thanks for your help.

**Comment by plittlewood-rpt** [comment]
Thanks for confirming!
