### ISSUE TITLE
Property type appearing in `unmappedAttributes` field

### ISSUE THREAD

**Issue by adam-hf** [reapit/foundations#7569]
The type attribute set for a property is appearing in the `unmappedAttributes` field in the data received from the Foundations REST API and not the `type` field (that is an empty array), is this correct behaviour? If so why are they appearing there, are these custom types? I've attached a screen-shot of the fields in AgencyCloud. The agency we are seeing this with is GTH and property YEO220274.

![prop_types](https://user-images.githubusercontent.com/110461568/186144250-53982ac6-08de-4b09-afde-8dd590c95fe4.png)

**Comment by plittlewood-rpt** [comment]
Hi @adam-hf this is correct behaviour. The fields in the structured type/situation/style etc fields are based on a standard set of supported attributes. When the Platform was built we had to do a lot of research around this area and standardized what is a completely customisable list, otherwise it went against the whole ethos of developers being able to build an app against one dataset that would work against all others. As time has gone on however it's become apparent that the differences in the configuration of these lists between customers has caused issues, which is why the unmappedAttributes collection was introduced. This collection will return any values from these lists (where set on the property or applicant) that aren't in the 'standard' supported set. This gives consumers the best of both worlds, a standard set that will use the same values between systems and can be filtered (ie flatApartment for systems that have "Flat" or "Apartment" or even "Flat/Apartment" as options), and any remaining items that don't form part of the standard set. In terms of how to handle this, you should always use the type/situation/style etc fields first, with the unmappedAttributes collection being a fallback. Please let me know if this does not answer your question.

**Comment by adam-hf** [comment]
@plittlewood-rpt Thank you for the thorough answer, that has cleared things up.
