### ISSUE TITLE
Unable to access oInetRM 

### ISSUE THREAD

**Issue by robchett** [reapit/foundations#7573]
**Describe the bug**
As per #7125 we need access to oInetRM  for YOM/RER/THA. 

**To Reproduce**
use `GET /offices?extrasField=oInetRM` 

**Expected behaviour**
extrasField to contain Rightmove URLs

**Screenshots**
N/A

**Device (please complete the following information for web issues):**
API

**Additional context**
Ideally this would be accessible at Property level as well as an Office

**Comment by plittlewood-rpt** [comment]
Hi @robchett - looking at the data it looks like this is because there are separate sales and lettings branch IDs configured under oInetRmSales and oInetRmLets respectively. If I enable these also it should resolve the problem, but can I just confirm that will solve your problem? It's worth noting that this functionality is tied to the microservice that governs the entity being queried, so it's not possible to return the oInet* data from the properties endpoint

**Comment by robchett** [comment]
Thanks @plittlewood-rpt that will solve the issue. Offices will be sufficient. Properties fitted in slightly better with our workflow but can do without.

**Comment by plittlewood-rpt** [comment]
Hi @robchett thanks - these two additional fields have now been enabled and I can see data being returned eg;

`GET /offices?extrasField=oInetRM&extrasField=oInetRMSales&extrasField=oInetRMLets&pageSize=100&pageNumber=2&sortBy=-modified`

![image](https://user-images.githubusercontent.com/30798627/186434165-3587712b-bb4c-4efe-b102-fc8b15335846.png)
