### ISSUE TITLE
Expose responsibilities, Break clause, Allowed/Disallowed, No gas flag against tenancy

### ISSUE THREAD

**Issue by rushikesh-obx** [reapit/foundations#7627]
**Is your feature request related to a problem? Please describe.**
"Tenant responsibilities, Break clause, Allowed/Disallowed, No gas flag" to be exposed via the Foundations API

**Describe the solution you'd like**
 "Tenant responsibilities, Break clause, Allowed/Disallowed, No gas flag" to be available on a /tenancies/{id} call

Ideally we'd also like to write back above fields to reapit using /tenancies/{id} POST call.

**Describe alternatives you've considered**
No other solution would be possible in Foundations.

**Comment by plittlewood-rpt** [comment]
This ticket should be split into three separate items for:

 - Break clause endpoint
 - Responsibilities endpoint
 - Allowances endpoint

@rushikesh-obx the no gas flag is already available on the properties API and will not be stored against the tenancy since it is attributable to the property and not a tenancy. If you need to get this information in the same HTTP request I would recommend using the `embed` capability on the tenancies API to embed the property

**Comment by plittlewood-rpt** [comment]
This item has now been broken into more manageable parts. Please track the issues above for future updates. Thanks
