### ISSUE TITLE
Syncing invoices to Supplier Invoices section from Fixflo

### ISSUE THREAD

**Issue by NorbiSamu** [reapit/foundations#7633]
Hi Reapit Team,

This is an extremely common request, most recently raised by one of our large mutual clients. I believe they got in touch with Alex Townsend on your end about it too.:

_When an invoice is uploaded on Fixflo, the invoice Document will sync across to 'Documents' under the relevant Works Order. Currently, we do not send this to the Accounts departments, so the client will manually have to do that on Reapit
Fixflo saves invoices into the docs section on the WO, not ias a supplier invoice, just as a regular document. Because Agency Cloud isn’t recognising it as a supplier invoice, it isn’t appearing where it should._

We would be keen to automate this process for our mutual clients, but I am struggling to find this section in our test system. Would you be able to point me in the right direction at all, or add it this to our test system? 

Also, is this possible via your API?

Many thanks,

Norbert Samu - Product Manager - Fixflo

**Comment by plittlewood-rpt** [comment]
When a ‘Supplier Invoice’ is generated or imported, it triggers an action via the accounts section in AgencyCloud. As we do not expose account information via the Platform API currently, uploading the document would not automate that action which is why it is not available in the test system.
We have created a Transactional epic (which you can subscribe to) to capture requests for access to account related data in our long-term column. However, we are not currently able to provide a time frame in which this would be available.

**Comment by plittlewood-rpt** [comment]
Hi @NorbiSamu we are looking at this as part of #7764 at the moment. It's worth noting that due to crossover with accounts processes in our system we'll only be able to allow invoices to be added in a pending state so that they appear in the invoice approvals list for the property managers to handle, which is already in their workflow.

**Comment by AshDeeming** [comment]
Hi @NorbiSamu 
Please could you confirm that the work completed on #7764 is of use & if this ticket can be closed?
