### ISSUE TITLE
Tenancy Activity feed- Previous meter reading 

### ISSUE THREAD

**Issue by jazzlall** [reapit/foundations#7780]
When using the PATCH/tenancies to update meter readings against a tenancy which works as expected. It has been noticed that compared to core AC behaviour it's not recording in the activity feed against the tenancy what the previous reading was against the record for auditing purposes. 

Is this bug or does this need to be a feature request?

![image](https://user-images.githubusercontent.com/36031810/192318169-a5ffe657-3ff3-492a-9bab-3b9c3c1c0b4d.png)

**Specification**
- Project: Reapit.Services.Tenancies
- Familiarise yourself with the journal entry text. From the screenshot it looks like the previous meter reading value AND the date it was taken is in the journal entry text
- Add mechanism to emit notification to journal service (via SQS - functionality already built) when we detect changes to the meter readings. This can only reliably be done when we know the user (auth code flow apps) so we should check the identity here also:
  - If user in context (check identity) set neg code to that user
  - If no user, notification neg code should be completly blank (may need to update journal service to handle this)
- Mechanism may need updating following the introduction of the jnlmisc table into that service
- Double check how AC behaves with regard to writing these journal entries and implement same behaviour

**Comment by plittlewood-rpt** [comment]
HI @jazzlall  it's not a bug as this has never been implemented. There is a long running ticket #308 which this falls into, however there's a slight issue because there's no way in AgencyCloud to record a journal entry when there's no user context (which is the case for server side apps). There's an internal discussion running about this as it's likely going to need structural changes to allow us to do this. What we could potentially do in the meantime is record journal entries for this state change when we know the user that's changed it
