### ISSUE TITLE
SDL Auctions field - Client (Robinson Jackson RBJ) 

### ISSUE THREAD

**Issue by rajeshwl** [reapit/foundations#7794]
Our mutual client Robinson Jackson has added a new field in the Reapit application but its not currently available in the properties API. Can you please share the **extras field name** for the field added.

Field in Application: **SDL Auctions**
Client : Robinson Jackson(RBJ)

Have attached the screenshot. Unfortunately there is a UI issue in the application where the field is been displayed so it's not clearly visible, this has been raised as a issue separately to your team by client.

![image](https://user-images.githubusercontent.com/14073702/192799542-3a30ab66-ba17-477e-a843-5e7bbaa44f2d.png)

**Comment by plittlewood-rpt** [comment]
Hi @rajeshwl - I have enabled access to this field `pSDLAuctionProperty` however it's worth noting that there aren't any properties in the agent's system with this set currently. It's also only enabled for Head Office rather than the whole company so it's only a very small subset of users that will be able to set it.

Access in the usual way ie

`GET /properties?extrasField=pSDLAuctionProperty`

Thanks
