### ISSUE TITLE
500 Error on API Call

### ISSUE THREAD

**Issue by jordanlewis-dngl** [reapit/foundations#7826]
Error - 

_Server returned a non successful status code - HTTPStatusCode=InternalServerError - Reason=Internal Server Error - Content={"statusCode":500,"dateTime":"2022-10-03T09:23:32.9598185Z","description":"An unexpected error has been encountered when fulfilling this request. This incident has been logged and will be investigated. Please try again."}_

Log - 

Removed by AD

**Comment by plittlewood-rpt** [comment]
Hi @jordanlewis-dngl - this should have been resolved around 14:50BST. Please can you confirm you can now access the data as expected? The problem was caused due to a misconfiguration for the specific customer whose data you were accessing. I have liaised with the relevant team to get this rectified. Thanks
