### ISSUE TITLE
Price not displaying after applicant PATCH update

### ISSUE THREAD

**Issue by ebuildwebsolutions** [reapit/foundations#7845]
Hi,

I have updated an applicant record using the PATCH/applicants/{id} API method.

This has successful updated and I can see the updated price fields when I call the applicant record using the GET/applicants/?emailAddresses

The issue is that the estate agent is not seeing the price fields updating within the Reapit CMS. He can see everything else updated except for the price. He sees Price 0 to 9,999,999

![image](https://user-images.githubusercontent.com/25635668/194090375-a38adeaa-09ad-42f6-8764-492c04e23035.png)

I have highlighted the PriceFrom and PriceTo for your reference from the API call. The eTag ID is "60240CA894434CA5AF4AA1AB0E42A327"

![image](https://user-images.githubusercontent.com/25635668/194089798-e42e927b-26ae-4dbf-be59-4ff16d8628c5.png)

Any idea why this is happening?

Kind regards,

Philip.

**Specification**
- Check for a mismatch between system currency setting in EDD's CRM configuration and the Platform configuration. It's likely there is a difference which will mean Platform APIs are storing monetary values in the wrong fields for this customer.

**Comment by plittlewood-rpt** [comment]
Hi @ebuildwebsolutions - can you let us know which agent and applicant this applies to?

**Comment by ebuildwebsolutions** [comment]
Hi Pete,

This is for Ed Dempsey.

Kind regards,

Philip.
________________________________

**Comment by plittlewood-rpt** [comment]
Hi @ebuildwebsolutions this should now be resolved. I'd be grateful if you could ask the agent to run the same test again and confirm. It was caused by a Foundations misconfiguration for this customer - we had their default currency set to GBP when it should have been EUR so some of the currency behaviours weren't running correctly. I've just run my own test using a test applicant on their system and it seems to be doing as it should do now. Thanks

**Comment by ebuildwebsolutions** [comment]
Hi Pete,

Thanks for the update. The estate agent has informed me that the price values are now displaying in the CMS.

Kind regards,

Philip.
