### ISSUE TITLE
Single Office Not Included In Company Wide Webhook

### ISSUE THREAD

**Issue by colearymyhome** [reapit/foundations#7846]
**Describe the bug**
Sherry Fitzgerald (Client ID SFG-GHOG) are on a webhook in Foundations to our API.

Every office that we've transitioned to using webhook hasn't had an issue. However, Sherry Fitzgerald Commercial (Office ID - SFC) isn't triggering the webhook at all using the same behaviour as other Sherry Fitzgerald offices.

The three properties that we are expecting to see trigger webhooks between 2.30pm and 3.30pm today are:

DNH220913, GNH220005, SFC210003 

all of which are not appearing in the Reapit logs for our Webhook:

Can you let us know if there is a difference in configuration for this office or if there is a bug please.

**Comment by plittlewood-rpt** [comment]
Hi @colearymyhome - the office mentioned (SFC) is not part of the office group that uses client id SFG-GHOG so if your app is only installed for that client id (rather than globally for SFG) - which seems to be the case here - then that is why you are not receiving webhooks. The customer would need to add SFC to the office group with that code.

**Comment by plittlewood-rpt** [comment]
You should be able to see the email address of the person that installed the app on the Installations page in the Developer Portal. As the installing user will be an admin, they should already be aware of how to edit office groups, but if not they can contact us directly. Hope this helps

**Comment by colearymyhome** [comment]
Many thanks
