### ISSUE TITLE
Penthouse coming through under "unmappedAttributes"

### ISSUE THREAD

**Issue by mp3duck** [reapit/foundations#7901]
We set an example property (heo220002 under WNK/Winkworth) to be a Penthouse.
We expected this to come back under the "type" field in the properties request (https://platform.reapit.cloud/properties/heo220002?embed=images), but it's coming back under "unmappedAttributes". Other property types come back under "type" as expected.

<img width="228" alt="image" src="https://user-images.githubusercontent.com/2575013/195296703-ac18678b-7e72-46f3-a588-e639983e22a2.png">

With "type" being empty:

<img width="131" alt="image" src="https://user-images.githubusercontent.com/2575013/195297150-85337e05-e6c3-4240-91b5-0e99c4779ff8.png">

Type field shown for a different property (heo220003)

<img width="95" alt="image" src="https://user-images.githubusercontent.com/2575013/195296963-13416d4a-213b-42ee-b29b-2c40e124e132.png">

**Comment by plittlewood-rpt** [comment]
Hi @mp3duck - this is by design. Please see [this documentation](https://foundations-documentation.reapit.cloud/platform-glossary#interpreting-department-data) for more information. When building the Platform one of the big challenges was being able to expose the plethora of customised attribute collections across our customer base. The documentation above will outline which fields you can expect to see in the structured type/style etc arrays, with the remainder appearing in the unmappedAttributes collection. The same behaviour will be seen in the applicants API also.
