### ISSUE TITLE
Company vs related Company List in landlord call returns address in different parameter

### ISSUE THREAD

**Issue by LouisaEvosite** [reapit/foundations#7936]
**Describe the bug**
A company address returned in a list of landlords appears in a different parameter from a normal company lookup.

**To Reproduce**
Look up a company using /companies/[companyID]. Address is in [address].
Look up a landlord using /landlords/[landlordID]. Any related companies appear in a list with their address under [primaryAddress]

**Expected behaviour**
For the related company's address in landlords/[ID] to appear under [address] too.

**Screenshots**
N/A

**Device (please complete the following information for web issues):**
N/A

**Additional context**
N/A

**Comment by LouisaEvosite** [comment]
Not sure if easier to make a separate bug but closely related- office IDs are not coming through in related companies when looked up through /landlords/[landlordID]

**Comment by plittlewood-rpt** [comment]
Hi @LouisaEvosite - this is intentional as the related contact model has to serve both contacts and companies. As there are generally more contacts than companies it is modelled on a contact (which can have multiple addresses, hence the naming conventions you can see)

I'm not sure I understand the issue with officeIds. As it's a separate issue please can you open another item?
