### ISSUE TITLE
Property Modified Webhook - "new" property contained "null"

### ISSUE THREAD

**Issue by stebrough** [reapit/foundations#7952]
**Describe the bug**
Property modified webhook call sent at 2022-10-19T08:06:13.897+00:00 for our app Integrated Interest Email Marketing contained "null" for the "new" property. This webhook is configured to ignore Etag updates.

**Expected behaviour**
"new" property contains the modified property record.

**Additional context**
Sensitive data emailed to sinfo@

**Comment by plittlewood-rpt** [comment]
Hi @stebrough - this is because the property was deleted or archived (archived in this case). As per the [documentation](https://foundations-documentation.reapit.cloud/api/webhooks#payload-schema) regarding the `new` property: _the new version of the entity, if applicable - this property will be null if a user has deleted or archived the entity._

I hope this helps

**Comment by stebrough** [comment]
Thanks @plittlewood-rpt
