### ISSUE TITLE
API: Recurring calendar appointments start and end times are not UTC

### ISSUE THREAD

**Issue by InspectREDev** [reapit/foundations#8043]
**Description**

We synchronise calendars with reapit via the api.
When we get a recurring appointment we get its start and end time as if they were UTC. For example:

      "start": "2021-05-11T11:15:00Z",
      "end": "2021-05-11T12:15:00Z",

However, when looking at the user's calendar in reapit, those appointments appear as being one hour later from 12:15 to 13:15.
This client is in the UK, so right now they do not have daylight savings, and it still shows (via API) as starting at 11:15.

**To Reproduce**

1. Create a recurrent appoinment in reapit. Frecuency: daily, Interval: 1, and no end of recurrence.
2. Do a get appointment API call.
3. Check the appointment is returned as starting one hour before the hour shown in the appointment.
4. NOTE I:  this may either be a bug in the API returned value (comes in as an hour ealrier), or the showing of the calendar (it shows it one hour later)
5. NOTE II: not sure if this is related, but the recurring appointments we get (4 in all) seem to have been created while daylight savings was on. At that moment "start time utc" would have correctly been an hour before what was shown in the calendar. But now it should return the same start time as the one shown in the UI.

**Expected behaviour**
The start time returned and the one showed in the calendar are the same.

**Screenshots**
![image](https://user-images.githubusercontent.com/117240508/199370501-8b621185-76ec-4305-93da-8f981fe42493.png)

**Device (please complete the following information for web issues):**

**Additional context**
The value returned from the api for the appointment shown in the screenshot is (removed some fields for brevity:
{
      "id": "SL...775",
      "created": "2021-05-06T10:35:56Z",
      "modified": "2022-10-05T12:04:40Z",
      "start": "2021-05-11T11:15:00Z",
      "end": "2021-05-11T12:15:00Z",
      "typeId": "AP",
      "description": "BREAK",
      "recurring": true,
      "recurrence": {
        "interval": 1,
        "type": "daily",
        "until": null
      },
      "cancelled": false,
      "followUp": {
        "due": null,
        "responseId": "",
        "notes": ""
      },
      "propertyId": "",
      "organiserId": "XXX",
      "negotiatorIds": [
        "XXX"
      ],
      "officeIds": [
        "XXX"
      ],
    }

**Comment by plittlewood-rpt** [comment]
Hi @InspectREDev - I'm not sure there is an easy answer to this unfortunately. As we do not duplicate the recurring entry the start time conversion is done based on the original appointment date, so in your example it is correct because 11th May IS in BST so you'd expect to see that hour difference here. It would be incorrect to suddenly have all the start times change when daylight savings came into effect (or vice versa)

**Comment by InspectREDev** [comment]
Hi @plittlewood-rpt. 
So if I understand correctly dates are sent in local time (acording to its first occurrence).
Will their serialisation be changed to have an offset (ie  UTC+00:00 or UTC +01:00) rather than being always sent as if they were UTC (Z suffix)?
Or should we ignore the Z suffix and always treat them as local time for UK (if the agency is in the UK)?
Also, does this mean that dates in other countries that use your product:
a) follow BST/UK time.
b) are UTC.
c) are always local respective to the office that creates them.
If c), do you have a way to get the time zone of the agency (officeID) for which we are trying to synchronise the calendars?

**Comment by plittlewood-rpt** [comment]
Hi @InspectREDev - customer databases store dates in local time (so our UK data centre is set to the local time here, the same for Australia etc). The APIs convert timestamps to UTC based on the data centre they are coming from, so you'll always see them in UTC with the conversion done based on the original start date. What you've said above is correct although I appreciate quite cumbersome. When we originally built the appointments API we did actually duplicate the recurring entities with new timestamps correct for the current DST setting for the time of year, however that caused a lot of confusion (and also performance problems) because you could see the same entity id multiple times in the same resultset with a different time, which isn't at all RESTful. Based on your points above is this a workable solution for you for the time being?

**Comment by InspectREDev** [comment]
Hi @plittlewood-rpt 
  Thanks for the explanation, had not thought about multiple appointments with the same id.
We will work as mentioned in my previous post,
You mention "for the time being". Is there a place we can check where you'd announce changes to the API?  Or do we just monitor "API Version" in https://developers.reapit.cloud?

**Comment by plittlewood-rpt** [comment]
Hi @InspectREDev - if we were to make a major change to an API that could be considered a breaking change, we'd send out relevant comms and it would be accompanied by a new version number so as not to break existing apps.
