### ISSUE TITLE
Joint landlords not flagged as an update on properties

### ISSUE THREAD

**Issue by asovdefixflo** [reapit/foundations#8118]
My company uses the Reapit API to import properties and landlords into our system.
Any changes that have been done to the properties in Reapit will be flagged as an update which we will be able to retrieve through the API endpoint.
The URL we use is: **/properties/?pageSize=100&sortBy=modified&modifiedFrom={modifiedFromUtc:o}&fromArchive=false**

**modifiedFromUtc** will be the last time we retrieved any properties from the api and anything that has changed in the meantime should be coming through next time we request properties.
However, when joint landlords are added or removed from a property we're able to retrieve it through the API using the last modifiedFromUtc so it seems that adding and removing joint landlords from the property is not flagged as an update on the property and therefore we're unable to naturally synchronise this into our systems.

Can you please look into this issue and let me know if this is something you can fix?

**Comment by plittlewood-rpt** [comment]
Hi @asovdefixflo - there is no landlord information other than the landlordId that gets surfaced from the properties API. As a result I wouldn't expect you to need to refetch the property if the only change being made is the addition/removal of a joint landlord. That said, I would expect that you might want to become aware of the this change from the landlords API instead, which is where the contact information for the landlord and any joint landlords is surfaced. This won't currently be reflected here either though but I just wanted to clarify your expectations. The reason the modified date is not being updated is because the CRM does not update the timestamp on the parent landlord record if the only change being made is to a joint landlord's relationship. I will raise this with the relevant team to see if we can get that addressed

**Comment by HollyJoyPhillips** [comment]
Internal reference PBI-4296

**Comment by HollyJoyPhillips** [comment]
Testing Notes: Joint landlord added and removed 'MKT210323' - modified date remains the same.

**Comment by HollyJoyPhillips** [comment]
Verified the landlord modified date is updated when a joint landlord is added/removed. @asovdefixflo if you have any issues, please comment or re open. Thanks.
