### ISSUE TITLE
RMBanner missing from YOM/RER Foundations Properties APIs

### ISSUE THREAD

**Issue by robchett** [reapit/foundations#8172]
**Describe the bug**
RMBanner is a custom field added to YOM/RER, it does not appear to be exposed via the Foundations API as it was in Webservice

**To Reproduce**
Steps to reproduce the behaviour eg:
Compare BRY220195 in RER with Webservice and Foundations

**Expected behaviour**
Se RMBanner = 14 in the Foundations API.

**Screenshots**
N/A

**Device (please complete the following information for web issues):**
API

**Additional context**
N/A

**Comment by AshDeeming** [comment]
Hi @robchett 
Please could you advise where this field is in AgencyCloud?

**Comment by NBareham** [comment]
@robchett @AshDeeming 
Here you go - it's in the Property > Marketing details > Premium dropdown. 
![image](https://user-images.githubusercontent.com/101395511/203998310-d82bb06b-7c3d-49fc-95f1-3d1af935443c.png)

**Comment by plittlewood-rpt** [comment]
Hi @robchett I have enabled this field so you can optionally request it in your API calls

Field name: pRMBanner

Include in your responses by using the `extrasField` query string parameter eg

`GET /properties?extrasField=pRMBanner` or `GET /properties/{id}?extrasField=pRMBanner`

Multiple extrasField parameters can be included in a single request providing you have been granted access to the custom data. The `extrasField` collection in the response model will include data for the fields _if_ it is explicitly set on the entity in the database, otherwise it will be omitted.

Finally, please allow around 15 minutes from receipt of this notification to allow the configuration changes to synchronise across the estate. If after this time you still cannot access this data, please get back in touch. Thanks
