### ISSUE TITLE
GET applicants endpoint not returning entities when passing in `name` parameter

### ISSUE THREAD

**Issue by stuhuntington** [reapit/foundations#8195]
**Describe the bug**
The GET /applicants endpoint is not returning entities when passing values for the `name` string parameter. The server responds with `{"message": "Internal server error"}`

This happens even when executing from the Docs swagger tool.

**To Reproduce**

curl -X 'GET' \
   'https://platform.reapit.cloud/applicants/?name=Joe Bloggs' \
   -H 'accept: application/json' \
   -H 'api-version: 2020-01-31' \
   -H 'Authorization: Bearer BearerToken'

**Specification**
- Project: Reapit.Services.Applicants
- Review query that is being executed against the database to determine if we can optimize

**Comment by HollyJoyPhillips** [comment]
This should be resolved now. If you are finding it's still an issue please reopen this ticket. Thanks.

**Comment by plittlewood-rpt** [comment]
Hi @stuhuntington - can you let me know if you get this error when retrieving the first page of results, or if performance gradually gets worse if you page through data? I've been running some tests and this is the behaviour I am seeing. I am looking at optimisations we might be able to do in the short term. Longer term we may need to alter our paging mechanism to address this more completely

**Comment by stuhuntington** [comment]
@plittlewood-rpt - I see the error when attempting to fetch any page or even not specifying any paging parameters in the query.

**Comment by plittlewood-rpt** [comment]
Thanks - is this happening on every single request or is the issue intermittent?

**Comment by stuhuntington** [comment]
Seems to be on every request - If you execute via reapit cloud swagger you get...

Failed to fetch.Possible Reasons:CORSNetwork FailureURL scheme must be "http" or "https" for CORS request.
--

Or if I send xhr myself....

```
Reapit Error @ Tue Dec 13 2022 11:56:49 GMT+0000 (Greenwich Mean Time): {"message":"502: Bad Gateway","extensions":{"response":{"url":"https://platform.reapit.cloud/applicants?name=Joe%20Bloggs","status":502,"statusText":"Bad Gateway","body":{"message":"Internal server error"}}}}
```

**Comment by plittlewood-rpt** [comment]
Thanks - would you be able to try it again in a few minutes and see if you see an improvement? I've altered one of the timeouts (it won't solve the fact the requests are slow but if we can stop them timing out it's a start)

**Comment by stuhuntington** [comment]
Problem still persisting at 12:57 13/12/2022

**Comment by plittlewood-rpt** [comment]
Hi @stuhuntington I've done some testing away from the APIs and used AgencyCloud directly and this has the same issue but isn't tied to HTTP timeouts. Running an applicant search for Joe Bloggs takes 92 seconds most of the time and this is down to the sheer amount of data in that system. The APIs have to respond in 30 seconds otherwise the request gets terminated. This is a hard limit which we are unable to change. We are looking at potentially introducing a different data store which allow for more efficient search capabilities but this is a big backend refactor and not something that is going to be introduced quickly. In the meantime I'll keep looking to see if there are other options. We might be able to be a bit smarter and only run a surname search if a single search term is provided which will be a lot quicker, but could also be a breaking change for some apps

**Comment by plittlewood-rpt** [comment]
Hi @stuhuntington the workaround here would be for us to allow you to specify what kind of name search you are running. The performance hit comes from the database having to amalgamate four fields (title/initials/surname/companyName) when running the search, which is the same problem that AgencyCloud has with huge volumes of data as is the case here. The workaround would involve a new query string parameter `nameType` that you could optionally pass in your `GET /applicants` request that gives you control over whether or not to do a surname/full/initials/company name search. When not passed, the existing behaviour is returned so we aren't introducing breaking changes eg:

`GET /applicants?name=Smith&nameType=surname` just search for applicant's whose contact's have a surname containing Smith

`GET /applicants?name=Pete&nameType=initials` just searches for applicant's whose contact's have initials/first name containing Pete

`GET /applicants?name=Smith & Sons&nameType=company` just searches for applicant's whose contact's are companies with a company name containing Smith & Sons

This would likely need to feed into the app that you are building so users could manage the search.

**Comment by plittlewood-rpt** [comment]
Hi @stuhuntington the change mentioned above was pushed out on Friday. I'm getting quite mixed results testing against SAU's data however so would be grateful if you could run some tests at your end and let me have your feedback. There's a number of differences with the indexes on the SAU database which I think is part of the problem here. It's something I'm speaking to our infrastructure team about to try and understand further. If you can run some tests using the new query string parameter I'd be grateful.

**Comment by stuhuntington** [comment]
Hi @plittlewood-rpt can I get back to you on the above. I am not sure that the proposed workarounds would be useful for our current requirements but I need to check with the product owner to see if we can modify/compromise on the UX to make this suggestion viable. Thanks

**Comment by plittlewood-rpt** [comment]
HI @stuhuntington I've been working with our infra guys today and we've made a couple of discoveries which are giving us something to work with. I've just reconfigured the applicants API to bypass the reader database server as it's possibly something to do with a specific reader that's causing the timeouts (yet to be determined). Can I ask you to test your app and let me know if you've started to get results back when name searching, and if so, if the behaviour is consistent?

**Comment by plittlewood-rpt** [comment]
Thanks - do you have the ability to run the same queries against SAV production data? If so I'd be interested if you get different results. The databases are on the same server and have a fairly similar volume of data in the tables concerned

**Comment by plittlewood-rpt** [comment]
Hi @stuhuntington  just to let you know I'll be picking this back up again - there's no easy answer to this unfortunately but we're looking at ways we might be able to optimize the underlying queries to make improvements

**Comment by plittlewood-rpt** [comment]
Hi @stuhuntington sorry for the delay on this. There are some changes being prepared for AgencyCloud and the underlying database that should eventually  resolve this problem but the rollout is very complex and requires planning due to database downtime etc (you'll be contacted in due course about this once it's a bit more ready so don't worry for now I just wanted to update you). In the meantime I've been doing some refactoring of the applicants API to squeeze as much out of it as I can, and I've completely reworked the contact name search mechanism which is just going through QA

**Comment by stuhuntington** [comment]
Thanks for keeping me updated 👍

**Comment by plittlewood-rpt** [comment]
@stuhuntington the refactor has just gone out if you want to run some tests when you get chance. It's still not amazing I'm afraid but it should cure the timeouts. I'm getting much more consistent results using the UAT dataset now.

**Comment by plittlewood-rpt** [comment]
There is potentially another update we can make, but I need to just look at if/how the name parameter is being used before deciding if we can implement it without a new version. Currently, when nameType is provided, we do a full wildcard search where the string could be anywhere in the database field (eg surname like *smith*). This prevents the database engine using indexes resulting in a much slower query. It's unlikely users will ever pass in 'part' of a surname, and so it's probably OK to run the query in the format surname like smith*, where the provided parameter is treated as the beginning of the phrase. This does allow the database to use the indexes and it makes another good improvement on your database. As this is a behavioural change though I need to just look at whether we need to version this update or not. I know you've previously said providing a type in your search query isn't really an option, and unfortunately matching all name fields is the best it's going to get now until the work in agency cloud is done. We are targeting that to be released within the next month or so but there are some infrastructure dependencies which could hold that up. Let me know your thoughts on performance following the latest round of updates when you can and we will go from there. Thanks

**Comment by rochellelevy** [comment]
@plittlewood-rpt / @HollyJoyPhillips this is a nice surprise. what was the implementation done on this?

**Comment by HollyJoyPhillips** [comment]
Hi @rochellelevy, it's not been done yet but it's been linked to this ticket #9273 (different endpoint but same issue). Rather than having both tickets open this one has been closed. The above ticket has been scheduled into our sprint starting 27/11.
