### ISSUE TITLE
Developer Analytics costs - friendly agent names

### ISSUE THREAD

**Issue by quigger** [reapit/foundations#8312]
In this ticket:
https://github.com/reapit/foundations/issues/8208
I was confused by the CLIENT names displayed.

I'm opening a new ticket to resolve the questions asked by @plittlewood-rpt in that (closed) ticket.

@plittlewood-rpt asked:
> "Hi @quigger is the main issue here that you can't see the name of the office group (so you can't translate "GSLG" into something meaningful?)"

Yes, that is the issue.

I can see CLIENT names like:
TEA-GSLG

but that isn't not very friendly.

Maybe this could be added:
TEA-GSLG (Slades Homes)

or similar?

**Comment by plittlewood-rpt** [comment]
@HollyJoyPhillips we should discuss this one. In a lot of cases the office group name won't mean anything to developers because it's not a brand name. In the case above, Team Association have multiple brands in their system so perhaps we should do something other than just expose the office group name here?

**Comment by HollyJoyPhillips** [comment]
Thanks @plittlewood-rpt. I've added a specification and moved to 'Near Term'. @quigger FYI

**Comment by quigger** [comment]
@AshDeeming @HollyJoyPhillips @willmcvay 

I do not see updated names here:
https://developers.reapit.cloud/analytics/costs

Is it waiting a production deploy?
