### ISSUE TITLE
Pagination element didn't allow setting the page

### ISSUE THREAD

**Issue by abrahamseni** [reapit/foundations#8324]
Currently, the Pagination element didn't allow setting the page outside the element.
So if I want to control the page like resetting the page to 1 when the page shown is 9, I need to manually input it in the input box.

**To Reproduce**
Steps to reproduce the behaviour eg:
Please check this sandbox: https://codesandbox.io/s/testing-reapit-elements-9zdbrz?file=/src/App.tsx:923-1031
Please note: we create the custom pagination element for testing purpose.

**Expected behaviour**
able to set page outside the pagination element

Reapit elements version: 3.9.2

**Comment by willmcvay** [comment]
@abrahamseni This is not a bug, rather the component works as intended. Pagination controls work by updating your pagination state - what you are describing is using a separate control to update the pagination component which seems an anti-pattern.

What I have done is to add an optional prop to render a forward and back to end button to the pagination component to allow users to fast forward to either the beginning or the end. This seems to be a preferable solution to your use case since the pagination controls are in a single place.
