### ISSUE TITLE
Why would we receive an under offer webhook for a completed property?

### ISSUE THREAD

**Issue by lcantrell79** [reapit/foundations#8459]
Our customer has contacted us because some of their completed properties have had their status change to under offer and our integration has imported them again.  The client is quite upset these properties were re-imported.

Please help us understand why this status was used if the property is completed and how to avoid this happening again. We imported the property based on the fact the status of selling.under offer was received via webhook.

Entity ID's 'CAI220317', 'CAI220352' received on 01/02/2023

The webhook json's received is attached
[AnthonyQuirk.zip](https://github.com/reapit/foundations/files/10664409/AnthonyQuirk.zip)

**Comment by plittlewood-rpt** [comment]
Hi @lcantrell79 - this has happened because it's the first time the webhooks pipeline has seen these properties and the status of each is "underOffer" (not completed). I'm picking this up internally to investigate further however as it appears webhook data was never seeded for this agent which is the underlying factor. In terms of protecting yourself against this, you _could_ ignore events where the diff is null/empty (as in both examples this was the case). The thing to bear in mind here though is that any properties added to the database with a status of under offer would result in you ignoring the event

**Comment by lcantrell79** [comment]
@plittlewood-rpt - What is seeding? The customer believes it's a mio issue and we do not want to ignore those webhooks.

**Comment by plittlewood-rpt** [comment]
Hi @lcantrell79 seeding is a process that needs to be run by us as part of the enablement of webhooks for a customer. As this was not run, the pipeline picked up the changes as 'new' properties which resulted in the hook being sent because the current status is underOffer. If seeding had been run, the properties in question wouldn't have been treated as new records so you would not have received these events. We'll discuss this internally to look at the best way of preventing a reocurrence
