### ISSUE TITLE
Full width ToggleRadio is no longer full width in @reapit/elements v3.10.3

### ISSUE THREAD

**Issue by simplychrisb** [reapit/foundations#8490]
**Describe the bug**
Full width ToggleRadio is no longer full width in @reapit/elements v3.10.3

**To Reproduce**
Steps to reproduce the behaviour eg:
1. Define a full width ToggleRadio using @reapit/elements v3.7.16, see attached screenshot.
2. Update to the latest version of @reapit/elements, currently v3.10.3 and the ToggleRadio is no longer full width see attached screenshot.

**Expected behaviour**
The ToggleRadio should be full width.

I've also attached a screenshot of what I believe to be the offending style: .el-toggle-radio-label.width overrides .el.toggle-full-width.width.

**Device (please complete the following information for web issues):**
 - Windows 10
 - Chrome Version 109.0.5414.120 and Edge Version 109.0.1518.78

**Additional context**
![ToggleRadio full width v3 7 16](https://user-images.githubusercontent.com/122380200/217565172-9219be49-a09c-4d46-b383-f6612144c713.png)
![ToggleRadio full width v3 10 3](https://user-images.githubusercontent.com/122380200/217565225-ecdae068-636f-46be-81e2-b7d05ae22cc2.png)
![ToggleRadio affected styles](https://user-images.githubusercontent.com/122380200/217566020-9ad95613-28eb-4b74-9985-2fc7ecfee85a.png)

**Comment by willmcvay** [comment]
@simplychrisb You are correct that the full width prop is no longer functional however, this is because it was removed from the Design System styleguide by our designer - v3.10.x brought Elements into line with a number of these updates. See the changelog here https://elements.reapit.cloud/?path=/docs/changelog--page We didn't remove the prop and the class component to avoid any runtime errors and we added a deprecation notice you should see in your console see https://github.com/reapit/foundations/blob/master/packages/elements/src/components/toggle/toggle.tsx#L56

Apologies if this requires a code change at your end, we do try and avoid breaking changes where possible but this is a balancing act with how the styleguide evolves.

**Comment by simplychrisb** [comment]
Hi @willmcvay, I completely forgot to check the changelog.
Version 3.10 does seem to include quite a few breaking changes which feels at odds with the minor version number increase so I'll probably stick with 3.9.9 for now.
Thanks

**Comment by willmcvay** [comment]
@simplychrisb We did consider a major version, it's just a bit of a grey area when it comes to Semver in the sense, yes there are some visual breaking changes, but there should be no functional breaking changes, no exports were removed from the project and we added deprecation notices ahead of the next major release. Thanks for the understanding.
