### ISSUE TITLE
Sandbox Data

### ISSUE THREAD

**Issue by itcdigitalcolin** [reapit/foundations#8525]
The data from the sandbox is poor - there are no or very few examples of pricing, full address fields, qualifiers, rooms, epc, lat/long etc. All valid properties have no images.

Attached is a raw printout from the feed, as gained from the Properties API call.

https://platform.reapit.cloud/properties/
client = 'SBOX'

[raw data.txt](https://github.com/reapit/foundations-code-examples/files/10731726/raw.data.txt)

**Comment by AshDeeming** [comment]
Hi @itcdigitalcolin 
The sandbox database can be updated & relevant records added in order to test the relevant process/requirement

This can be done via the Agents UI i.e. our Core software, AgencyCloud Developer Edition https://developers.reapit.cloud/desktop
or by using the post or patch functionality by swagger or another API client
