### ISSUE TITLE
Incorrect Location being passed using foundation API

### ISSUE THREAD

**Issue by Jejin** [reapit/foundations#8561]
Property ID BGO030017 on our Reapit has a postal code of W14 0BT but the foundation API is passing the location as EARLS COURT to the foundation API which is feeding our website. We have had similar issues in the past with with the below properties coming through as Earl's Court and we had to modify the code for these website listings to remove the location to fix the issue.

BGO220308	
BGO030017
BGO950017
https://www.druce.com/property-to-rent/BGO030017/2-bedroom-flat-rockley-road-brook-green-london-w14/

Can you please check and share your feedback ?

**Specificaton**
- Fix example given at source
- Log AgencyCloud ticket to see if they can set the correct area id whenever the lat/long changes on a property

**Comment by AshDeeming** [comment]
Hi @Jejin 
The areaID's can be obtained via the Areas endpoint; 
![image](https://user-images.githubusercontent.com/61687775/220901978-c896699d-3dcb-4af0-a3c3-01dd15fa03dc.png)

Please note that areas (generally used for matching) can be drawn/amended by the clients therefore the Location/Area may not match the address/postcode/long.lat

**Comment by tim-west** [comment]
Hi @AshDeeming, the issue seems to be that the incorrect `areaId` is being assigned to the property.

1. If you query the endpoint `/properties/BGO950017`, you will see the `areaId` returned is **EAL**.
2. If you then query the endpoint `/areas/EAL` you will see a list of coordinates returned under `area` that makes up a polygon.
3. When you plot the polygon on a map, you will see that the postcode **W14 0NH** and latitude/longitude for the property falls outside the defined polygon. See [demo](https://codepen.io/timwestdesigns/pen/VwGjJdg).

**Comment by ashindey12** [comment]
@Jejin the mentioned 3 properties are updated to point to correct location code, the issue was caused due to loccode not being updated correctly when property location is pinned to desired coordinates.
