### ISSUE TITLE
Missing Mapped Attribute

### ISSUE THREAD

**Issue by soilleir** [reapit/foundations#8624]
We have come across an issue which has forced us to put halt on major automation development we are working on.  We are a Reapit client (Rettie & Co) and not a 3rd party developer.  The issue is that Steading and Bungalow are not mapped attributes under styles.  I know that Bungalow is mapped under type but a Bungalow is of type House and Style Bungalow in a similar way that a Penthouse is of type Apartment and Style Penthouse.  So the way the attributes are mapped is inconsistent. 

As our attributes are heavily tided into our website we cannot easily change our config to make it fit with Reapit's Mapping so we urgently need Bungalow and Steading to be included in the style mapping.

**Comment by soilleir** [comment]
Hi @AshDeeming 

We have already reviewed this before posting and unfortunately it doesnt help us as there is nothing about how  to Patch or Post an unmapped attribute

**Comment by plittlewood-rpt** [comment]
Hi @soilleir firstly apologies I never got back to you via email. I've got a draft half written but it's been one of those weeks. Is it just Bungalow and Steading you're having problems with? If so we might be able to get these added fairly quickly for you.

Unfortunately it’s not possible to update the unmapped requirements through the PATCH endpoint, they were just added in a read-only fashion to facilitate the display of certain items on customer websites. 

The reason mapping attributes is so important is so that we can present a standard contract to all developers using the API, instead of how the old SOAP services used to operate where the contracts effectively ended up different between customer systems.

Thanks
Pete

**Comment by soilleir** [comment]
Thanks @plittlewood-rpt   i totally get the premise and ideally we would re configure our attributes to comply but our current set up is directly tied to our website so we can't.    If you can get bungalow and steading mapped in Style for us that would be amazing and allow us to proceed with the automation project for now.

 I've already set the ball rolling on an internal project to rationalise our attributes but it requires a lot of coordination and will take a while before its all in order due to the tie in with the website

**Comment by plittlewood-rpt** [comment]
Completely appreciate the point about the complexities around making any attribute changes. We don't tend to customise the lists anymore but as you've been with us for a while you're in the group of customers whose departments don't follow the standard setup. Let me get these two sorted then we've dealt with the immediate problem, then we can go from there.

**Comment by plittlewood-rpt** [comment]
These should be in place in the next 30 mins

**Comment by soilleir** [comment]
> These should be in place in the next 30 mins

@plittlewood-rpt  you are a legend.  Thank you
