### ISSUE TITLE
As a 'Negotiator', I want to see a Welcome Wizard when I first login

### ISSUE THREAD

**Issue by HollyJoyPhillips** [reapit/foundations#87]
Given that I am a 'Negotiator' and I have accepted the 'Terms and Conditions' on my first log in, I want to then see a welcome guide  

**Summary:** We already have a welcome wizard for a Developer when they first login , we now should include a welcome wizard in the Client Portal 

**Task**: To display a welcome guide after a 'Client'  'Accepts' the ‘Terms and Conditions’ modal 

**Similar to:** https://marketplace.reapit.cloud/developer/welcome

**Component**:  https://reapit.github.io/elements/?path=/story/helpguide--primary

- Should set a ‘reapit-first-login-complete’ cookie when final step has been completed 
- Content TBC. For now show 5 steps with lorem ipsum and a placeholder image

**Comment by tanphamhaiduong** [comment]
@HollyJoyPhillips I think the team need more input for this issue

**Comment by trankhacvy** [comment]
@willmcvay When a negotiator (client) logged in to portal, the `redirectRoute` will be `/client/installed`. Now I try to change  `redirectRoute` to `/client/welcome` (because I want client see the Welcome page when the first time they logged in)  but I get below error. I wonder do we need to add some configs for `redirectRoute` ?

<img width="865" alt="Screen Shot 2020-02-25 at 14 00 36" src="https://user-images.githubusercontent.com/8068926/75222626-3bbc4200-57d7-11ea-8783-77a75b007250.png">
