### ISSUE TITLE
Duplicate Entries in the PROPERTY_LETTINGS_WON_INSTRUCTIONS Table

### ISSUE THREAD

**Issue by Jejin** [reapit/foundations#8707]
Two entries in the PROPERTY_LETTINGS_WON_INSTRUCTIONS Table for the same transaction.  Both the entries have the values but a unique ID. 

19f7839ce3cf716750e4619ed462b542
095be0f908ba5b21e6eeb10d824d505a

Is this an issue with the data load and will be sorted in the next refresh ?

Thanks
Jejin

**Comment by plittlewood-rpt** [comment]
Hi @Jejin this is because the property status changed in this manner as you can see from the property journal (see below). It was a deliberate decision to NOT de-duplicate the data in the analytics schema so that it remained consistent with the data in AgencyCloud, but I can see why this might be seen as problematic. I'll keep this ticket open so we can discuss the possibility of deduplication in some tables, including this one. 

![image](https://user-images.githubusercontent.com/30798627/224353808-f36812ee-76d3-4c82-a2c4-8c280043db4f.png)

**Comment by plittlewood-rpt** [comment]
Can you give me an example of where you are seeing that only the last instruction transaction is maintained? Happy to have a look to confirm :) thanks
