### ISSUE TITLE
500 Internal Server Error - properties API

### ISSUE THREAD

**Issue by mc1906** [reapit/foundations#8746]
We are receiving sporadic 500 Internal Server errors from the properties endpoint of the Reapit data feed API.

The latest error we saw was at 06:00 15-03-2023

We have seen this error occur 5 times since 08-03-2023

The requested URL was;

https: //platform.reapit.cloud/properties/?
pageNumber=1&pageSize=100&internetAdvertising=true&embed=images&officeID=WkY&officeID=HES&officeID=PRE&officeID=MOR&officeID=ALL&officeID=HOESofficeID=AIN&officeID=SPT&officeID=LNH&sellingStatus=forSale&sellingStat us=underOffer&sellingStatus=reserved&sellingStatus=under0fferUnavailable&marketingMode=selling&marketingMode=sellingAndLetting

APP ID is : ac089ce7-427b-49d8-841a-4f0e5e7f519b

Our system makes a request to this endpoint on a daily basis to retrieve property data.

Can you please investigate and let us know what the issue was and if it has been fixed?

**Comment by plittlewood-rpt** [comment]
Hi @mc1906 can ou let me know which customer you are fetching data for?

**Comment by mc1906** [comment]
Hi,
the customer is BFL Homes Ltd / Venmore Group

**Comment by mc1906** [comment]
Hi, is there any update on this issue?

**Comment by plittlewood-rpt** [comment]
HI @mc1906 the API uses the same database that the customer's CRM uses so we can provide accurate real time results (without synchronising to a different repository to run the APIs which would introduce latency between users making changes and you being able to see them). As a result we do have situations where an intensive set of operations in the CRM could have an impact on the APIs. It's something we are aware of and discussing internally to come up with a solution, but no immediate remediation actions have been carried out yet

**Comment by plittlewood-rpt** [comment]
I note from your query that you are embedding images into your response. It's likely you will have less chance of your requests timing out if you fetch images separately. Requests have to complete within 30 seconds to prevent timeouts (this is a hard limit we cannot change). The embed mechanism will page through x pages of data before your results get returned which in the case of property images for a large number of properties could potentially be a pretty vast number of changes.

**Comment by mc1906** [comment]
Hi 
thanks for your reply. 

I can't see the 30 second timeout limit, or recommendation to fetch images separately referenced in your documentation.

Fetching images separately will increase API calls and require us to adjust our update routine which we will investigate.

If we implement this change, can you say definitively that this will avoid the internal server errors being returned from your system?

**Comment by plittlewood-rpt** [comment]
HI @mc1906 thanks for coming back to me and sorry for the delay in my response.

I've dug into this a bit more deeply and I can see from our logs you've had 36 "504" responses in the last 4 weeks and can also see why you are probably running into this problem. We have two data centres running our Foundations APIs. One in Europe (London) and another in APAC (Sydney). We do not copy data between regions due to legal requirements. Your requests are hitting our Sydney infrastructure which indicates your processing function is hosted somewhere near Australia and as a result the APIs are making a call back to Europe where the customer's data is located. This adds a reasonable amount of latency which can result in timeouts if the database is busy at the same time and takes longer to return data.

The immediate thing you could do based on the above is look at the feasibility of moving your application closer to Europe so that your requests hit the infrastructure there instead of in Sydney. You'll likely see a vast improvement in performance of API calls. That said, it's worth pointing out that we are in the middle of a project to alter how traffic gets routed to the data centres, and plan to start routing requests to the data centres closest to the customers' database rather than the data centre closest to the server that is actually making the request. This work is nearing completion and should be delivered soon.

It's worth noting that we can never definitively guarantee that there won't be an issue and that every request will succeed. It's a fairly common understanding that when developing anything the uses HTTP it's best practice to code for some kind of failure. Depending on the language you are using, there are various packages to help with this - as an example, the [Polly package](https://github.com/App-vNext/Polly) is great is you're using .NET

I note your point about the 30 second timeout, and will look at updating our documentation. The embed mechanism is there for convenience and makes no difference to how your consumption billing is calculated (you are billed as though you are making the requests yourself). This is [documented here](https://foundations-documentation.reapit.cloud/api/api-documentation#embedding-data)

We do also have a ticket logged in our Near Term column to look at seeing if we can improve the performance of the embed mechanism (we currently page sequentially, and there is a possibility we can page simultaneously) in #8427 - this is an exploratory ticket and any actions off the back of that need to be reviewed carefully.

I hope this update is helpful. Please let me know any feedback, particularly relating to reviewing where your application is hosted as that will give you the biggest benefit.

Thanks

**Comment by mc1906** [comment]
Hi,

Thank you for the reply and support with this issue, it's appreciated.

This particular application which makes the requets to your API endpoint "platform.reapit.cloud" is hosted in the UK on a dedicated host using a fixed UK registered IP address for egress traffic. - Can you provide the evidence why you think our system is hosted near to Sydney or is this determination based purely on where you are receiving the request?

As you will understand, we have no control beyond our data centre for how the DNS of your endpoint is resolved.

Our engineers have also run diagnostics from our host, and can see our host is resolving IP addresses registered to Amazon Web Services (which we assume is your infrastructure). The routing of requests to AWS regions as you describe would then be dependent either on configuration of the AWS environment, or with Route53 lowest latency - which are both out of our control. If it is a latency issue, could it be that your London Data Centre is giving higher latency (perhaps due to load) than Sydney?

We understand that HTTP requests are never guaranteed, and our system is configured to retry, however the failure rate is  currently exceeding our retry rate.

Do you have a timeline on your routing configuration changes?

Thanks again for your help,

**Comment by mc1906** [comment]
Hi Pete,

Thanks for the quick reply .. yes this particular application is hosted in a data centre in Nottingham, UK.

From your logs are you able to see the origin IP address for our requests hitting Sydney? (if so could you provide the first 2 octets?)

Thanks,
Matt

**Comment by mc1906** [comment]
Yes, that looks like our IP address which is registered in the UK, so seems like there could be a false positive on the geolocation;

https://lite.ip2location.com/united-kingdom-of-great-britain-and-northern-ireland-ip-address-ranges?lang=en_US  

I'll await your update.

Thanks again for your help.

**Comment by plittlewood-rpt** [comment]
HI @mc1906  - AWS have asked if you can run the following command from the server that's making the request to confirm which public resolver is being used when making your request:

```
Linux - dig +nocl TXT o-o.myaddr.l.google.com +short
Windows PowerShell -   Resolve-DnsName o-o.myaddr.l.google.com TXT
Windows command prompt - nslookup -type=txt o-o.myaddr.l.google.com
```

Please can you do this when convenient and let me know the result? They've also asked me to turn on some additional logging so we'll have more detail the next time this happens.

**Comment by plittlewood-rpt** [comment]
Thanks @mc1906 (un)helpfully this hasn't occurred again since I enabled the extra logging as suggested by AWS, but I keep checking regularly.

**Comment by plittlewood-rpt** [comment]
Hi @mc1906 this still has not reoccurred. Can you confirm you're seeing 100% success rate at your end now?

**Comment by mc1906** [comment]
Hi @plittlewood-rpt,

On the 23rd March, we reduced the number of properties we request 'per page' from 100 to 75 to reduce the size of the payload - since we did this we have not seen any errors.

**Comment by plittlewood-rpt** [comment]
Thanks for confirming these changes. I'll close this item down in that case. The DNS logging is enabled so if we do see situations where your app randomly gets routed across to our infrastructure in Sydney we can look into it further. Thanks
