### ISSUE TITLE
Property status changed to Market appraisal 

### ISSUE THREAD

**Issue by ErnstHavenga001** [reapit/foundations#8770]
We currently report on property status' changed to market appraisal in a given date range. We don't appear to be able to do this at the moment in the data warehouse.

![MarketAppraisals](https://user-images.githubusercontent.com/128135294/226880807-b48877b8-e631-486a-bac8-0b3d8668edb4.png)" from the Journal entries.

**Comment by plittlewood-rpt** [comment]
Hi @ErnstHavenga001 

The existing PROPERTY_SALES_VALUATIONS and PROPERTY_LETTINGS_VALUATIONS model views in the analytics schema are largely based on journal data and should allow you to achieve what you are trying to do. Can you confirm if you've reviewed the data in these tables before we look into this further?

Thanks
Pete

**Comment by ErnstHavenga001** [comment]
@plittlewood-rpt 

Thank you very much for your reply.

If I look at the PROPERTY_SALES_VALUATIONS table, I only see 277 rows under Column VALUATION_DATE for 2023 so far. The Reapit report we are trying to duplicate is producing 4180 rows.

![Market_Appraisal Report](https://user-images.githubusercontent.com/128135294/227858343-4ebd523b-2918-4424-9e72-c2e09afa158e.png)
![Market_Appraisals](https://user-images.githubusercontent.com/128135294/227858347-62766aa8-5c71-40f8-8d9f-d2c9099091e6.png)
![VALUATION_DATE](https://user-images.githubusercontent.com/128135294/227858353-8a1c2976-728c-4e02-8a19-8df9906265aa.png)

**Comment by plittlewood-rpt** [comment]
Hi @ErnstHavenga001 altering the valuations view is probably the wrong thing to do here as it's not designed to cater for properties going from a status past Market Appraisal (eg from Under Offer back to Market Appraisal) as this doesn't make sense in the context of the lifetime of a property. We recommend for subsequent sales that an existing property record be duplicated rather than reused, which I suspect is your issue here.

Having said that, I think it would be useful for us to expose a simple view of property status changes so you can report on this how you wish. This view would simply contain the property id, the old status and the new status, along with the date and time of when the change took place. This should give you the best of both worlds.

Does this sound like it will suit your use case? Apologies for the delay coming back to you

**Comment by ErnstHavenga001** [comment]
@plittlewood-rpt thank you very much. It does sound like it will suit the use case.

**Comment by plittlewood-rpt** [comment]
Thanks. I've logged a new ticket, reference above where you can track this.
