### ISSUE TITLE
Property status change to Exchange

### ISSUE THREAD

**Issue by ErnstHavenga001** [reapit/foundations#8771]
We currently report on property status' changed to Exchanged in a given date range. We don't appear to be able to do this at the moment in the data warehouse.

![No of units sold](https://user-images.githubusercontent.com/128135294/226902862-3dde4909-1644-4eab-b20d-e3f2581b2a41.png)

**Comment by ErnstHavenga001** [comment]
@plittlewood-rpt

Thank you very much for your reply.

If I look at the PROPERTY_SALES_EXCHANGES table, I only see 3 rows under Column EXCHANGED_DATE for 2023 so far. The Reapit report we are trying to duplicate is producing 324 rows.

![Nr of Units Sold Report](https://user-images.githubusercontent.com/128135294/227864339-41a38951-f000-4549-bd27-ec40bd9daf79.png)
![Nr of Units Sold](https://user-images.githubusercontent.com/128135294/227864343-19751a2d-ddd6-45bb-989d-5178f044d82f.png)
![EXCHANGE_DATE](https://user-images.githubusercontent.com/128135294/227864614-f5271354-b9cc-4d10-b68a-fbd86bd7b424.png)

**Comment by plittlewood-rpt** [comment]
Hi @ErnstHavenga001 I think I've got to the bottom of this one. Whilst there was a minor bug in the model generation behaviour (I've resolved this and your data should update within the next hour or so), the exchanges view only includes properties which are still in the Exchanged (or Completed) status. This is because a subsequent sale should normally be registered as a new property on your system.

The equivalent report in AgencyCloud is
![image](https://user-images.githubusercontent.com/30798627/236461917-48710781-4fb8-4d3a-af83-b93b83c6e109.png)

Once the analytics schema refresh job has run, I'd be grateful if you could review this and come back to me. Many thanks

**Comment by MatthewGoddard** [comment]
Thanks @plittlewood-rpt

**Comment by ErnstHavenga001** [comment]
Thank you very much @plittlewood-rpt<https://github.com/plittlewood-rpt>
