### ISSUE TITLE
Company not returned through API

### ISSUE THREAD

**Issue by matt-fixflo** [reapit/foundations#8860]
**Describe the bug**
There is a company that is viewable in the front end that we are not able to get when querying the API.  It will be a setup/configuration issue but we have been advised to ask it on here.

**To Reproduce**
Sending an API request to /companies/LHO21025096 for LOC-GLAS returns a 404 response.

Also when searching companies with ?fromArchive=true&id=LHO21025096  returns no data.

**Comment by plittlewood-rpt** [comment]
Hi @matt-fixflo this is happening because the company is associated to office LOH (Linley & Simpson Head Office) which for some reason is not part of the LOC-GLAS office group, so the entity gets filtered out. The customer would need to alter the office group to resolve this issue, OR they can alternatively assign another office to the company that is part of the LOC-GLAS group.
