### ISSUE TITLE
Urgent - 429 Too Many Requests

### ISSUE THREAD

**Issue by raymond2323** [reapit/foundations#9193]
We went live with a large client yesterday and it seems now the API is giving us problems - we are getting this response, for most requests now - Is this something you can look at as currently the client isn't able to use system? 

429 Too Many Requests

**Comment by raymond2323** [comment]
I think because you are not processing the requests, all calls are retrying and retrying (as they are jobs and will retry) so it's only going to increase the number of calls we are making towards the API. Can you adjust any rate limiter for us?

**Comment by plittlewood-rpt** [comment]
Hi @raymond2323 - this appears to be occurring because you are exceeding the request concurrency limit as detailed here: https://foundations-documentation.reapit.cloud/api/api-documentation#rate-limits

Please can you review this documentation and ensure your app is waiting for requests to complete before firing subsequent requests to remain within the documented limits. Please let us know if you need any further assistance

**Comment by plittlewood-rpt** [comment]
Hi @raymond2323 do you need any more assistance with this? Many thanks

**Comment by raymond2323** [comment]
We are building something on our end to address this. Will let you know if we get any further questions. You can close this ticket.
