### ISSUE TITLE
Update Swagger documentation to correctly indicate negotiatorIds is required

### ISSUE THREAD

**Issue by robchett** [reapit/foundations#9206]
**Describe the bug**
The applicants API requires negotiatorIds to be passed in the POST payload, however the Swagger documentation does not indicate that this is a required field. We should address this

**Specification**
- Project: Reapit.Services.Applicants
- Ensure CreateApplicantModel.NegotiatorIds is marked as [SwaggerRequired]
- Ensure any other mandatory properties are also marked as required. OfficeIds for example may have the same problem

**Comment by plittlewood-rpt** [comment]
Hi @robchett this has always been a required field and this should be reflected in the swagger documentation so we will address that as soon as we can. I've just checked the history around the validation on that endpoint and there haven't been any changes since March 2023 when we correct an issue with the validation error messages as part of #8375

**Comment by robchett** [comment]
Thanks Pete, you're are correct, we stopped including the Neg by mistake in May and the update had only just now got to testing. Thanks for looking into correcting the documentation.
