### ISSUE TITLE
add field in Contacts window?

### ISSUE THREAD

**Issue by buonzz** [reapit/foundations#9255]
**Summary**
Similar to "Marketing Consent" field, wherein a user can toggle the contact's preferences, We would like to also add our own opt-in/opt-out field specific to our integration . We would like to have this saved in the metadata field of that contact being edited by the user in Agency Cloud.

**Question** 
How do we customize the Contact window to add our custom field, so that Agency Cloud users can toggle it?

**Detail and or supporting links and screenshots**
![2](https://github.com/reapit/foundations/assets/946233/4679f338-58de-4f01-b71a-e1d8e308c2f3)

**Comment by AshDeeming** [comment]
Hi @buonzz 

Certain screens in AgencyCloud can be replaced via the Desktop API - see the below:
https://foundations-documentation.reapit.cloud/api/desktop-api#desktop-types

In order to add an additional input field, your app would need to replace the screens functionality & included your required field or create an app that stores this additional detail only. https://foundations-documentation.reapit.cloud/api/desktop-api#overview

**Comment by buonzz** [comment]
just to clarify, in my app settings I need to configure this:
![2](https://github.com/reapit/foundations/assets/946233/eae8c45d-3c4f-4f91-a42d-e16faecb1458)

 so that the "Apps" menu will appear on the Contact screen?

then i could use 

```
let cntCode = (window as any).__REAPIT_MARKETPLACE_GLOBALS__;
```

in my app to retrieve the contact code?
im trying to verify if im heading the right direction
