### ISSUE TITLE
Include 'Charging Period' column on billing 

### ISSUE THREAD

**Issue by HollyJoyPhillips** [reapit/foundations#9318]
**Summary**: To ensure accurate invoicing we should include a charging period column on the monthly billing spreadsheet

**Task**:
- Add 'Invoice Period' column
- Should be populated for annual fees (application listing & developer registration) in the format 1st Jun - 31st May 24
- Should be populated for monthly fees in the format 1st Jun - 30th Jun 23

**Route**: /developers/costs/

**Comment by plittlewood-rpt** [comment]
@HollyJoyPhillips  can we discuss this. There's already a charging period column on the spreadsheet and it feels like it would make sense to actual roll the annual subscription charge into the next months billing (which is more complex but more accurate otherwise accounts need to remember to bill something in the upcoming month)

**Comment by HollyJoyPhillips** [comment]
Hi @plittlewood-rpt I'm happy with that approached and agreed it with Partnerships :)
