### ISSUE TITLE
Appointment won't change to "Followed Up" when the "followUp.responseId" have empty string value

### ISSUE THREAD

**Issue by ss-dimasm** [reapit/foundations#9349]
**Describe the bug**
Appointment is not mark as "Followed Up" when we're not adding the "followUp.responseId" proper value to the PATCH payload, but in AC is possible to mark the appointment to "Followed Up" without set the proper "followUp.responseId" value.

**To Reproduce**
Steps to reproduce the behaviour eg:
1. Open AC and create one appointment (untick the Followed up tick boxes)
2. Send the attached payload A with patch to appointment endpoint
3. Close the pop-up in AC, hit refresh, and open the same appointment in AC
4. Follow Up tick box already untick and follow up due doesn't have value, but the Followed up is not ticked too
5. Send the attached payload B to the single appointment service with PATCH
6. Close the popped-up in AC, hit refresh, and open the same appointment in AC again
7. now Followed up is ticked

**Expected behaviour**
Because in AgencyCloud is possible to have the ticked "Followed Up" without having "followUp.responseId" data, then the appointment service should able to have the same behaviour like the AC does.

**Payload A**
```json
{
  "followUpOn":null
}
```

**Payload B**
```json
{
  "followUpOn":null,
  "followUp": {
     "responseId":"random-response-id"
   }
}
```

**Specification**
- Project: Reapit.Services.Appointments
- Work through the above and replicate. It's likely there is some logic in this service that governs whether or not the Follow Up checkbox is ticked. The API clears this box when followUpOn is set to null but from the above it looks like there is a hole in the logic somewhere. 
- Once replicated work through appropriate bug resolution

**Comment by plittlewood-rpt** [comment]
HI @ss-dimasm this looks like a bug in the UI behaviour in AgencyCloud. I'm just waiting to speak to one of the developers in the respective team about it to try and debug the problem

**Comment by plittlewood-rpt** [comment]
Hi @ss-dimasm this is indeed a strange UI bug in AgencyCloud which I'll get logged. The followed up tickbox on the appointment window is only meant to be checked if there is either a pre-set option selected OR something stored in the follow up notes. The state of the checkbox is getting stuck somewhere in memory when you check it without entering this information in the UI, and you'll find that if you fully close the application and relaunch it and look at the appointment again it's now unticked, which is effectively what you're seeing with the API update.

Some may argue this behaviour is correct, as no follow up data has actually been set, so the appointment hasn't 'actually' been followed up. For this reason I may get some push back that this isn't actually a bug but by design, but nevertheless I'll send it over to our Agencycloud development team.

The only real option for you developing against the API is to set either the followUp.responseId or followUp.notes (or both)

**Comment by plittlewood-rpt** [comment]
@ss-dimasm I have logged an internal bug ticket ref ACT-485. For information, the correct behaviour is that the followed up checkbox should never be ticked when no pre set feedback or notes are entered, so it's worth considering that this will likely be how this issue is addressed, rather than being able to mark an appointment as followed up without this information being set.
