### ISSUE TITLE
Updates to the config service

### ISSUE THREAD

**Issue by HollyJoyPhillips** [reapit/foundations#9473]
This has been re-tested but an issue still is occurring. See steps below. 

Steps 10 and 14 are the issue, and they're basically the same thing but have included them both because there is a very slight difference, even though there is probably only one root cause.

  1. Using the setting TEST-NUMBER-RANGE-MOB, which has a default value of 5

 2. Set the value to 6 at organisation level (orgId = 1)

 3. Get the value for the organisation, should return { value: 6, level: organisation } - PASS

 4. Get the value for a franchise, should return { value: 6, level: organisation } - PASS

 5. Set the value to 7 at franchise level (orgId = 1, franchiseId = 2)

 6. Get the value for the organisation (orgId = 1), should return { value: 6, level: organisation } - PASS

 7. Get the value for the franchise (orgId = 1, franchiseId = 2), should return { value: 7, level: franchise } - PASS

 8. Get the value for an office (orgId = 1, franchiseId = 2, officeId = 3), should return { value: 7, level: franchise } - PASS

 9. Get the value for a user (orgId = 1, franchiseId = 2, officeId = 3, userId = 4), should return { value: 7, level: franchise } - PASS

 10. Set the value to 7 at office level (orgId = 1, franchiseId = 2, officeId = 3) - should be a no-op as it matches the inherited value

 11. Get the value for the office (orgId = 1, franchiseId = 2, officeId = 3), should return { value: 7, level: franchise } - FAIL: actually returns { value: 7, level: office }, suggesting that the POST in step 10 was not treated as a no-op

 12. Set the value to 6 at office level (orgId = 1, franchiseId = 2, officeId = 3)

 13. Get the value for the office (orgId = 1, franchiseId = 2, officeId = 3), should return { value: 6, level: office } - PASS

 14. Set the value to 7 at office level (orgId = 1, franchiseId = 2, officeId = 3) - this time the explicitly set office-level value should be deleted as we are setting to the same as the inherited value

 15. Get the value for the office (orgId = 1, franchiseId = 2, officeId = 3), should return { value: 7, level: franchise } - FAIL: actually returns { value: 7, level: office }, suggesting that the POST in step 10 did not delete the value
 
**Note:** Tested through Swagger.

**Comment by bashleigh** [comment]
no 10: created a franchise with config value of 7 and attempted to create an office value with a value of 7. Franchise value was returned. Would you prefer a different response status instead of the current payload of the previous level? Could return a 422 instead of 201 with previous level.

See outcome below, sending request for officeId creation with value of 7 (matches franchise) results in the franchise value being returned. See the level in the response payload.

<img width="1392" alt="Screenshot 2023-07-27 at 10 58 36" src="https://github.com/reapit/foundations/assets/11574250/f61d3895-10cd-4020-9b84-a4abf8913258">

Just to clarify, this is a query from after the request. No office value was created
<img width="1019" alt="Screenshot 2023-07-27 at 10 59 23" src="https://github.com/reapit/foundations/assets/11574250/b7892ef8-2fee-4e89-97ee-e15e6a69a612">

**Comment by bashleigh** [comment]
12-14: 
Managed to create an office value with the value of 6, which returned an office level config with value of 6. 
Setting the value to 7 deletes the office value of 6 and returns franchise
<img width="1392" alt="Screenshot 2023-07-27 at 11 06 30" src="https://github.com/reapit/foundations/assets/11574250/5ff612b6-790d-4216-8158-adfef9123d02">

<img width="1392" alt="Screenshot 2023-07-27 at 11 06 07" src="https://github.com/reapit/foundations/assets/11574250/7500528a-8ea5-4f35-82dd-10dafd7af6f1">

**Comment by HollyJoyPhillips** [comment]
Confirmed with NT - working as expected.
