### ISSUE TITLE
Setting client account in order to use POST/Transactions/supplierInvoice endpoint

### ISSUE THREAD

**Issue by katedeedman** [reapit/foundations#9642]
Hey Reapit,

We have a shared client hoping to use the POST/Transactions/supplierInvoice endpoint to sync invoices from Fixflo into Reapit. When looking at their RPS, we've noticed that they don't have the Client Account field within the Landlord Financial Details modal (screenshot below). 

![image (57)](https://github.com/reapit/foundations/assets/117754771/01ba2905-56fb-46ea-ab79-277a4c82f879)

When we built the new configuration using the new endpoint, we did face a few errors in testing when this field wasn't set. So I wanted to confirm:

- Does this field need to be set in order to use the POST/Transactions/supplierInvoice endpoint?
- Why do some clients have this field and others not? Would be good for us to know so we can make a plan if other agencies want to set it up but don't have the Client Account field. 

Many thanks in advance! 

Kate 
(Lead Product Manager at Fixflo)

**Comment by AshDeeming** [comment]
Hi @katedeedman 
This functionality is only enabled for client using our Client Accounts solution.

**Comment by katedeedman** [comment]
Hello!

Just chasing up this one. If someone could let me know if this means the
client can't use the POST/Transactions/supplierInvoice endpoint, that would
be great.

Thanks!

-Kate

**Comment by AshDeeming** [comment]
Hi @katedeedman 
If a client is not setup/enabled for Client Accounts within AgencyCloud - They will not have nominal accounts setup & therefore will be invalid.

**Comment by katedeedman** [comment]
Thanks for confirming, Ash!

**Comment by plittlewood-rpt** [comment]
HI @katedeedman 

I've checked in with our client accounts team and the option to set the account only shows if the customer has more than one primary client account configured in their system which is why the customer concerned can't see it. That said, it does look like we've got some handling for this scenario in the transactions API so I'll look into why this isn't working as we'd expect ASAP and come back to you.

Thanks

**Comment by plittlewood-rpt** [comment]
HI @katedeedman looking at this, and re-reading the above, you've not mentioned if you've actually had an error or not. There is handling in the API for the scenario where there's only a single account set so you should find you can post supplier invoices without an issue. Can you confirm if you've actually had a problem here (or if this was just logged out of curiosity to confirm the behaviour?). If the former, are you able to provide an example as I've run through the API endpoint code against their system and it's behaving as I'd expect.

**Comment by katedeedman** [comment]
Hey Pete,

This was logged just out of curiosity when the client raised that they
don't have that field. We wanted to double check after the discussion on
this ticket - https://github.com/reapit/foundations/issues/9008
<https://github.com/reapit/foundations/issues/9008>

I'll ask one of our devs to have a go and let you know how we get on!

-Kate

**Comment by plittlewood-rpt** [comment]
Pending 3rd party feedback

**Comment by katedeedman** [comment]
Thank you! If you wouldn't mind keeping it open for another day or two,
that would be great. Just in case we have any follow up questions.

I've asked one of our devs to look at it tomorrow.

-Kate

**Comment by plittlewood-rpt** [comment]
HI @katedeedman are we good to close this down?

**Comment by katedeedman** [comment]
Hi Pete,

I caught up with one of our developers last night about this. I wondered if
you could point me in the direction of where the single primary account is
configured in our sandbox?

Thanks!

Kate

**Comment by plittlewood-rpt** [comment]
Hi Kate

There's actually 2 primary accounts configured in the Developer Edition. You can see them if you open up a Landlord and click the little pencil icon next to the Financial header

![image](https://github.com/reapit/foundations/assets/30798627/ad857084-b2a7-4c37-827b-d4de11ae6ec5)

Hope this helps - let me know if i've misunderstood your question.

Thanks
Pete

**Comment by katedeedman** [comment]
Hello!

Sorry, I wondered where it's set if they don't have that Client Account
field?

Our Sandbox set up reflects your screenshots but struggling to see how it's
set for those users that don't have that field.

Thanks!

-Kate

**Comment by plittlewood-rpt** [comment]
Hi Kate

Sorry I think I misunderstood possibly. When only a single primary account is configured, the system infers it's use rather than explicitly storing it. The API does the same thing and explicitly checks how many primary accounts are configured when storing a supplier invoice in the database. If there's only one, we use it (as this is what AgencyCloud does) and it doesn't require setting against the landlord at all. If there's more than one, that's where we need the branch configure the correct primary account against the landlord, and so they see the additional option on the screen shown above.

Does that answer the question a bit better? Let me know if not :)

Thanks

**Comment by plittlewood-rpt** [comment]
Hi Kate - I'll close this item down for now as I think you should have all you need. Just let me know if not. Cheers
