### ISSUE TITLE
Cannot find a property from a customer via the API

### ISSUE THREAD

**Issue by brunosabenca** [reapit/foundations#9681]
**Describe the bug**
Property is not being returned when searching for it by address.

**To Reproduce**
The client ID is YOM-GCHS
1 - Searching for property by address
2 - The property is not included in the results

BUT when calling the endpoint /properties/QLF210199 the property is returned successfully

**Expected behaviour**
The API should include the property in the results.

**Device (please complete the following information for web issues):**
 - API integration

**Additional context**
Ticket submitted by Goodlord regarding the API integration.

**Specification**
- This is likely a data issue, possibly compounded by office group settings although Ash has checked this already. Run tests locally

**Comment by AshDeeming** [comment]
![image](https://github.com/reapit/foundations/assets/61687775/d9307cac-ddee-4ab4-899e-e6e9446b99ab) - OfficeID QLF is within officeGroup YOM-GCHS

**Comment by andytait** [comment]
Hi @AshDeeming,

Is there an update on the issue flagged by @brunosabenca?

Thanks!

**Comment by plittlewood-rpt** [comment]
@brunosabenca please can you advise what parameters you are passing in your call to GET /properties? I am searching by just the street name (line 1) and the property is being returned. Thanks

**Comment by mikefox** [comment]
@plittlewood-rpt The property is returned in the search results but it's filtered out by our post processing logic. The reason it's filtered out is because we fetch the `_embedded` resource on the property and then check the `['landlord']['related']` fields of this embedded resource. We expect the value of the `related` field to be an array of landlord contacts but for this particular property the value of `related` is an empty array. This is not normally the case as we would see this a lot more often in our system. Can you provide any insight on why this particular property has this configuration?

**Comment by mikefox** [comment]
@plittlewood-rpt Would appreciate any insight on this, thanks.

**Comment by RWilcox-Reapit** [comment]
Hi @mikefox 
This property should be retrievable now. It was caused due to bad data in the address line fields for that specific property which I've corrected.
Thanks
