### ISSUE TITLE
PROPERTY_SALES_EARNED_FEES Fee not correct

### ISSUE THREAD

**Issue by jessieip** [reapit/foundations#9720]
Hi there,

We hope to get the fee split data and below is the fee split box at Reapit:

![image](https://github.com/reapit/foundations/assets/84917225/b279266b-9980-4396-97af-e2262de1fce1)

It should be the fee column at PROPERTY_SALES_EARNED_FEES but Pete has advised the FEE column isn't being set correctly. That's why I raised a ticket. When I view property code = MNS220159, the FEE column is NULL.

Many thanks,
Jessie

**Comment by matt-austin-andrews** [comment]
Hi there,

Is there any update? I understand it will take several months but i'm curious the latest status.

Thanks,
Jessie Ip

**Comment by plittlewood-rpt** [comment]
Hi @matt-austin-andrews this item is in the current sprint so will be looked at before Friday next week (you can see the sprint dates on the Github Projects page). For information this only affects fee splits that are added as a percentage rather than a fixed value. You'll find that if you change the fee split and then type £1347.50 into the fee box and then Save that it will resolve the issue. It looks like there is an issue specifically when handling splits stored as a percentage - of which there are very few - that we need to resolve

**Comment by matt-austin-andrews** [comment]
Thank you for the update Pete and I can see the sprint date at projects :)

**Comment by plittlewood-rpt** [comment]
This should now be resolved. Any issues let me know

**Comment by matt-austin-andrews** [comment]
> This should now be resolved. Any issues let me know

yes, it works, thank you Pete :)
