### ISSUE TITLE
Making HEAD request to document download URL now returns 502

### ISSUE THREAD

**Issue by garrym** [reapit/foundations#9861]
**Background context**
We want to find the size of documents before using them in our application, so we have been making a `HEAD` request to the download endpoint and reading the `Content-Length` header.

CURL example:

```
curl --location --head 'https://platform.reapit.cloud/documents/[removed]/download' \
--header 'Accept: application/octet-stream' \
--header 'reapit-customer: [removed]' \
--header 'api-version: 2020-01-31' \
--header 'Authorization: Bearer [removed]'
```

If the request fails we resort to downloading the entire file via a `GET` request on the same URL and checking the file size locally instead, which isn't ideal.

This has been working fine and we've not had any errors. At around 08:30am this morning (27/09/2023) this call started to fail and we are now receiving 502 HTTP status code responses for this request. We are no longer able to get the size of the file, and are having to fall back to downloading the entire file each time.

It's worth noting that for the document we're using, the `GET` request works fine and downloads it. I can provide the document ID if required.

**Specification**
Not sure what to add here.

**Specification**
- Project: Reapit.Services.Documents
- This seems to be specific files causing the problem, so check the logs for these events and use one of them as an example for troubleshooting

**Comment by plittlewood-rpt** [comment]
HI @garrym this is happening because there is currently no proper support for HEAD requests in the API. The file was still being transferred into memory which was causing a memory error. I've got a PR up to add proper support for HEAD requests on the download endpoint which will resolve this and it should get merged early next week. The issue will only occur when trying to download files over a certain size which may perhaps be why it looks like it's only just started occurring - I've checked our logs and it's been occurring sporadically for quite some time, and always on specific files.

**Comment by plittlewood-rpt** [comment]
Hi @garrym the update to resolve this has just gone out to production. I'm monitoring our logs at this end to make sure the 502s drop off, but I'd be grateful if you could feedback once you've had chance to verify the fix at your end also. Thanks

**Comment by garrym** [comment]
Thanks @plittlewood-rpt I'll get the team to verify over the next few days and get back to you.

**Comment by plittlewood-rpt** [comment]
@garrym just checked the logs this end and there's been no 502's since the update went out and I would have expected to see at least one or two since then based on usual traffic patterns, so hopefully that's a good sign!
