### ISSUE TITLE
EPC document or URL attached

### ISSUE THREAD

**Issue by matt-austin-andrews** [reapit/foundations#9916]
Hi there,

We plan to display a metrics about "No EPC document" at BI tools (Looker). The users request to check whether it has EPC document/URL upload to Reapit or not.

Here's the screenshot at Reapit:
![image](https://github.com/reapit/foundations/assets/88837586/55fb84eb-fe2b-4832-aa65-4ee795e5b6d6)

Currently, I can't see this field is available at Reapit by viewing PROPERTIES at Snowflake. Can you add a column such as "Certificate(Yes/No)", "Certificate No", Start Date", "End Date", "Supplier"?

Many thanks,
Jessie

**Specification**
- Project: Analytics Schema
- This data is incorrectly being presented in the PROPERTY_LETTINGS_CERTIFICATES view model. To resolve:
- Add new PROPERTY_SALES_CERTIFICATES view model that is a duplicate of the lettings one but with only certificates relating to sales (or dual marketed) properties
- At some point in the future we can then remove the SALES certificate data from the lettings view model (comms required)

**Comment by plittlewood-rpt** [comment]
Hi @matt-austin-andrews you'll currently find this data (incorrectly) in the PROPERTY_LETTINGS_CERTIFICATES view. I think rather than renaming the view which would be a breaking change, the best thing to do here is to add a new view model specifically for EPC certificates (something like PROPERTY_EPC_CERTIFICATES), OR separate certificates for Sales properties out into a PROPERTY_SALES_CERTIFICATES view model. We'll discuss this on our refinement session later today.

**Comment by matt-austin-andrews** [comment]
Hi Pete,

Thank you for the update. I will get in touch at the next few weeks regarding the new view. 

Jessie

**Comment by matt-austin-andrews** [comment]
Hi there,

Considering the ticket was created at the beginning last month, any update news? Will you create a new view model?

Kind regards,
Jessie

**Comment by plittlewood-rpt** [comment]
HI @matt-austin-andrews yes the specification has been updated and this is now in our Near Term column and will be picked up in line with our development processes. We are going to add a new view and at some point in the future will remove the incorrect data from the lettings certificates view
