### ISSUE TITLE
Unable to inculde bullet points in "Reapit Summary"

### ISSUE THREAD

**Issue by supportagentmedium** [reapit/foundations#9931]
Hi Team,

Client(Gascoines) unable to include bullet in "Reapit Summary"
![image](https://github.com/reapit/foundations/assets/130666121/e2442bcb-2ff3-4ec9-9ab9-06b06c487ecf)

**Comment by Steve-Clark-Reapit** [comment]
To explain further, the web company get the list (as per the screenshot they attached) but want to add a bullet point before each row. However, they can't seem to do this.

The client doesn't want to amend this to have the bullet points in agency Cloud because that would potentially mean changes to templates etc. Also, they didn't have to do this in their previous software (Alto) so they think it is likely to get missed by some staff.

**Comment by AshDeeming** [comment]
Hi @supportagentmedium @Steve-Clark-Reapit 
Please could you confirm which section of AgencyCloud this relates to as all descriptions (unless extra) should be found within the properties endpoint

**Comment by Steve-Clark-Reapit** [comment]
@AshDeeming this is the Accommodation Summary - see example below from property RAV230082
![image](https://github.com/reapit/foundations/assets/129882073/d0f87751-2d16-4283-b698-a57b2d62272e)

Web company wants each row preceded by a bullet point, but client ideally does not want to add bullet points in Agency Cloud.

**Comment by plittlewood-rpt** [comment]
Hi all - if the customer doesn't want to add bullet points to their summary, the web company will need to do it. The API will not alter customer data before it outputs it, as this would cause problems when it came to handling data being written back into their system (bullet points would start to appear in AgencyCloud). Hope this helps. Thanks
