### ISSUE TITLE
Tenancy Deposit not match

### ISSUE THREAD

**Issue by abrahamseni** [reapit/foundations#9975]
When I try to post create a new tenancy the error is shown:
```json
{
    "statusCode": 400,
    "dateTime": "",
    "description": "The `deposit.sum` must match the `deposit.period` and `deposit.type` when all are provided."
}
```

This is a sample of the data that we post:
```json
  "deposit": {
    "heldBy": "stakeholder",
    "period": 5,
    "type": "weeksRent",
    "sum": 1384.61
  }
```

What caused the error?

I'm not familiar with the validation, please help elaborate on it.
Thanks.

**Comment by plittlewood-rpt** [comment]
@abrahamseni this error is advising you that the sum must match the calculated value of the period/type combination. In your example above, you specify a deposit of 5 weeks rent, which is a sum of 1384.61. Please check that 5 x [tenancy rent] equates to this value. The service is detecting a mismatch in the data you have provided, which is why it is returning this error. Please let me know if unclear, you just need to look at the rent on the tenancy you are posting and multiply that value by 5.

**Comment by abrahamseni** [comment]
@plittlewood-rpt Thanks.
I forgot that you already add this in #9394 
But when I try to change deposit sum to `rent * deposit.period` it still give me the same error

Here is the data that I post:
```json
  "rent": 1200,
  "rentFrequency": "monthly",
  "deposit": {
    "heldBy": "stakeholder",
    "period": 5,
    "type": "weeksRent",
    "sum": 6000
  },
```

**Comment by abrahamseni** [comment]
@plittlewood-rpt Gotcha.
It worked now. Thanks.
