### ISSUE TITLE
Get token Invalid Client error but Authentication Client Id and my Authentication Client Secret is correct

### ISSUE THREAD

**Issue by barnes-killianH** [reapit/foundations#9984]
**Summary**
Hello, 
I am unable to create a tokent via https://connect.reapit.cloud/ to interact with my previously created APP. 

I've followed the steps in the documentation on this page https://foundations-documentation.reapit.cloud/api/api-documentation#client-credentials-flow. 
I get my Authentication Client Id and my Authentication Client Secret on the APP details page.

However, I'm getting the invalid_client error and the documentation available for this error code (https://foundations-documentation.reapit.cloud/troubleshooting/authentication-issues) doesn't give me any more information about my problem.

**Details and/or supporting links and screenshots**
Here are the steps I took :
. Creation of the APP on https://developers.reapit.cloud/apps
. Retrieve Authentication Client Id and Authentication Client Secret from the APP details page
. Under Portman, create the POST request using the following curl:
curl --request POST \
  --url 'https://connect.reapit.cloud/token?grant_type=client_credentials&client_id=XCLIENTIDX' \
  --header 'Authorization: Basic XBASE64SECRETX' \
  --header 'content-type: application/x-www-form-urlencoded' \

Where XCLIENTIDX and XBASE64SECRETX are replaced by my values retrieved from my APP's detail page.

**Comment by AshDeeming** [comment]
Hi @barnes-killianH 
Please could you confirm the app name & whether the data being accessed is SBOX?

**Comment by barnes-killianH** [comment]
This is the name of the application barnes-international-heady-cushion. As far as the data is concerned, I can't tell you how to find out this information.

**Comment by plittlewood-rpt** [comment]
Hi @barnes-killianH I can get a token back for your app with no issues so it's likely something to do with the way you are encoding the auth header. One observation I have made though is that the grant_type and client_id shouldn't be in your request URI as you've posted above. They should be in the request body. Please can you email the full request to sinfo@reapitfoundations.zendesk.com and we should be able to find out what the issue is and advise further.
